import json
import requests
import time

API_KEY = 'AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk'

def translate_batch(texts, target_lang):
    if not texts:
        return []
    url = f'https://translation.googleapis.com/language/translate/v2?key={API_KEY}'
    results = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        payload = {'q': batch, 'target': target_lang, 'source': 'en'}
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                translations = [t['translatedText'] for t in data['data']['translations']]
                results.extend(translations)
            else:
                results.extend(batch)
        except:
            results.extend(batch)
    return results

# More TOEIC words - I, J, K, L words
WORDS = [
    ('ice', 'noun', 'frozen water', 'Break the ice.'),
    ('icon', 'noun', 'symbol', 'Industry icon.'),
    ('iconic', 'adj', 'symbolic', 'Iconic brand.'),
    ('idea', 'noun', 'thought', 'Great idea.'),
    ('ideal', 'adj', 'perfect', 'Ideal candidate.'),
    ('ideally', 'adv', 'perfectly', 'Ideally suited.'),
    ('identical', 'adj', 'same', 'Identical products.'),
    ('identification', 'noun', 'recognition', 'ID verification.'),
    ('identify', 'verb', 'to recognize', 'Identify needs.'),
    ('identity', 'noun', 'characteristics', 'Brand identity.'),
    ('ideology', 'noun', 'belief system', 'Corporate ideology.'),
    ('idle', 'adj', 'inactive', 'Idle capacity.'),
    ('ignorance', 'noun', 'lack of knowledge', 'Market ignorance.'),
    ('ignorant', 'adj', 'unaware', 'Ignorant of facts.'),
    ('ignore', 'verb', 'to disregard', 'Ignore warnings.'),
    ('ill', 'adj', 'sick', 'Ill effects.'),
    ('illegal', 'adj', 'unlawful', 'Illegal activity.'),
    ('illegally', 'adv', 'unlawfully', 'Illegally obtained.'),
    ('illness', 'noun', 'disease', 'Workplace illness.'),
    ('illuminate', 'verb', 'to light up', 'Illuminate issue.'),
    ('illusion', 'noun', 'false idea', 'Create illusion.'),
    ('illustrate', 'verb', 'to show', 'Illustrate point.'),
    ('illustration', 'noun', 'example', 'Clear illustration.'),
    ('image', 'noun', 'picture', 'Brand image.'),
    ('imagery', 'noun', 'visual images', 'Marketing imagery.'),
    ('imaginable', 'adj', 'conceivable', 'Every imaginable way.'),
    ('imaginary', 'adj', 'not real', 'Imaginary scenario.'),
    ('imagination', 'noun', 'creativity', 'Use imagination.'),
    ('imaginative', 'adj', 'creative', 'Imaginative solution.'),
    ('imagine', 'verb', 'to visualize', 'Imagine possibilities.'),
    ('imbalance', 'noun', 'lack of balance', 'Trade imbalance.'),
    ('imitate', 'verb', 'to copy', 'Imitate competitors.'),
    ('imitation', 'noun', 'copy', 'Cheap imitation.'),
    ('immature', 'adj', 'not fully developed', 'Immature market.'),
    ('immediate', 'adj', 'instant', 'Immediate action.'),
    ('immediately', 'adv', 'at once', 'Act immediately.'),
    ('immense', 'adj', 'huge', 'Immense potential.'),
    ('immensely', 'adv', 'hugely', 'Immensely popular.'),
    ('immigrant', 'noun', 'newcomer', 'Immigrant labor.'),
    ('immigration', 'noun', 'entering country', 'Immigration policy.'),
    ('imminent', 'adj', 'about to happen', 'Imminent launch.'),
    ('immune', 'adj', 'protected', 'Immune to criticism.'),
    ('immunity', 'noun', 'protection', 'Legal immunity.'),
    ('impact', 'noun', 'effect', 'Major impact.'),
    ('impair', 'verb', 'to damage', 'Impair performance.'),
    ('impairment', 'noun', 'damage', 'Asset impairment.'),
    ('impart', 'verb', 'to give', 'Impart knowledge.'),
    ('impartial', 'adj', 'unbiased', 'Impartial review.'),
    ('impediment', 'noun', 'obstacle', 'Trade impediment.'),
    ('impending', 'adj', 'upcoming', 'Impending deadline.'),
    ('imperative', 'adj', 'essential', 'Business imperative.'),
    ('imperial', 'adj', 'relating to empire', 'Imperial system.'),
    ('impersonal', 'adj', 'lacking warmth', 'Impersonal service.'),
    ('implement', 'verb', 'to carry out', 'Implement strategy.'),
    ('implementation', 'noun', 'execution', 'Plan implementation.'),
    ('implication', 'noun', 'consequence', 'Financial implication.'),
    ('implicit', 'adj', 'implied', 'Implicit agreement.'),
    ('implicitly', 'adv', 'by implication', 'Implicitly agreed.'),
    ('imply', 'verb', 'to suggest', 'Imply approval.'),
    ('import', 'noun', 'imported goods', 'Import duty.'),
    ('importance', 'noun', 'significance', 'Great importance.'),
    ('important', 'adj', 'significant', 'Important meeting.'),
    ('importantly', 'adv', 'significantly', 'More importantly.'),
    ('importer', 'noun', 'one who imports', 'Major importer.'),
    ('impose', 'verb', 'to force', 'Impose restrictions.'),
    ('imposition', 'noun', 'forcing', 'Tax imposition.'),
    ('impossible', 'adj', 'not possible', 'Impossible task.'),
    ('impractical', 'adj', 'not practical', 'Impractical solution.'),
    ('impress', 'verb', 'to affect strongly', 'Impress clients.'),
    ('impression', 'noun', 'effect', 'First impression.'),
    ('impressive', 'adj', 'remarkable', 'Impressive results.'),
    ('imprison', 'verb', 'to jail', 'Imprison fraudsters.'),
    ('imprisonment', 'noun', 'jailing', 'Face imprisonment.'),
    ('improbable', 'adj', 'unlikely', 'Improbable outcome.'),
    ('improper', 'adj', 'inappropriate', 'Improper conduct.'),
    ('improve', 'verb', 'to make better', 'Improve quality.'),
    ('improvement', 'noun', 'betterment', 'Continuous improvement.'),
    ('improvise', 'verb', 'to create spontaneously', 'Improvise solution.'),
    ('impulse', 'noun', 'sudden urge', 'Impulse buying.'),
    ('impulsive', 'adj', 'acting on impulse', 'Impulsive purchase.'),
    ('inability', 'noun', 'lack of ability', 'Inability to pay.'),
    ('inaccessible', 'adj', 'unreachable', 'Inaccessible market.'),
    ('inaccurate', 'adj', 'incorrect', 'Inaccurate data.'),
    ('inactive', 'adj', 'not active', 'Inactive account.'),
    ('inadequate', 'adj', 'insufficient', 'Inadequate resources.'),
    ('inappropriate', 'adj', 'unsuitable', 'Inappropriate behavior.'),
    ('inaugural', 'adj', 'first', 'Inaugural event.'),
    ('inaugurate', 'verb', 'to begin', 'Inaugurate program.'),
    ('inauguration', 'noun', 'beginning', 'Store inauguration.'),
    ('incentive', 'noun', 'motivation', 'Sales incentive.'),
    ('inch', 'noun', 'unit of measure', 'Every inch.'),
    ('incidence', 'noun', 'occurrence rate', 'Incidence of fraud.'),
    ('incident', 'noun', 'event', 'Security incident.'),
    ('incidental', 'adj', 'secondary', 'Incidental costs.'),
    ('incidentally', 'adv', 'by the way', 'Incidentally mentioned.'),
    ('incline', 'verb', 'to tend', 'Incline toward.'),
    ('include', 'verb', 'to contain', 'Include details.'),
    ('including', 'prep', 'containing', 'Including taxes.'),
    ('inclusion', 'noun', 'including', 'Diversity inclusion.'),
    ('inclusive', 'adj', 'including all', 'Inclusive pricing.'),
    ('income', 'noun', 'earnings', 'Annual income.'),
    ('incoming', 'adj', 'arriving', 'Incoming calls.'),
    ('incompatible', 'adj', 'not compatible', 'Incompatible systems.'),
    ('incompetent', 'adj', 'lacking ability', 'Incompetent staff.'),
    ('incomplete', 'adj', 'not finished', 'Incomplete order.'),
    ('inconsistent', 'adj', 'not consistent', 'Inconsistent quality.'),
    ('inconvenience', 'noun', 'trouble', 'Cause inconvenience.'),
    ('inconvenient', 'adj', 'troublesome', 'Inconvenient time.'),
    ('incorporate', 'verb', 'to include', 'Incorporate feedback.'),
    ('incorporation', 'noun', 'formation', 'Company incorporation.'),
    ('incorrect', 'adj', 'wrong', 'Incorrect information.'),
    ('increase', 'verb', 'to grow', 'Increase sales.'),
    ('increasingly', 'adv', 'more and more', 'Increasingly important.'),
    ('incredible', 'adj', 'amazing', 'Incredible growth.'),
    ('incredibly', 'adv', 'amazingly', 'Incredibly fast.'),
    ('increment', 'noun', 'increase', 'Salary increment.'),
    ('incremental', 'adj', 'gradual', 'Incremental change.'),
    ('incur', 'verb', 'to suffer', 'Incur costs.'),
    ('indebted', 'adj', 'owing', 'Deeply indebted.'),
    ('indeed', 'adv', 'in fact', 'Indeed true.'),
    ('indefinite', 'adj', 'not definite', 'Indefinite period.'),
    ('indefinitely', 'adv', 'without limit', 'Postponed indefinitely.'),
    ('independence', 'noun', 'freedom', 'Financial independence.'),
    ('independent', 'adj', 'self-governing', 'Independent contractor.'),
    ('independently', 'adv', 'by oneself', 'Work independently.'),
    ('index', 'noun', 'indicator', 'Stock index.'),
    ('indicate', 'verb', 'to show', 'Indicate interest.'),
    ('indication', 'noun', 'sign', 'Early indication.'),
    ('indicator', 'noun', 'sign', 'Performance indicator.'),
    ('indifferent', 'adj', 'unconcerned', 'Indifferent market.'),
    ('indigenous', 'adj', 'native', 'Indigenous market.'),
    ('indirect', 'adj', 'not direct', 'Indirect costs.'),
    ('indirectly', 'adv', 'not directly', 'Indirectly affected.'),
    ('indispensable', 'adj', 'essential', 'Indispensable service.'),
    ('individual', 'adj', 'single', 'Individual needs.'),
    ('individually', 'adv', 'separately', 'Individually assessed.'),
    ('indoor', 'adj', 'inside', 'Indoor facility.'),
    ('indoors', 'adv', 'inside', 'Work indoors.'),
    ('induce', 'verb', 'to cause', 'Induce demand.'),
    ('inducement', 'noun', 'incentive', 'Financial inducement.'),
    ('induction', 'noun', 'introduction', 'Employee induction.'),
    ('indulge', 'verb', 'to satisfy', 'Indulge customers.'),
    ('industrial', 'adj', 'relating to industry', 'Industrial sector.'),
    ('industrialization', 'noun', 'becoming industrial', 'Rapid industrialization.'),
    ('industrialize', 'verb', 'to become industrial', 'Industrialize economy.'),
    ('industrialized', 'adj', 'industrial', 'Industrialized nation.'),
    ('industry', 'noun', 'business sector', 'Tech industry.'),
    ('ineffective', 'adj', 'not effective', 'Ineffective strategy.'),
    ('inefficiency', 'noun', 'lack of efficiency', 'Reduce inefficiency.'),
    ('inefficient', 'adj', 'not efficient', 'Inefficient process.'),
    ('inequality', 'noun', 'disparity', 'Income inequality.'),
    ('inevitable', 'adj', 'unavoidable', 'Inevitable change.'),
    ('inevitably', 'adv', 'unavoidably', 'Inevitably leads to.'),
    ('inexpensive', 'adj', 'cheap', 'Inexpensive option.'),
    ('inexperienced', 'adj', 'lacking experience', 'Inexperienced staff.'),
    ('infant', 'noun', 'baby', 'Infant industry.'),
    ('inferior', 'adj', 'lower quality', 'Inferior product.'),
    ('infinite', 'adj', 'endless', 'Infinite possibilities.'),
    ('inflate', 'verb', 'to increase', 'Inflate prices.'),
    ('inflation', 'noun', 'price increase', 'High inflation.'),
    ('inflationary', 'adj', 'causing inflation', 'Inflationary pressure.'),
    ('inflexible', 'adj', 'rigid', 'Inflexible policy.'),
    ('inflict', 'verb', 'to cause', 'Inflict damage.'),
    ('influence', 'noun', 'effect', 'Market influence.'),
    ('influential', 'adj', 'powerful', 'Influential leader.'),
    ('influx', 'noun', 'inflow', 'Influx of capital.'),
    ('inform', 'verb', 'to tell', 'Inform customers.'),
    ('informal', 'adj', 'casual', 'Informal meeting.'),
    ('informally', 'adv', 'casually', 'Discuss informally.'),
    ('information', 'noun', 'data', 'Contact information.'),
    ('informative', 'adj', 'educational', 'Informative session.'),
    ('informed', 'adj', 'knowledgeable', 'Informed decision.'),
    ('infrastructure', 'noun', 'basic systems', 'IT infrastructure.'),
    ('infrequent', 'adj', 'rare', 'Infrequent occurrence.'),
    ('infringe', 'verb', 'to violate', 'Infringe patent.'),
    ('infringement', 'noun', 'violation', 'Copyright infringement.'),
    ('ingenious', 'adj', 'clever', 'Ingenious solution.'),
    ('ingredient', 'noun', 'component', 'Key ingredient.'),
    ('inhabit', 'verb', 'to live in', 'Inhabit space.'),
    ('inhabitant', 'noun', 'resident', 'Local inhabitants.'),
    ('inherent', 'adj', 'built-in', 'Inherent risk.'),
    ('inherently', 'adv', 'naturally', 'Inherently risky.'),
    ('inherit', 'verb', 'to receive', 'Inherit business.'),
    ('inheritance', 'noun', 'legacy', 'Inheritance tax.'),
    ('inhibit', 'verb', 'to prevent', 'Inhibit growth.'),
    ('initial', 'adj', 'first', 'Initial investment.'),
    ('initially', 'adv', 'at first', 'Initially skeptical.'),
    ('initiate', 'verb', 'to begin', 'Initiate project.'),
    ('initiation', 'noun', 'beginning', 'Project initiation.'),
    ('initiative', 'noun', 'plan', 'New initiative.'),
    ('injection', 'noun', 'infusion', 'Capital injection.'),
    ('injure', 'verb', 'to harm', 'Injure reputation.'),
    ('injury', 'noun', 'harm', 'Personal injury.'),
    ('injustice', 'noun', 'unfairness', 'Social injustice.'),
    ('ink', 'noun', 'liquid for writing', 'Sign in ink.'),
    ('inland', 'adj', 'interior', 'Inland revenue.'),
    ('inlet', 'noun', 'entrance', 'Air inlet.'),
    ('inmate', 'noun', 'prisoner', 'Prison inmates.'),
    ('inn', 'noun', 'small hotel', 'Country inn.'),
    ('inner', 'adj', 'internal', 'Inner circle.'),
    ('innocence', 'noun', 'guiltlessness', 'Prove innocence.'),
    ('innocent', 'adj', 'not guilty', 'Innocent party.'),
    ('innovate', 'verb', 'to create new', 'Innovate products.'),
    ('innovation', 'noun', 'new idea', 'Product innovation.'),
    ('innovative', 'adj', 'creative', 'Innovative approach.'),
    ('innovator', 'noun', 'creator', 'Industry innovator.'),
    ('input', 'noun', 'contribution', 'Valuable input.'),
    ('inquire', 'verb', 'to ask', 'Inquire about.'),
    ('inquiry', 'noun', 'question', 'Customer inquiry.'),
    ('insane', 'adj', 'crazy', 'Insane idea.'),
    ('inscribe', 'verb', 'to write on', 'Inscribe name.'),
    ('inscription', 'noun', 'writing', 'Award inscription.'),
    ('insect', 'noun', 'bug', 'Insect pest.'),
    ('insecure', 'adj', 'unsafe', 'Insecure system.'),
    ('insecurity', 'noun', 'lack of security', 'Job insecurity.'),
    ('insert', 'verb', 'to put in', 'Insert data.'),
    ('insertion', 'noun', 'putting in', 'Ad insertion.'),
    ('inside', 'prep', 'within', 'Inside information.'),
    ('insider', 'noun', 'one with inside access', 'Industry insider.'),
    ('insight', 'noun', 'understanding', 'Market insight.'),
    ('insightful', 'adj', 'perceptive', 'Insightful analysis.'),
    ('insignificant', 'adj', 'unimportant', 'Insignificant amount.'),
    ('insist', 'verb', 'to demand', 'Insist on quality.'),
    ('insistence', 'noun', 'demanding', 'Customer insistence.'),
    ('inspect', 'verb', 'to examine', 'Inspect goods.'),
    ('inspection', 'noun', 'examination', 'Quality inspection.'),
    ('inspector', 'noun', 'examiner', 'Safety inspector.'),
    ('inspiration', 'noun', 'motivation', 'Find inspiration.'),
    ('inspire', 'verb', 'to motivate', 'Inspire team.'),
    ('inspiring', 'adj', 'motivating', 'Inspiring leader.'),
    ('instability', 'noun', 'lack of stability', 'Economic instability.'),
    ('install', 'verb', 'to set up', 'Install software.'),
    ('installation', 'noun', 'setting up', 'System installation.'),
    ('installment', 'noun', 'payment portion', 'Monthly installment.'),
    ('instance', 'noun', 'example', 'For instance.'),
    ('instant', 'adj', 'immediate', 'Instant access.'),
    ('instantaneous', 'adj', 'immediate', 'Instantaneous response.'),
    ('instantly', 'adv', 'immediately', 'Respond instantly.'),
    ('instead', 'adv', 'in place of', 'Instead of.'),
    ('instinct', 'noun', 'natural tendency', 'Business instinct.'),
    ('instinctive', 'adj', 'natural', 'Instinctive decision.'),
    ('institute', 'noun', 'organization', 'Research institute.'),
    ('institution', 'noun', 'organization', 'Financial institution.'),
    ('institutional', 'adj', 'relating to institution', 'Institutional investor.'),
    ('instruct', 'verb', 'to teach', 'Instruct staff.'),
    ('instruction', 'noun', 'direction', 'Follow instructions.'),
    ('instructional', 'adj', 'educational', 'Instructional video.'),
    ('instructor', 'noun', 'teacher', 'Training instructor.'),
    ('instrument', 'noun', 'tool', 'Financial instrument.'),
    ('instrumental', 'adj', 'helpful', 'Instrumental in success.'),
    ('insufficient', 'adj', 'not enough', 'Insufficient funds.'),
    ('insulate', 'verb', 'to protect', 'Insulate from risk.'),
    ('insulation', 'noun', 'protection', 'Insulation material.'),
    ('insurance', 'noun', 'coverage', 'Health insurance.'),
    ('insure', 'verb', 'to provide coverage', 'Insure property.'),
    ('insured', 'noun', 'person covered', 'The insured.'),
    ('insurer', 'noun', 'insurance company', 'Major insurer.'),
    ('intact', 'adj', 'complete', 'Keep intact.'),
    ('intake', 'noun', 'consumption', 'Annual intake.'),
    ('intangible', 'adj', 'not physical', 'Intangible assets.'),
    ('integral', 'adj', 'essential', 'Integral part.'),
    ('integrate', 'verb', 'to combine', 'Integrate systems.'),
    ('integrated', 'adj', 'combined', 'Integrated approach.'),
    ('integration', 'noun', 'combination', 'System integration.'),
    ('integrity', 'noun', 'honesty', 'Business integrity.'),
    ('intellect', 'noun', 'intelligence', 'Sharp intellect.'),
    ('intellectual', 'adj', 'relating to intellect', 'Intellectual property.'),
    ('intelligence', 'noun', 'information', 'Market intelligence.'),
    ('intelligent', 'adj', 'smart', 'Intelligent design.'),
    ('intend', 'verb', 'to plan', 'Intend to expand.'),
    ('intended', 'adj', 'planned', 'Intended purpose.'),
    ('intense', 'adj', 'strong', 'Intense competition.'),
    ('intensely', 'adv', 'strongly', 'Intensely competitive.'),
    ('intensify', 'verb', 'to increase', 'Intensify efforts.'),
    ('intensity', 'noun', 'strength', 'Work intensity.'),
    ('intensive', 'adj', 'concentrated', 'Labor intensive.'),
    ('intent', 'noun', 'purpose', 'Letter of intent.'),
    ('intention', 'noun', 'plan', 'Clear intention.'),
    ('intentional', 'adj', 'deliberate', 'Intentional action.'),
    ('intentionally', 'adv', 'deliberately', 'Intentionally misleading.'),
    ('interact', 'verb', 'to communicate', 'Interact with customers.'),
    ('interaction', 'noun', 'communication', 'Customer interaction.'),
    ('interactive', 'adj', 'involving interaction', 'Interactive display.'),
    ('intercept', 'verb', 'to stop', 'Intercept message.'),
    ('interchange', 'noun', 'exchange', 'Data interchange.'),
    ('interest', 'noun', 'concern', 'Best interest.'),
    ('interested', 'adj', 'having interest', 'Interested parties.'),
    ('interesting', 'adj', 'engaging', 'Interesting proposal.'),
    ('interface', 'noun', 'connection point', 'User interface.'),
    ('interfere', 'verb', 'to obstruct', 'Interfere with.'),
    ('interference', 'noun', 'obstruction', 'Government interference.'),
    ('interim', 'adj', 'temporary', 'Interim report.'),
    ('interior', 'noun', 'inside', 'Interior design.'),
    ('intermediate', 'adj', 'middle', 'Intermediate level.'),
    ('internal', 'adj', 'inside', 'Internal audit.'),
    ('internally', 'adv', 'inside', 'Handled internally.'),
    ('international', 'adj', 'worldwide', 'International trade.'),
    ('internationally', 'adv', 'worldwide', 'Expand internationally.'),
    ('internet', 'noun', 'worldwide network', 'Internet access.'),
    ('interpret', 'verb', 'to explain', 'Interpret data.'),
    ('interpretation', 'noun', 'explanation', 'Data interpretation.'),
    ('interpreter', 'noun', 'translator', 'Hire interpreter.'),
    ('interrupt', 'verb', 'to stop', 'Interrupt meeting.'),
    ('interruption', 'noun', 'break', 'Service interruption.'),
    ('interval', 'noun', 'gap', 'Regular intervals.'),
    ('intervene', 'verb', 'to get involved', 'Intervene in dispute.'),
    ('intervention', 'noun', 'involvement', 'Government intervention.'),
    ('interview', 'noun', 'meeting', 'Job interview.'),
    ('interviewer', 'noun', 'questioner', 'Meet interviewer.'),
    ('intimate', 'adj', 'close', 'Intimate knowledge.'),
    ('intimidate', 'verb', 'to frighten', 'Intimidate competitors.'),
    ('into', 'prep', 'inside', 'Break into market.'),
    ('intolerable', 'adj', 'unbearable', 'Intolerable conditions.'),
    ('intranet', 'noun', 'internal network', 'Company intranet.'),
    ('intricate', 'adj', 'complex', 'Intricate design.'),
    ('intrigue', 'verb', 'to fascinate', 'Intrigue investors.'),
    ('intriguing', 'adj', 'fascinating', 'Intriguing offer.'),
    ('intrinsic', 'adj', 'inherent', 'Intrinsic value.'),
    ('introduce', 'verb', 'to present', 'Introduce product.'),
    ('introduction', 'noun', 'presentation', 'Product introduction.'),
    ('introductory', 'adj', 'initial', 'Introductory price.'),
    ('intrude', 'verb', 'to interfere', 'Intrude on privacy.'),
    ('intrusion', 'noun', 'interference', 'Data intrusion.'),
    ('intuition', 'noun', 'instinct', 'Trust intuition.'),
    ('intuitive', 'adj', 'instinctive', 'Intuitive design.'),
    ('invalid', 'adj', 'not valid', 'Invalid claim.'),
    ('invaluable', 'adj', 'extremely useful', 'Invaluable experience.'),
    ('invariably', 'adv', 'always', 'Invariably true.'),
    ('invasion', 'noun', 'intrusion', 'Privacy invasion.'),
    ('invent', 'verb', 'to create', 'Invent product.'),
    ('invention', 'noun', 'creation', 'New invention.'),
    ('inventive', 'adj', 'creative', 'Inventive approach.'),
    ('inventor', 'noun', 'creator', 'Patent inventor.'),
    ('inventory', 'noun', 'stock', 'Inventory management.'),
    ('inverse', 'adj', 'opposite', 'Inverse relationship.'),
    ('invest', 'verb', 'to put money into', 'Invest capital.'),
    ('investigate', 'verb', 'to examine', 'Investigate complaint.'),
    ('investigation', 'noun', 'examination', 'Internal investigation.'),
    ('investigator', 'noun', 'examiner', 'Private investigator.'),
    ('investment', 'noun', 'money invested', 'Return on investment.'),
    ('investor', 'noun', 'one who invests', 'Institutional investor.'),
    ('invisible', 'adj', 'unseen', 'Invisible barrier.'),
    ('invitation', 'noun', 'request to attend', 'Send invitation.'),
    ('invite', 'verb', 'to ask to come', 'Invite bids.'),
    ('invoice', 'noun', 'bill', 'Send invoice.'),
    ('invoke', 'verb', 'to call upon', 'Invoke clause.'),
    ('involve', 'verb', 'to include', 'Involve team.'),
    ('involved', 'adj', 'participating', 'Get involved.'),
    ('involvement', 'noun', 'participation', 'Active involvement.'),
    ('inward', 'adj', 'internal', 'Inward investment.'),
    ('iron', 'noun', 'metal', 'Iron out details.'),
    ('ironic', 'adj', 'contrary to expected', 'Ironic twist.'),
    ('ironically', 'adv', 'contrary to expected', 'Ironically successful.'),
    ('irony', 'noun', 'opposite of expected', 'Cruel irony.'),
    ('irrational', 'adj', 'illogical', 'Irrational decision.'),
    ('irregular', 'adj', 'not regular', 'Irregular pattern.'),
    ('irrelevant', 'adj', 'not relevant', 'Irrelevant information.'),
    ('irrespective', 'adj', 'regardless', 'Irrespective of size.'),
    ('irresponsible', 'adj', 'not responsible', 'Irresponsible behavior.'),
    ('irreversible', 'adj', 'permanent', 'Irreversible damage.'),
    ('irritate', 'verb', 'to annoy', 'Irritate customers.'),
    ('irritating', 'adj', 'annoying', 'Irritating delay.'),
    ('island', 'noun', 'land surrounded by water', 'Island location.'),
    ('isolate', 'verb', 'to separate', 'Isolate problem.'),
    ('isolated', 'adj', 'separate', 'Isolated incident.'),
    ('isolation', 'noun', 'separation', 'Work in isolation.'),
    ('issue', 'noun', 'matter', 'Key issue.'),
    ('item', 'noun', 'thing', 'Line item.'),
    ('itemize', 'verb', 'to list', 'Itemize expenses.'),
    ('itinerary', 'noun', 'travel plan', 'Business itinerary.'),
    ('jail', 'noun', 'prison', 'Face jail.'),
    ('jam', 'noun', 'blockage', 'Traffic jam.'),
    ('jar', 'noun', 'container', 'Cookie jar.'),
    ('jargon', 'noun', 'specialized language', 'Business jargon.'),
    ('jealous', 'adj', 'envious', 'Jealous competitors.'),
    ('jealousy', 'noun', 'envy', 'Professional jealousy.'),
    ('jeopardize', 'verb', 'to endanger', 'Jeopardize deal.'),
    ('jeopardy', 'noun', 'danger', 'In jeopardy.'),
    ('jet', 'noun', 'aircraft', 'Private jet.'),
    ('jewel', 'noun', 'gem', 'Crown jewel.'),
    ('jewelry', 'noun', 'ornaments', 'Jewelry store.'),
    ('job', 'noun', 'work', 'Job opening.'),
    ('jockey', 'verb', 'to maneuver', 'Jockey for position.'),
    ('jog', 'verb', 'to run slowly', 'Jog memory.'),
    ('join', 'verb', 'to connect', 'Join forces.'),
    ('joint', 'adj', 'shared', 'Joint venture.'),
    ('jointly', 'adv', 'together', 'Work jointly.'),
    ('joke', 'noun', 'jest', 'No joke.'),
    ('jolly', 'adj', 'happy', 'Jolly good.'),
    ('jolt', 'noun', 'shock', 'Market jolt.'),
    ('jostle', 'verb', 'to push', 'Jostle for attention.'),
    ('journal', 'noun', 'publication', 'Trade journal.'),
    ('journalism', 'noun', 'news writing', 'Business journalism.'),
    ('journalist', 'noun', 'reporter', 'Financial journalist.'),
    ('journey', 'noun', 'trip', 'Customer journey.'),
    ('joy', 'noun', 'happiness', 'Joy of success.'),
    ('joyful', 'adj', 'happy', 'Joyful occasion.'),
    ('judge', 'verb', 'to evaluate', 'Judge performance.'),
    ('judgment', 'noun', 'decision', 'Sound judgment.'),
    ('judicial', 'adj', 'relating to courts', 'Judicial review.'),
    ('juice', 'noun', 'liquid', 'Creative juice.'),
    ('jumble', 'noun', 'mix', 'Jumbled message.'),
    ('jump', 'verb', 'to leap', 'Jump at chance.'),
    ('junction', 'noun', 'connection', 'Key junction.'),
    ('junior', 'adj', 'lower rank', 'Junior staff.'),
    ('junk', 'noun', 'waste', 'Junk mail.'),
    ('jurisdiction', 'noun', 'authority', 'Legal jurisdiction.'),
    ('jury', 'noun', 'panel', 'Jury verdict.'),
    ('just', 'adj', 'fair', 'Just decision.'),
    ('justice', 'noun', 'fairness', 'Seek justice.'),
    ('justifiable', 'adj', 'defensible', 'Justifiable decision.'),
    ('justification', 'noun', 'reason', 'Cost justification.'),
    ('justify', 'verb', 'to defend', 'Justify expense.'),
    ('keen', 'adj', 'eager', 'Keen interest.'),
    ('keenly', 'adv', 'eagerly', 'Keenly aware.'),
    ('keep', 'verb', 'to retain', 'Keep records.'),
    ('keeper', 'noun', 'guardian', 'Gate keeper.'),
    ('kernel', 'noun', 'core', 'Kernel of truth.'),
    ('key', 'adj', 'important', 'Key factor.'),
    ('keyboard', 'noun', 'input device', 'Computer keyboard.'),
    ('keynote', 'noun', 'main theme', 'Keynote speech.'),
    ('kick', 'verb', 'to start', 'Kick off project.'),
    ('kickback', 'noun', 'illegal payment', 'Receive kickback.'),
    ('kickoff', 'noun', 'start', 'Project kickoff.'),
    ('kid', 'noun', 'child', 'New kid on block.'),
    ('kill', 'verb', 'to end', 'Kill project.'),
    ('killer', 'noun', 'destroyer', 'Deal killer.'),
    ('kind', 'noun', 'type', 'What kind.'),
    ('kindly', 'adv', 'please', 'Kindly assist.'),
    ('kindness', 'noun', 'friendliness', 'Show kindness.'),
    ('king', 'noun', 'ruler', 'Content is king.'),
    ('kingdom', 'noun', 'realm', 'Business kingdom.'),
    ('kiosk', 'noun', 'booth', 'Information kiosk.'),
    ('kit', 'noun', 'set', 'Starter kit.'),
    ('kitchen', 'noun', 'cooking area', 'Office kitchen.'),
    ('knee', 'noun', 'joint', 'Knee-jerk reaction.'),
    ('knife', 'noun', 'cutting tool', 'Knife edge.'),
    ('knit', 'verb', 'to join', 'Close-knit team.'),
    ('knock', 'verb', 'to hit', 'Knock out competition.'),
    ('knot', 'noun', 'tie', 'Tie the knot.'),
    ('know', 'verb', 'to understand', 'Know the market.'),
    ('know-how', 'noun', 'expertise', 'Technical know-how.'),
    ('knowing', 'adj', 'aware', 'Knowing look.'),
    ('knowledge', 'noun', 'understanding', 'Industry knowledge.'),
    ('knowledgeable', 'adj', 'well-informed', 'Knowledgeable staff.'),
    ('known', 'adj', 'recognized', 'Well known.'),
    ('lab', 'noun', 'laboratory', 'Research lab.'),
    ('label', 'noun', 'tag', 'Product label.'),
    ('labor', 'noun', 'work', 'Labor cost.'),
    ('laboratory', 'noun', 'research facility', 'Testing laboratory.'),
    ('laborer', 'noun', 'worker', 'Manual laborer.'),
    ('lace', 'noun', 'fabric', 'Shoelace.'),
    ('lack', 'noun', 'absence', 'Lack of funds.'),
    ('lacking', 'adj', 'missing', 'Lacking resources.'),
    ('ladder', 'noun', 'climbing tool', 'Corporate ladder.'),
    ('lag', 'verb', 'to fall behind', 'Lag behind.'),
    ('laid-back', 'adj', 'relaxed', 'Laid-back atmosphere.'),
    ('lake', 'noun', 'body of water', 'Lake resort.'),
    ('lamp', 'noun', 'light', 'Desk lamp.'),
    ('land', 'verb', 'to secure', 'Land contract.'),
    ('landing', 'noun', 'arrival', 'Soft landing.'),
    ('landlord', 'noun', 'property owner', 'Commercial landlord.'),
    ('landmark', 'noun', 'significant point', 'Landmark deal.'),
    ('landscape', 'noun', 'scene', 'Business landscape.'),
    ('lane', 'noun', 'path', 'Fast lane.'),
    ('language', 'noun', 'speech', 'Business language.'),
    ('lap', 'noun', 'circuit', 'Final lap.'),
    ('laptop', 'noun', 'portable computer', 'Work laptop.'),
    ('large', 'adj', 'big', 'Large scale.'),
    ('largely', 'adv', 'mostly', 'Largely successful.'),
    ('laser', 'noun', 'focused light', 'Laser focus.'),
    ('last', 'adj', 'final', 'Last resort.'),
    ('lasting', 'adj', 'permanent', 'Lasting impact.'),
    ('lastly', 'adv', 'finally', 'Lastly mentioned.'),
    ('late', 'adj', 'after time', 'Late delivery.'),
    ('lately', 'adv', 'recently', 'Lately improved.'),
    ('latent', 'adj', 'hidden', 'Latent demand.'),
    ('later', 'adv', 'afterward', 'See later.'),
    ('lateral', 'adj', 'sideways', 'Lateral move.'),
    ('latest', 'adj', 'most recent', 'Latest news.'),
    ('latitude', 'noun', 'freedom', 'Give latitude.'),
    ('latter', 'adj', 'second of two', 'The latter option.'),
    ('laugh', 'verb', 'to express joy', 'Laugh off.'),
    ('laughter', 'noun', 'expression of joy', 'Office laughter.'),
    ('launch', 'verb', 'to start', 'Launch product.'),
    ('laundry', 'noun', 'washing', 'Laundry list.'),
    ('lavish', 'adj', 'extravagant', 'Lavish spending.'),
    ('law', 'noun', 'rule', 'Business law.'),
    ('lawful', 'adj', 'legal', 'Lawful activity.'),
    ('lawn', 'noun', 'grass area', 'Office lawn.'),
    ('lawsuit', 'noun', 'legal case', 'File lawsuit.'),
    ('lawyer', 'noun', 'attorney', 'Corporate lawyer.'),
    ('lay', 'verb', 'to put', 'Lay foundation.'),
    ('layer', 'noun', 'level', 'Management layer.'),
    ('layoff', 'noun', 'job cut', 'Mass layoffs.'),
    ('layout', 'noun', 'arrangement', 'Office layout.'),
    ('lazy', 'adj', 'idle', 'Lazy approach.'),
    ('lead', 'verb', 'to guide', 'Lead team.'),
    ('leader', 'noun', 'guide', 'Market leader.'),
    ('leadership', 'noun', 'guidance', 'Strong leadership.'),
    ('leading', 'adj', 'top', 'Leading company.'),
    ('leaf', 'noun', 'page', 'Turn new leaf.'),
    ('leaflet', 'noun', 'brochure', 'Information leaflet.'),
    ('league', 'noun', 'group', 'Big league.'),
    ('leak', 'verb', 'to disclose', 'Information leaked.'),
    ('leakage', 'noun', 'escape', 'Data leakage.'),
    ('lean', 'adj', 'efficient', 'Lean manufacturing.'),
    ('leap', 'noun', 'jump', 'Quantum leap.'),
    ('learn', 'verb', 'to acquire knowledge', 'Learn skills.'),
    ('learner', 'noun', 'student', 'Fast learner.'),
    ('learning', 'noun', 'education', 'Continuous learning.'),
    ('lease', 'noun', 'rental agreement', 'Sign lease.'),
    ('least', 'adj', 'smallest', 'At least.'),
    ('leather', 'noun', 'animal skin', 'Leather goods.'),
    ('leave', 'verb', 'to depart', 'Leave company.'),
    ('lecture', 'noun', 'speech', 'Guest lecture.'),
    ('lecturer', 'noun', 'speaker', 'Visiting lecturer.'),
    ('ledger', 'noun', 'record book', 'General ledger.'),
    ('left', 'adj', 'remaining', 'Time left.'),
    ('leg', 'noun', 'support', 'Leg work.'),
    ('legacy', 'noun', 'inheritance', 'Legacy system.'),
    ('legal', 'adj', 'lawful', 'Legal department.'),
    ('legality', 'noun', 'lawfulness', 'Question legality.'),
    ('legally', 'adv', 'lawfully', 'Legally binding.'),
    ('legend', 'noun', 'famous person', 'Industry legend.'),
    ('legendary', 'adj', 'famous', 'Legendary success.'),
    ('legislation', 'noun', 'laws', 'New legislation.'),
    ('legislative', 'adj', 'law-making', 'Legislative change.'),
    ('legislator', 'noun', 'lawmaker', 'Contact legislator.'),
    ('legislature', 'noun', 'law-making body', 'State legislature.'),
    ('legitimate', 'adj', 'valid', 'Legitimate business.'),
    ('legitimately', 'adv', 'validly', 'Legitimately earned.'),
    ('leisure', 'noun', 'free time', 'Leisure industry.'),
    ('lend', 'verb', 'to loan', 'Lend support.'),
    ('lender', 'noun', 'loan provider', 'Mortgage lender.'),
    ('lending', 'noun', 'loaning', 'Bank lending.'),
    ('length', 'noun', 'distance', 'At length.'),
    ('lengthen', 'verb', 'to extend', 'Lengthen deadline.'),
    ('lengthy', 'adj', 'long', 'Lengthy process.'),
    ('lens', 'noun', 'glass', 'Through lens.'),
    ('less', 'adj', 'smaller amount', 'Less risk.'),
    ('lessen', 'verb', 'to reduce', 'Lessen impact.'),
    ('lesser', 'adj', 'smaller', 'Lesser extent.'),
    ('lesson', 'noun', 'teaching', 'Valuable lesson.'),
    ('let', 'verb', 'to allow', 'Let go.'),
    ('lethal', 'adj', 'deadly', 'Lethal blow.'),
    ('letter', 'noun', 'written message', 'Cover letter.'),
    ('level', 'noun', 'degree', 'Management level.'),
    ('leverage', 'noun', 'influence', 'Financial leverage.'),
    ('levy', 'verb', 'to impose', 'Levy tax.'),
    ('liability', 'noun', 'responsibility', 'Legal liability.'),
    ('liable', 'adj', 'responsible', 'Held liable.'),
    ('liaison', 'noun', 'connection', 'Client liaison.'),
    ('liberal', 'adj', 'generous', 'Liberal policy.'),
    ('liberalization', 'noun', 'freeing up', 'Trade liberalization.'),
    ('liberalize', 'verb', 'to free up', 'Liberalize market.'),
    ('liberally', 'adv', 'generously', 'Spend liberally.'),
    ('liberate', 'verb', 'to free', 'Liberate resources.'),
    ('liberation', 'noun', 'freedom', 'Market liberation.'),
    ('liberty', 'noun', 'freedom', 'Take liberty.'),
    ('library', 'noun', 'book collection', 'Resource library.'),
    ('license', 'noun', 'permit', 'Software license.'),
    ('licensee', 'noun', 'license holder', 'Franchise licensee.'),
    ('licensing', 'noun', 'granting license', 'Licensing agreement.'),
    ('lid', 'noun', 'cover', 'Put lid on.'),
    ('lie', 'verb', 'to recline', 'Lie ahead.'),
    ('life', 'noun', 'existence', 'Product life.'),
    ('lifecycle', 'noun', 'life stages', 'Product lifecycle.'),
    ('lifelong', 'adj', 'entire life', 'Lifelong learning.'),
    ('lifestyle', 'noun', 'way of living', 'Lifestyle brand.'),
    ('lifetime', 'noun', 'duration of life', 'Customer lifetime.'),
    ('lift', 'verb', 'to raise', 'Lift ban.'),
    ('light', 'adj', 'not heavy', 'Light workload.'),
    ('lighten', 'verb', 'to reduce', 'Lighten load.'),
    ('lighting', 'noun', 'illumination', 'Office lighting.'),
    ('lightly', 'adv', 'gently', 'Take lightly.'),
    ('lightweight', 'adj', 'not heavy', 'Lightweight design.'),
    ('like', 'prep', 'similar to', 'Like this.'),
    ('likelihood', 'noun', 'probability', 'High likelihood.'),
    ('likely', 'adj', 'probable', 'Most likely.'),
    ('likewise', 'adv', 'similarly', 'Likewise important.'),
    ('limb', 'noun', 'branch', 'Go out on limb.'),
    ('lime', 'noun', 'citrus fruit', 'In the limelight.'),
    ('limit', 'noun', 'restriction', 'Budget limit.'),
    ('limitation', 'noun', 'restriction', 'Know limitations.'),
    ('limited', 'adj', 'restricted', 'Limited edition.'),
    ('limiting', 'adj', 'restricting', 'Limiting factor.'),
    ('line', 'noun', 'row', 'Product line.'),
    ('linear', 'adj', 'in a line', 'Linear growth.'),
    ('lineup', 'noun', 'arrangement', 'Product lineup.'),
    ('linger', 'verb', 'to remain', 'Doubts linger.'),
    ('lingering', 'adj', 'remaining', 'Lingering concerns.'),
    ('link', 'noun', 'connection', 'Supply chain link.'),
    ('linkage', 'noun', 'connection', 'Strong linkage.'),
    ('lion', 'noun', 'large cat', 'Lion share.'),
    ('lip', 'noun', 'edge', 'Lip service.'),
    ('liquid', 'noun', 'fluid', 'Liquid assets.'),
    ('liquidate', 'verb', 'to sell off', 'Liquidate inventory.'),
    ('liquidation', 'noun', 'selling off', 'Company liquidation.'),
    ('liquidity', 'noun', 'cash availability', 'Market liquidity.'),
    ('liquor', 'noun', 'alcohol', 'Liquor license.'),
    ('list', 'noun', 'series', 'Waiting list.'),
    ('listen', 'verb', 'to hear', 'Listen carefully.'),
    ('listener', 'noun', 'one who listens', 'Good listener.'),
    ('listing', 'noun', 'entry', 'Stock listing.'),
    ('literacy', 'noun', 'ability to read', 'Financial literacy.'),
    ('literal', 'adj', 'exact', 'Literal meaning.'),
    ('literally', 'adv', 'exactly', 'Literally true.'),
    ('literary', 'adj', 'relating to literature', 'Literary rights.'),
    ('literature', 'noun', 'written works', 'Product literature.'),
    ('litigation', 'noun', 'legal action', 'Avoid litigation.'),
    ('little', 'adj', 'small', 'Little chance.'),
    ('live', 'adj', 'happening now', 'Live broadcast.'),
    ('livelihood', 'noun', 'means of living', 'Earn livelihood.'),
    ('lively', 'adj', 'energetic', 'Lively discussion.'),
    ('liver', 'noun', 'organ', 'Deliver.'),
    ('living', 'noun', 'livelihood', 'Cost of living.'),
    ('load', 'noun', 'burden', 'Work load.'),
    ('loan', 'noun', 'borrowed money', 'Bank loan.'),
    ('lobby', 'verb', 'to influence', 'Lobby government.'),
    ('lobbying', 'noun', 'influencing', 'Industry lobbying.'),
    ('lobbyist', 'noun', 'influence seeker', 'Hire lobbyist.'),
    ('local', 'adj', 'nearby', 'Local market.'),
    ('locality', 'noun', 'area', 'Business locality.'),
    ('localize', 'verb', 'to adapt locally', 'Localize product.'),
    ('locally', 'adv', 'nearby', 'Source locally.'),
    ('locate', 'verb', 'to find', 'Locate office.'),
    ('location', 'noun', 'place', 'Prime location.'),
    ('lock', 'verb', 'to secure', 'Lock in price.'),
    ('locker', 'noun', 'storage unit', 'Employee locker.'),
    ('lodge', 'verb', 'to submit', 'Lodge complaint.'),
    ('lofty', 'adj', 'high', 'Lofty goals.'),
    ('log', 'noun', 'record', 'Activity log.'),
    ('logic', 'noun', 'reasoning', 'Business logic.'),
    ('logical', 'adj', 'reasonable', 'Logical step.'),
    ('logically', 'adv', 'reasonably', 'Logically follows.'),
    ('logistics', 'noun', 'organization', 'Supply chain logistics.'),
    ('logo', 'noun', 'symbol', 'Company logo.'),
    ('lone', 'adj', 'single', 'Lone voice.'),
    ('lonely', 'adj', 'isolated', 'Lonely at top.'),
    ('long', 'adj', 'extended', 'Long term.'),
    ('longevity', 'noun', 'long life', 'Company longevity.'),
    ('long-range', 'adj', 'far-reaching', 'Long-range plan.'),
    ('long-standing', 'adj', 'established', 'Long-standing relationship.'),
    ('long-term', 'adj', 'extended period', 'Long-term strategy.'),
    ('look', 'verb', 'to see', 'Look ahead.'),
    ('lookout', 'noun', 'watch', 'On the lookout.'),
    ('loom', 'verb', 'to appear', 'Challenges loom.'),
    ('looming', 'adj', 'approaching', 'Looming deadline.'),
    ('loop', 'noun', 'circle', 'In the loop.'),
    ('loophole', 'noun', 'gap', 'Tax loophole.'),
    ('loose', 'adj', 'not tight', 'Loose ends.'),
    ('loosen', 'verb', 'to make less tight', 'Loosen restrictions.'),
    ('lord', 'noun', 'ruler', 'Landlord.'),
    ('lorry', 'noun', 'truck', 'Delivery lorry.'),
    ('lose', 'verb', 'to be deprived of', 'Lose money.'),
    ('loser', 'noun', 'one who loses', 'Clear loser.'),
    ('loss', 'noun', 'deprivation', 'Financial loss.'),
    ('lost', 'adj', 'missing', 'Lost opportunity.'),
    ('lot', 'noun', 'large amount', 'Parking lot.'),
    ('lottery', 'noun', 'game of chance', 'Win lottery.'),
    ('loud', 'adj', 'noisy', 'Loud and clear.'),
    ('loudly', 'adv', 'noisily', 'Speak loudly.'),
    ('lounge', 'noun', 'waiting area', 'Business lounge.'),
    ('love', 'noun', 'affection', 'Labor of love.'),
    ('lovely', 'adj', 'beautiful', 'Lovely gesture.'),
    ('lover', 'noun', 'enthusiast', 'Nature lover.'),
    ('low', 'adj', 'not high', 'Low cost.'),
    ('lower', 'verb', 'to reduce', 'Lower prices.'),
    ('loyal', 'adj', 'faithful', 'Loyal customer.'),
    ('loyalty', 'noun', 'faithfulness', 'Brand loyalty.'),
    ('luck', 'noun', 'fortune', 'Good luck.'),
    ('luckily', 'adv', 'fortunately', 'Luckily saved.'),
    ('lucky', 'adj', 'fortunate', 'Lucky break.'),
    ('lucrative', 'adj', 'profitable', 'Lucrative deal.'),
    ('luggage', 'noun', 'bags', 'Carry-on luggage.'),
    ('lumber', 'noun', 'wood', 'Lumber industry.'),
    ('lump', 'noun', 'mass', 'Lump sum.'),
    ('lunch', 'noun', 'midday meal', 'Business lunch.'),
    ('luncheon', 'noun', 'formal lunch', 'Award luncheon.'),
    ('lure', 'verb', 'to attract', 'Lure customers.'),
    ('lurk', 'verb', 'to wait hidden', 'Dangers lurk.'),
    ('lush', 'adj', 'rich', 'Lush environment.'),
    ('lust', 'noun', 'strong desire', 'Lust for success.'),
    ('luxurious', 'adj', 'very comfortable', 'Luxurious hotel.'),
    ('luxury', 'noun', 'extravagance', 'Luxury brand.'),
]

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    existing = data.get('words', data)

print(f'기존 단어: {len(existing)}개')
word_set = {w['word'].lower() for w in existing}
new_words = [(w,p,m,e) for w,p,m,e in WORDS if w.lower() not in word_set]
print(f'추가할 새 단어: {len(new_words)}개')

if not new_words:
    print('추가할 단어 없음')
    exit()

langs = ['ko','ja','zh','es','pt','de','fr','vi','ar','id']
trans_by_lang = {}
print('번역 중...')
for lang in langs:
    print(f'  {lang}...', end=' ', flush=True)
    trans_by_lang[lang] = translate_batch([w[2] for w in new_words], lang)
    print('완료')
    time.sleep(0.2)

count = len(existing)
total = count + len(new_words)
for i, (word, pos, meaning, example) in enumerate(new_words):
    word_id = count + i + 1
    if word_id <= total // 4:
        level = '0-400'
    elif word_id <= total // 2:
        level = '400-600'
    elif word_id <= total * 3 // 4:
        level = '600-800'
    else:
        level = '800-990'
    trans = {lang: trans_by_lang[lang][i] if i < len(trans_by_lang[lang]) else meaning for lang in langs}
    existing.append({'id': word_id, 'word': word, 'meaning': meaning, 'example': example, 'pos': pos, 'level': level, 'translations': trans})

with open('assets/data/words.json', 'w', encoding='utf-8') as f:
    json.dump({'words': existing}, f, ensure_ascii=False, indent=2)

level_counts = {}
for w in existing:
    lv = w.get('level', '0-400')
    level_counts[lv] = level_counts.get(lv, 0) + 1

print(f'\n총 단어 수: {len(existing)}개')
for lv in ['0-400', '400-600', '600-800', '800-990']:
    print(f'  {lv}: {level_counts.get(lv, 0)}개')
