import json
import requests
import time

API_KEY = 'AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk'

def translate_batch(texts, target_lang):
    if not texts:
        return []
    url = f'https://translation.googleapis.com/language/translate/v2?key={API_KEY}'
    results = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        payload = {'q': batch, 'target': target_lang, 'source': 'en'}
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                translations = [t['translatedText'] for t in data['data']['translations']]
                results.extend(translations)
            else:
                results.extend(batch)
        except Exception as e:
            results.extend(batch)
    return results

WORDS = [
    ('pace', 'noun', 'a rate of speed', 'Keep up the pace.'),
    ('package', 'noun', 'a wrapped bundle', 'Package arrived.'),
    ('panel', 'noun', 'a group of experts', 'Expert panel.'),
    ('parallel', 'adj', 'similar', 'Parallel campaigns.'),
    ('parameter', 'noun', 'a boundary', 'Set parameters.'),
    ('partial', 'adj', 'not complete', 'Partial payment.'),
    ('participate', 'verb', 'to take part', 'Please participate.'),
    ('particular', 'adj', 'specific', 'This particular model.'),
    ('patent', 'noun', 'exclusive rights', 'File a patent.'),
    ('patience', 'noun', 'calm endurance', 'Requires patience.'),
    ('pattern', 'noun', 'regular form', 'Growth pattern.'),
    ('peak', 'noun', 'highest point', 'Sales peak.'),
    ('penalty', 'noun', 'a punishment', 'Late penalty.'),
    ('pending', 'adj', 'waiting', 'Decision pending.'),
    ('pension', 'noun', 'retirement income', 'Pension plan.'),
    ('perceive', 'verb', 'to understand', 'Perceive correctly.'),
    ('perception', 'noun', 'understanding', 'Public perception.'),
    ('permanent', 'adj', 'lasting', 'Permanent position.'),
    ('permission', 'noun', 'consent', 'Request permission.'),
    ('persist', 'verb', 'to continue', 'Problems persist.'),
    ('personnel', 'noun', 'employees', 'Personnel files.'),
    ('perspective', 'noun', 'point of view', 'New perspective.'),
    ('persuade', 'verb', 'to convince', 'Persuade them.'),
    ('phase', 'noun', 'a stage', 'Phase one.'),
    ('philosophy', 'noun', 'beliefs', 'Business philosophy.'),
    ('pilot', 'noun', 'a test', 'Pilot program.'),
    ('pioneer', 'verb', 'to be first', 'Pioneer technology.'),
    ('pitch', 'noun', 'presentation', 'Sales pitch.'),
    ('platform', 'noun', 'a base system', 'Online platform.'),
    ('pledge', 'verb', 'to promise', 'Pledge support.'),
    ('poll', 'noun', 'a survey', 'Customer poll.'),
    ('portfolio', 'noun', 'collection', 'Investment portfolio.'),
    ('portion', 'noun', 'a part', 'A portion.'),
    ('pose', 'verb', 'to present', 'Pose a challenge.'),
    ('possess', 'verb', 'to own', 'Possess skills.'),
    ('possibility', 'noun', 'a chance', 'Explore possibilities.'),
    ('postpone', 'verb', 'to delay', 'Postpone meeting.'),
    ('potential', 'noun', 'possibility', 'Market potential.'),
    ('practical', 'adj', 'useful', 'Practical solution.'),
    ('praise', 'verb', 'express approval', 'Praise good work.'),
    ('precaution', 'noun', 'preventive measure', 'Safety precautions.'),
    ('precise', 'adj', 'exact', 'Precise measurements.'),
    ('predict', 'verb', 'to forecast', 'Predict sales.'),
    ('preference', 'noun', 'liking', 'State preference.'),
    ('preliminary', 'adj', 'initial', 'Preliminary results.'),
    ('premise', 'noun', 'building', 'Company premises.'),
    ('premium', 'noun', 'high quality', 'Premium products.'),
    ('preparation', 'noun', 'getting ready', 'Careful preparation.'),
    ('preserve', 'verb', 'to maintain', 'Preserve reputation.'),
    ('preside', 'verb', 'to be in charge', 'Preside over meeting.'),
    ('prestige', 'noun', 'high status', 'Position of prestige.'),
    ('prevail', 'verb', 'to be widespread', 'Common sense prevailed.'),
    ('primary', 'adj', 'main', 'Primary focus.'),
    ('prime', 'adj', 'most important', 'Prime location.'),
    ('principal', 'adj', 'first in importance', 'Principal reason.'),
    ('principle', 'noun', 'fundamental truth', 'Sound principles.'),
    ('prior', 'adj', 'earlier', 'Prior to meeting.'),
    ('privacy', 'noun', 'freedom from intrusion', 'Customer privacy.'),
    ('privilege', 'noun', 'special right', 'A privilege.'),
    ('probability', 'noun', 'likelihood', 'High probability.'),
    ('probe', 'verb', 'to investigate', 'Probe further.'),
    ('processor', 'noun', 'one that processes', 'Payment processor.'),
    ('procure', 'verb', 'to obtain', 'Procure materials.'),
    ('productive', 'adj', 'achieving a lot', 'Productive meeting.'),
    ('profession', 'noun', 'occupation', 'Respected profession.'),
    ('profitable', 'adj', 'making profit', 'Profitable business.'),
    ('profound', 'adj', 'very deep', 'Profound impact.'),
    ('projection', 'noun', 'estimate', 'Sales projections.'),
    ('prolong', 'verb', 'to extend', 'Do not prolong.'),
    ('prominent', 'adj', 'important', 'Prominent figure.'),
    ('prompt', 'adj', 'quick', 'Prompt response.'),
    ('proof', 'noun', 'evidence', 'Proof of purchase.'),
    ('proportion', 'noun', 'relative size', 'In proportion.'),
    ('prospect', 'noun', 'potential customer', 'Promising prospect.'),
    ('prospective', 'adj', 'potential', 'Prospective clients.'),
    ('prosper', 'verb', 'to succeed', 'Business prospers.'),
    ('prosperity', 'noun', 'financial success', 'Economic prosperity.'),
    ('provision', 'noun', 'supply', 'Make provisions.'),
    ('provoke', 'verb', 'to cause', 'Do not provoke.'),
    ('proximity', 'noun', 'nearness', 'Close proximity.'),
    ('publicity', 'noun', 'public attention', 'Good publicity.'),
    ('punctual', 'adj', 'on time', 'Be punctual.'),
    ('quarterly', 'adj', 'every three months', 'Quarterly report.'),
    ('query', 'noun', 'a question', 'Address queries.'),
    ('quest', 'noun', 'a search', 'Quest for excellence.'),
    ('questionnaire', 'noun', 'set of questions', 'Complete questionnaire.'),
    ('quota', 'noun', 'fixed share', 'Sales quota.'),
    ('radical', 'adj', 'extreme', 'Radical change.'),
    ('ratio', 'noun', 'proportion', 'Debt ratio.'),
    ('rational', 'adj', 'based on reason', 'Rational decision.'),
    ('raw', 'adj', 'unprocessed', 'Raw materials.'),
    ('realistic', 'adj', 'practical', 'Realistic goals.'),
    ('realm', 'noun', 'area or field', 'Realm of finance.'),
    ('reassure', 'verb', 'restore confidence', 'Reassure customer.'),
    ('rebate', 'noun', 'partial refund', 'Mail-in rebate.'),
    ('recession', 'noun', 'economic decline', 'During recession.'),
    ('recipe', 'noun', 'formula', 'Recipe for success.'),
    ('recipient', 'noun', 'one who receives', 'Email recipients.'),
    ('reciprocal', 'adj', 'mutual', 'Reciprocal agreement.'),
    ('recognition', 'noun', 'acknowledgment', 'Employee recognition.'),
    ('recommendation', 'noun', 'suggestion', 'Based on recommendation.'),
    ('reconcile', 'verb', 'make consistent', 'Reconcile accounts.'),
    ('recovery', 'noun', 'returning', 'Economic recovery.'),
    ('recruitment', 'noun', 'hiring process', 'Recruitment drive.'),
    ('rectify', 'verb', 'to correct', 'Rectify error.'),
    ('recur', 'verb', 'happen again', 'Problems recur.'),
    ('redundant', 'adj', 'no longer needed', 'Became redundant.'),
    ('referendum', 'noun', 'public vote', 'Held referendum.'),
    ('refine', 'verb', 'to improve', 'Refine strategy.'),
    ('refresh', 'verb', 'to renew', 'Refresh skills.'),
    ('regardless', 'adv', 'despite everything', 'Proceed regardless.'),
    ('regional', 'adj', 'relating to region', 'Regional manager.'),
    ('registration', 'noun', 'act of registering', 'Complete registration.'),
    ('reinforce', 'verb', 'to strengthen', 'Reinforce message.'),
    ('relax', 'verb', 'become less tense', 'Relax restrictions.'),
    ('relief', 'noun', 'reduction', 'Tax relief.'),
    ('relieve', 'verb', 'to reduce', 'Relieve pressure.'),
    ('reluctant', 'adj', 'unwilling', 'Reluctant to change.'),
    ('remainder', 'noun', 'what is left', 'Remainder of order.'),
    ('remarkable', 'adj', 'worthy of attention', 'Remarkable achievement.'),
    ('remedy', 'noun', 'solution', 'Find remedy.'),
    ('renewal', 'noun', 'making new again', 'Contract renewal.'),
    ('rental', 'noun', 'payment for use', 'Rental costs.'),
    ('reorganize', 'verb', 'arrange again', 'Reorganize department.'),
    ('replacement', 'noun', 'substitute', 'Find replacement.'),
    ('replica', 'noun', 'copy', 'Exact replica.'),
    ('representation', 'noun', 'acting for another', 'Legal representation.'),
    ('representative', 'noun', 'one who represents', 'Sales representative.'),
    ('reproduce', 'verb', 'to copy', 'Reproduce document.'),
    ('reputation', 'noun', 'opinion held', 'Protect reputation.'),
    ('reschedule', 'verb', 'schedule again', 'Reschedule meeting.'),
    ('reservation', 'noun', 'arrangement', 'Make reservation.'),
    ('residence', 'noun', 'place to live', 'Place of residence.'),
    ('resident', 'noun', 'one who lives', 'Local residents.'),
    ('resignation', 'noun', 'act of quitting', 'Submit resignation.'),
    ('resist', 'verb', 'to oppose', 'Resist change.'),
    ('resolution', 'noun', 'solution', 'Conflict resolution.'),
    ('resort', 'verb', 'to turn to', 'Resort to measures.'),
    ('respective', 'adj', 'belonging to each', 'Respective roles.'),
    ('responsibility', 'noun', 'duty', 'Take responsibility.'),
    ('restoration', 'noun', 'bringing back', 'Service restoration.'),
    ('restriction', 'noun', 'limitation', 'Travel restrictions.'),
    ('restructure', 'verb', 'organize differently', 'Restructure company.'),
    ('retention', 'noun', 'keeping', 'Customer retention.'),
    ('retrospect', 'noun', 'looking back', 'In retrospect.'),
    ('revision', 'noun', 'change', 'Budget revision.'),
    ('revive', 'verb', 'bring back', 'Revive brand.'),
    ('revolution', 'noun', 'major change', 'Digital revolution.'),
    ('rigid', 'adj', 'not flexible', 'Rigid policies.'),
    ('rigorous', 'adj', 'strict', 'Rigorous testing.'),
    ('rival', 'noun', 'competitor', 'Main rival.'),
    ('robust', 'adj', 'strong', 'Robust sales.'),
    ('rotate', 'verb', 'turn or alternate', 'Rotate shifts.'),
    ('rough', 'adj', 'approximate', 'Rough estimate.'),
    ('routine', 'noun', 'regular procedure', 'Daily routine.'),
    ('ruling', 'noun', 'decision', 'Court ruling.'),
    ('rural', 'adj', 'countryside', 'Rural markets.'),
    ('safeguard', 'verb', 'to protect', 'Safeguard data.'),
    ('sanction', 'noun', 'penalty', 'Economic sanctions.'),
    ('satisfactory', 'adj', 'acceptable', 'Satisfactory results.'),
    ('saturate', 'verb', 'fill completely', 'Saturate market.'),
    ('savings', 'noun', 'money saved', 'Cost savings.'),
    ('scarce', 'adj', 'in short supply', 'Resources scarce.'),
    ('scatter', 'verb', 'to spread', 'Scattered locations.'),
    ('scenario', 'noun', 'possible situation', 'Worst scenario.'),
    ('scope', 'noun', 'extent', 'Project scope.'),
    ('scrutiny', 'noun', 'close examination', 'Under scrutiny.'),
    ('seal', 'verb', 'close securely', 'Seal the deal.'),
    ('sector', 'noun', 'part of economy', 'Private sector.'),
    ('segment', 'noun', 'section', 'Market segment.'),
    ('selection', 'noun', 'choice', 'Wide selection.'),
    ('seminar', 'noun', 'training session', 'Attend seminar.'),
    ('sensitive', 'adj', 'easily affected', 'Sensitive information.'),
    ('sequence', 'noun', 'order', 'In sequence.'),
    ('session', 'noun', 'period of activity', 'Training session.'),
    ('setback', 'noun', 'problem', 'Minor setback.'),
    ('settlement', 'noun', 'agreement', 'Reach settlement.'),
    ('severe', 'adj', 'serious', 'Severe consequences.'),
    ('shareholder', 'noun', 'stock owner', 'Shareholder meeting.'),
    ('shipment', 'noun', 'goods sent', 'Shipment arrived.'),
    ('shortage', 'noun', 'lack', 'Labor shortage.'),
    ('shortcoming', 'noun', 'fault', 'Address shortcomings.'),
    ('shortly', 'adv', 'soon', 'Available shortly.'),
    ('shrink', 'verb', 'become smaller', 'Markets shrink.'),
    ('shutdown', 'noun', 'closing', 'Factory shutdown.'),
    ('signature', 'noun', 'signed name', 'Your signature.'),
    ('significance', 'noun', 'importance', 'Great significance.'),
    ('simplify', 'verb', 'make easier', 'Simplify process.'),
    ('simulate', 'verb', 'to imitate', 'Simulate conditions.'),
    ('simultaneous', 'adj', 'at same time', 'Simultaneous launch.'),
    ('skeptical', 'adj', 'doubtful', 'Skeptical about plan.'),
    ('skilled', 'adj', 'having skill', 'Skilled workers.'),
    ('slack', 'noun', 'loose part', 'Pick up slack.'),
    ('slight', 'adj', 'small', 'Slight increase.'),
    ('slot', 'noun', 'position', 'Time slot.'),
    ('slump', 'noun', 'decline', 'Sales slump.'),
    ('soar', 'verb', 'rise rapidly', 'Profits soar.'),
    ('sole', 'adj', 'only', 'Sole supplier.'),
    ('solely', 'adv', 'only', 'Solely responsible.'),
    ('solid', 'adj', 'firm', 'Solid performance.'),
    ('solution', 'noun', 'answer', 'Find solution.'),
    ('solve', 'verb', 'to find answer', 'Solve problem.'),
    ('sophisticated', 'adj', 'complex', 'Sophisticated system.'),
    ('sort', 'verb', 'to arrange', 'Sort by date.'),
    ('source', 'noun', 'origin', 'Reliable source.'),
    ('spare', 'adj', 'extra', 'Spare parts.'),
    ('spark', 'verb', 'to cause', 'Spark interest.'),
    ('specialize', 'verb', 'focus on specific area', 'Specialize in IT.'),
    ('specific', 'adj', 'particular', 'Specific requirements.'),
    ('specification', 'noun', 'detailed description', 'Product specifications.'),
    ('specify', 'verb', 'state clearly', 'Specify details.'),
    ('spectrum', 'noun', 'range', 'Wide spectrum.'),
    ('speculate', 'verb', 'to guess', 'Speculate about future.'),
    ('spend', 'verb', 'to use money', 'Spend wisely.'),
    ('spike', 'noun', 'sudden increase', 'Price spike.'),
    ('spin', 'verb', 'to turn rapidly', 'Spin off company.'),
    ('split', 'verb', 'to divide', 'Split the costs.'),
    ('sponsor', 'verb', 'to support', 'Sponsor event.'),
    ('spot', 'noun', 'place', 'Parking spot.'),
    ('spread', 'verb', 'to extend', 'Spread risk.'),
    ('spur', 'verb', 'to encourage', 'Spur growth.'),
    ('squeeze', 'verb', 'to compress', 'Squeeze costs.'),
    ('stability', 'noun', 'steadiness', 'Financial stability.'),
    ('stable', 'adj', 'steady', 'Stable market.'),
    ('stack', 'verb', 'to pile up', 'Stack boxes.'),
    ('staff', 'noun', 'employees', 'Hire staff.'),
    ('stage', 'noun', 'phase', 'Early stage.'),
    ('stagnant', 'adj', 'not growing', 'Stagnant sales.'),
    ('stake', 'noun', 'interest or share', 'Stakeholder.'),
    ('stall', 'verb', 'to delay', 'Negotiations stalled.'),
    ('stance', 'noun', 'position', 'Company stance.'),
    ('standard', 'noun', 'level of quality', 'High standards.'),
    ('standpoint', 'noun', 'point of view', 'From our standpoint.'),
    ('staple', 'noun', 'main item', 'Office staple.'),
    ('startup', 'noun', 'new company', 'Tech startup.'),
    ('state', 'verb', 'to express', 'State your opinion.'),
    ('statement', 'noun', 'declaration', 'Financial statement.'),
    ('statistics', 'noun', 'numerical data', 'Sales statistics.'),
    ('status', 'noun', 'position', 'Current status.'),
    ('steady', 'adj', 'stable', 'Steady growth.'),
    ('steep', 'adj', 'sharp', 'Steep decline.'),
    ('stem', 'verb', 'to originate', 'Stem from.'),
    ('stimulate', 'verb', 'to encourage', 'Stimulate demand.'),
    ('stipulate', 'verb', 'to specify', 'Contract stipulates.'),
    ('stock', 'noun', 'inventory or shares', 'Stock market.'),
    ('storage', 'noun', 'keeping place', 'Data storage.'),
    ('store', 'verb', 'to keep', 'Store safely.'),
    ('straightforward', 'adj', 'simple', 'Straightforward process.'),
    ('strain', 'noun', 'stress', 'Financial strain.'),
    ('strategic', 'adj', 'planned', 'Strategic planning.'),
    ('strategy', 'noun', 'plan', 'Business strategy.'),
    ('stream', 'noun', 'flow', 'Revenue stream.'),
    ('streamline', 'verb', 'make efficient', 'Streamline operations.'),
    ('strength', 'noun', 'strong point', 'Core strength.'),
    ('strengthen', 'verb', 'to make stronger', 'Strengthen ties.'),
    ('stress', 'noun', 'pressure', 'Work stress.'),
    ('strict', 'adj', 'rigid', 'Strict rules.'),
    ('strike', 'noun', 'work stoppage', 'Workers strike.'),
    ('strive', 'verb', 'to try hard', 'Strive for excellence.'),
    ('structure', 'noun', 'organization', 'Company structure.'),
    ('struggle', 'verb', 'to have difficulty', 'Struggle to compete.'),
    ('subject', 'noun', 'topic', 'Subject matter.'),
    ('submit', 'verb', 'to present', 'Submit application.'),
    ('subordinate', 'noun', 'person of lower rank', 'Direct subordinate.'),
    ('subscribe', 'verb', 'to sign up', 'Subscribe to service.'),
    ('subscription', 'noun', 'regular payment', 'Monthly subscription.'),
    ('subsequent', 'adj', 'following', 'Subsequent events.'),
    ('subsidiary', 'noun', 'owned company', 'Subsidiary company.'),
    ('subsidize', 'verb', 'to support financially', 'Government subsidizes.'),
    ('subsidy', 'noun', 'financial support', 'Government subsidy.'),
    ('substantial', 'adj', 'considerable', 'Substantial increase.'),
    ('substitute', 'noun', 'replacement', 'Find substitute.'),
    ('subtle', 'adj', 'not obvious', 'Subtle difference.'),
    ('succeed', 'verb', 'to achieve', 'Succeed in business.'),
    ('successive', 'adj', 'consecutive', 'Successive quarters.'),
    ('sufficient', 'adj', 'enough', 'Sufficient funds.'),
    ('suggest', 'verb', 'to propose', 'Suggest alternatives.'),
    ('suggestion', 'noun', 'proposal', 'Accept suggestion.'),
    ('suit', 'verb', 'to be appropriate', 'Suit your needs.'),
    ('suitable', 'adj', 'appropriate', 'Suitable candidate.'),
    ('sum', 'noun', 'total', 'Lump sum.'),
    ('summarize', 'verb', 'to give brief account', 'Summarize report.'),
    ('summit', 'noun', 'top level meeting', 'Business summit.'),
    ('superb', 'adj', 'excellent', 'Superb quality.'),
    ('superior', 'adj', 'higher quality', 'Superior product.'),
    ('supervise', 'verb', 'to oversee', 'Supervise team.'),
    ('supervision', 'noun', 'oversight', 'Under supervision.'),
    ('supervisor', 'noun', 'manager', 'Direct supervisor.'),
    ('supplement', 'verb', 'to add to', 'Supplement income.'),
    ('supplier', 'noun', 'provider', 'Main supplier.'),
    ('supply', 'noun', 'stock', 'Supply and demand.'),
    ('support', 'verb', 'to help', 'Support customers.'),
    ('suppose', 'verb', 'to assume', 'Suppose that.'),
    ('suppress', 'verb', 'to hold back', 'Suppress information.'),
    ('surcharge', 'noun', 'extra charge', 'Fuel surcharge.'),
    ('surge', 'noun', 'sudden increase', 'Demand surge.'),
    ('surplus', 'noun', 'excess', 'Budget surplus.'),
    ('surprise', 'noun', 'unexpected event', 'No surprise.'),
    ('surrender', 'verb', 'to give up', 'Surrender rights.'),
    ('surround', 'verb', 'to encircle', 'Surrounded by.'),
    ('survey', 'noun', 'questionnaire', 'Customer survey.'),
    ('survive', 'verb', 'to continue to exist', 'Survive competition.'),
    ('suspect', 'verb', 'to think', 'Suspect fraud.'),
    ('suspend', 'verb', 'to stop temporarily', 'Suspend operations.'),
    ('sustain', 'verb', 'to maintain', 'Sustain growth.'),
    ('sustainable', 'adj', 'maintainable', 'Sustainable development.'),
    ('swift', 'adj', 'quick', 'Swift action.'),
    ('switch', 'verb', 'to change', 'Switch providers.'),
    ('symbol', 'noun', 'representation', 'Company symbol.'),
    ('symptom', 'noun', 'sign', 'Economic symptom.'),
    ('syndicate', 'noun', 'group', 'Banking syndicate.'),
    ('synthesis', 'noun', 'combination', 'Synthesis of ideas.'),
    ('systematic', 'adj', 'organized', 'Systematic approach.'),
    ('tackle', 'verb', 'to deal with', 'Tackle problem.'),
    ('tactic', 'noun', 'strategy', 'Sales tactics.'),
    ('tailor', 'verb', 'to customize', 'Tailor services.'),
    ('tangible', 'adj', 'real', 'Tangible results.'),
    ('tap', 'verb', 'to access', 'Tap into market.'),
    ('tariff', 'noun', 'tax on imports', 'Import tariff.'),
    ('task', 'noun', 'job', 'Complete task.'),
    ('team', 'noun', 'group', 'Work team.'),
    ('technical', 'adj', 'relating to technology', 'Technical support.'),
    ('technique', 'noun', 'method', 'Sales technique.'),
    ('technology', 'noun', 'applied science', 'New technology.'),
    ('tedious', 'adj', 'boring', 'Tedious work.'),
    ('temporary', 'adj', 'not permanent', 'Temporary position.'),
    ('tenant', 'noun', 'renter', 'Building tenant.'),
    ('tendency', 'noun', 'trend', 'Downward tendency.'),
    ('tender', 'noun', 'bid', 'Submit tender.'),
    ('tentative', 'adj', 'not definite', 'Tentative agreement.'),
    ('tenure', 'noun', 'period of holding', 'Job tenure.'),
    ('term', 'noun', 'condition', 'Contract terms.'),
    ('terminal', 'noun', 'endpoint', 'Airport terminal.'),
    ('terminate', 'verb', 'to end', 'Terminate contract.'),
    ('terms', 'noun', 'conditions', 'Payment terms.'),
    ('territory', 'noun', 'area', 'Sales territory.'),
    ('test', 'verb', 'to examine', 'Test product.'),
    ('testimony', 'noun', 'evidence', 'Expert testimony.'),
    ('thorough', 'adj', 'complete', 'Thorough review.'),
    ('threat', 'noun', 'danger', 'Competitive threat.'),
    ('threaten', 'verb', 'to pose danger', 'Threaten market share.'),
    ('threshold', 'noun', 'limit', 'Price threshold.'),
    ('thrive', 'verb', 'to prosper', 'Business thrives.'),
    ('tight', 'adj', 'strict', 'Tight budget.'),
    ('timetable', 'noun', 'schedule', 'Project timetable.'),
    ('tip', 'noun', 'advice', 'Helpful tips.'),
    ('toll', 'noun', 'charge', 'Toll fee.'),
    ('top', 'adj', 'highest', 'Top priority.'),
    ('total', 'noun', 'sum', 'Grand total.'),
    ('tour', 'noun', 'visit', 'Factory tour.'),
    ('trace', 'verb', 'to find', 'Trace shipment.'),
    ('track', 'verb', 'to follow', 'Track progress.'),
    ('trade', 'noun', 'commerce', 'International trade.'),
    ('trademark', 'noun', 'brand symbol', 'Registered trademark.'),
    ('tradition', 'noun', 'custom', 'Company tradition.'),
    ('traffic', 'noun', 'movement', 'Web traffic.'),
    ('train', 'verb', 'to teach', 'Train employees.'),
    ('training', 'noun', 'instruction', 'Job training.'),
    ('transaction', 'noun', 'deal', 'Financial transaction.'),
    ('transfer', 'verb', 'to move', 'Transfer funds.'),
    ('transform', 'verb', 'to change', 'Transform business.'),
    ('transition', 'noun', 'change', 'Smooth transition.'),
    ('translate', 'verb', 'to convert', 'Translate document.'),
    ('transmit', 'verb', 'to send', 'Transmit data.'),
    ('transparent', 'adj', 'clear', 'Transparent pricing.'),
    ('transport', 'verb', 'to carry', 'Transport goods.'),
    ('transportation', 'noun', 'carrying', 'Public transportation.'),
    ('trap', 'noun', 'snare', 'Debt trap.'),
    ('travel', 'verb', 'to go', 'Travel for business.'),
    ('treasure', 'noun', 'valuable thing', 'Company treasure.'),
    ('treat', 'verb', 'to deal with', 'Treat customers well.'),
    ('treatment', 'noun', 'handling', 'Fair treatment.'),
    ('treaty', 'noun', 'agreement', 'Trade treaty.'),
    ('tremendous', 'adj', 'very large', 'Tremendous growth.'),
    ('trend', 'noun', 'tendency', 'Market trend.'),
    ('trial', 'noun', 'test', 'Free trial.'),
    ('trigger', 'verb', 'to cause', 'Trigger response.'),
    ('trim', 'verb', 'to reduce', 'Trim costs.'),
    ('triple', 'verb', 'to multiply by three', 'Triple sales.'),
    ('triumph', 'noun', 'victory', 'Business triumph.'),
    ('trouble', 'noun', 'problem', 'Financial trouble.'),
    ('trust', 'noun', 'confidence', 'Customer trust.'),
    ('trustworthy', 'adj', 'reliable', 'Trustworthy partner.'),
    ('tuition', 'noun', 'instruction fee', 'Tuition reimbursement.'),
    ('turnaround', 'noun', 'reversal', 'Business turnaround.'),
    ('turnover', 'noun', 'rate of change', 'Employee turnover.'),
    ('twist', 'noun', 'unexpected change', 'Plot twist.'),
    ('type', 'noun', 'kind', 'Type of business.'),
    ('typical', 'adj', 'normal', 'Typical day.'),
    ('ultimately', 'adv', 'in the end', 'Ultimately succeed.'),
    ('unable', 'adj', 'not able', 'Unable to attend.'),
    ('unanimous', 'adj', 'all agreeing', 'Unanimous decision.'),
    ('uncertain', 'adj', 'not sure', 'Uncertain future.'),
    ('undergo', 'verb', 'to experience', 'Undergo changes.'),
    ('underlying', 'adj', 'fundamental', 'Underlying cause.'),
    ('undermine', 'verb', 'to weaken', 'Undermine efforts.'),
    ('undertake', 'verb', 'to take on', 'Undertake project.'),
    ('undo', 'verb', 'to reverse', 'Undo damage.'),
    ('unforeseen', 'adj', 'unexpected', 'Unforeseen circumstances.'),
    ('uniform', 'adj', 'consistent', 'Uniform standards.'),
    ('unique', 'adj', 'one of a kind', 'Unique product.'),
    ('unit', 'noun', 'single item', 'Business unit.'),
    ('unity', 'noun', 'oneness', 'Team unity.'),
    ('universal', 'adj', 'for all', 'Universal appeal.'),
    ('unknown', 'adj', 'not known', 'Unknown factor.'),
    ('unless', 'conj', 'except if', 'Unless approved.'),
    ('unlike', 'adj', 'different', 'Unlike competitors.'),
    ('unlikely', 'adj', 'not probable', 'Unlikely event.'),
    ('unlimited', 'adj', 'without limits', 'Unlimited access.'),
    ('unload', 'verb', 'to remove', 'Unload cargo.'),
    ('unnecessary', 'adj', 'not needed', 'Unnecessary expense.'),
    ('unprecedented', 'adj', 'never before', 'Unprecedented growth.'),
    ('unrealistic', 'adj', 'not practical', 'Unrealistic goals.'),
    ('unrest', 'noun', 'disturbance', 'Labor unrest.'),
    ('unstable', 'adj', 'not steady', 'Unstable market.'),
    ('upcoming', 'adj', 'soon to happen', 'Upcoming event.'),
    ('update', 'verb', 'to bring current', 'Update records.'),
    ('upgrade', 'verb', 'to improve', 'Upgrade system.'),
    ('uphold', 'verb', 'to maintain', 'Uphold standards.'),
    ('upon', 'prep', 'on', 'Upon receipt.'),
    ('upper', 'adj', 'higher', 'Upper management.'),
    ('upward', 'adj', 'going up', 'Upward trend.'),
    ('urban', 'adj', 'city related', 'Urban market.'),
    ('urge', 'verb', 'to strongly recommend', 'Urge action.'),
    ('urgent', 'adj', 'requiring immediate action', 'Urgent matter.'),
    ('usage', 'noun', 'use', 'Usage rate.'),
    ('useful', 'adj', 'helpful', 'Useful information.'),
    ('user', 'noun', 'one who uses', 'End user.'),
    ('usual', 'adj', 'normal', 'Usual practice.'),
    ('utility', 'noun', 'usefulness', 'Utility costs.'),
    ('utilize', 'verb', 'to use', 'Utilize resources.'),
    ('utmost', 'adj', 'greatest', 'Utmost importance.'),
    ('vacant', 'adj', 'empty', 'Vacant position.'),
    ('valid', 'adj', 'acceptable', 'Valid argument.'),
    ('validate', 'verb', 'to confirm', 'Validate data.'),
    ('validity', 'noun', 'soundness', 'Check validity.'),
    ('valuable', 'adj', 'worth much', 'Valuable asset.'),
    ('value', 'noun', 'worth', 'Added value.'),
    ('variable', 'adj', 'changing', 'Variable costs.'),
    ('variation', 'noun', 'difference', 'Price variation.'),
    ('variety', 'noun', 'range', 'Wide variety.'),
    ('various', 'adj', 'different', 'Various options.'),
    ('vary', 'verb', 'to differ', 'Prices vary.'),
    ('vast', 'adj', 'very large', 'Vast market.'),
    ('vehicle', 'noun', 'means of transport', 'Company vehicle.'),
    ('vendor', 'noun', 'seller', 'Preferred vendor.'),
    ('venture', 'noun', 'risky business', 'Joint venture.'),
    ('venue', 'noun', 'place', 'Meeting venue.'),
    ('verbal', 'adj', 'spoken', 'Verbal agreement.'),
    ('verify', 'verb', 'to confirm', 'Verify information.'),
    ('versatile', 'adj', 'adaptable', 'Versatile employee.'),
    ('version', 'noun', 'form', 'Latest version.'),
    ('vertical', 'adj', 'upright', 'Vertical integration.'),
    ('via', 'prep', 'by way of', 'Via email.'),
    ('viable', 'adj', 'workable', 'Viable option.'),
    ('vice', 'noun', 'deputy', 'Vice president.'),
    ('view', 'noun', 'opinion', 'Point of view.'),
    ('vigorous', 'adj', 'strong', 'Vigorous growth.'),
    ('violate', 'verb', 'to break', 'Violate policy.'),
    ('violation', 'noun', 'breach', 'Policy violation.'),
    ('virtual', 'adj', 'online', 'Virtual meeting.'),
    ('virtue', 'noun', 'good quality', 'By virtue of.'),
    ('visible', 'adj', 'able to be seen', 'Visible improvement.'),
    ('vision', 'noun', 'idea of future', 'Company vision.'),
    ('visit', 'verb', 'to go to', 'Visit client.'),
    ('vital', 'adj', 'essential', 'Vital information.'),
    ('voice', 'verb', 'to express', 'Voice concerns.'),
    ('volatile', 'adj', 'unstable', 'Volatile market.'),
    ('volume', 'noun', 'quantity', 'Sales volume.'),
    ('voluntary', 'adj', 'by choice', 'Voluntary participation.'),
    ('volunteer', 'verb', 'to offer freely', 'Volunteer to help.'),
    ('vote', 'verb', 'to choose', 'Vote on decision.'),
    ('vouch', 'verb', 'to guarantee', 'Vouch for quality.'),
    ('voucher', 'noun', 'coupon', 'Gift voucher.'),
    ('vulnerable', 'adj', 'exposed to harm', 'Vulnerable position.'),
    ('wage', 'noun', 'pay', 'Minimum wage.'),
    ('waive', 'verb', 'to give up right', 'Waive fee.'),
    ('warehouse', 'noun', 'storage building', 'Distribution warehouse.'),
    ('warrant', 'verb', 'to justify', 'Warrant investigation.'),
    ('warranty', 'noun', 'guarantee', 'Product warranty.'),
    ('waste', 'noun', 'unused material', 'Reduce waste.'),
    ('wealth', 'noun', 'riches', 'Wealth management.'),
    ('weigh', 'verb', 'to consider', 'Weigh options.'),
    ('weight', 'noun', 'importance', 'Carry weight.'),
    ('welfare', 'noun', 'wellbeing', 'Employee welfare.'),
    ('whereas', 'conj', 'while on the contrary', 'Whereas before.'),
    ('whereby', 'adv', 'by which', 'System whereby.'),
    ('whilst', 'conj', 'while', 'Whilst working.'),
    ('wholesale', 'adj', 'in bulk', 'Wholesale price.'),
    ('wide', 'adj', 'broad', 'Wide range.'),
    ('widespread', 'adj', 'common', 'Widespread use.'),
    ('willing', 'adj', 'ready', 'Willing to help.'),
    ('win', 'verb', 'to succeed', 'Win contract.'),
    ('withdraw', 'verb', 'to take back', 'Withdraw offer.'),
    ('withdrawal', 'noun', 'removal', 'Cash withdrawal.'),
    ('withhold', 'verb', 'to keep back', 'Withhold payment.'),
    ('withstand', 'verb', 'to resist', 'Withstand pressure.'),
    ('witness', 'verb', 'to see', 'Witness growth.'),
    ('workforce', 'noun', 'employees', 'Skilled workforce.'),
    ('workload', 'noun', 'amount of work', 'Heavy workload.'),
    ('workplace', 'noun', 'place of work', 'Safe workplace.'),
    ('workshop', 'noun', 'training session', 'Skills workshop.'),
    ('worldwide', 'adj', 'global', 'Worldwide presence.'),
    ('worry', 'verb', 'to be concerned', 'Worry about costs.'),
    ('worsen', 'verb', 'to get worse', 'Situation worsened.'),
    ('worth', 'noun', 'value', 'Net worth.'),
    ('worthwhile', 'adj', 'valuable', 'Worthwhile investment.'),
    ('worthy', 'adj', 'deserving', 'Worthy cause.'),
    ('wrap', 'verb', 'to finish', 'Wrap up meeting.'),
    ('write', 'verb', 'to compose', 'Write report.'),
    ('yield', 'verb', 'to produce', 'Yield results.'),
    ('zero', 'noun', 'nothing', 'Zero defects.'),
    ('zone', 'noun', 'area', 'Time zone.'),
]

# Load existing
with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    existing = data.get('words', data)

print(f'기존 단어: {len(existing)}개')
word_set = {w['word'].lower() for w in existing}
new_words = [(w,p,m,e) for w,p,m,e in WORDS if w.lower() not in word_set]
print(f'추가할 새 단어: {len(new_words)}개')

if not new_words:
    print('추가할 단어 없음')
    exit()

langs = ['ko','ja','zh','es','pt','de','fr','vi','ar','id']
trans_by_lang = {}
print('번역 중...')
for lang in langs:
    print(f'  {lang}...', end=' ', flush=True)
    trans_by_lang[lang] = translate_batch([w[2] for w in new_words], lang)
    print('완료')
    time.sleep(0.2)

count = len(existing)
total = count + len(new_words)
for i, (word, pos, meaning, example) in enumerate(new_words):
    word_id = count + i + 1
    if word_id <= total // 4:
        level = '0-400'
    elif word_id <= total // 2:
        level = '400-600'
    elif word_id <= total * 3 // 4:
        level = '600-800'
    else:
        level = '800-990'
    trans = {lang: trans_by_lang[lang][i] if i < len(trans_by_lang[lang]) else meaning for lang in langs}
    existing.append({'id': word_id, 'word': word, 'meaning': meaning, 'example': example, 'pos': pos, 'level': level, 'translations': trans})

with open('assets/data/words.json', 'w', encoding='utf-8') as f:
    json.dump({'words': existing}, f, ensure_ascii=False, indent=2)

level_counts = {}
for w in existing:
    lv = w.get('level', '0-400')
    level_counts[lv] = level_counts.get(lv, 0) + 1

print(f'\n총 단어 수: {len(existing)}개')
for lv in ['0-400', '400-600', '600-800', '800-990']:
    print(f'  {lv}: {level_counts.get(lv, 0)}개')
