import json
import requests
import time

API_KEY = 'AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk'

def translate_batch(texts, target_lang):
    if not texts:
        return []
    url = f'https://translation.googleapis.com/language/translate/v2?key={API_KEY}'
    results = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        payload = {'q': batch, 'target': target_lang, 'source': 'en'}
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                translations = [t['translatedText'] for t in data['data']['translations']]
                results.extend(translations)
            else:
                results.extend(batch)
        except:
            results.extend(batch)
    return results

# More TOEIC words - Business, Finance, Marketing, HR
WORDS = [
    ('craft', 'verb', 'to make skillfully', 'Craft a proposal.'),
    ('crash', 'noun', 'sudden failure', 'Market crash.'),
    ('create', 'verb', 'to make', 'Create opportunity.'),
    ('creation', 'noun', 'making', 'Job creation.'),
    ('creative', 'adj', 'imaginative', 'Creative solution.'),
    ('creativity', 'noun', 'imagination', 'Encourage creativity.'),
    ('credential', 'noun', 'qualification', 'Check credentials.'),
    ('credibility', 'noun', 'trustworthiness', 'Build credibility.'),
    ('credible', 'adj', 'believable', 'Credible source.'),
    ('credit', 'noun', 'loan or recognition', 'Line of credit.'),
    ('creditor', 'noun', 'lender', 'Pay creditors.'),
    ('crisis', 'noun', 'emergency', 'Financial crisis.'),
    ('criteria', 'noun', 'standards', 'Selection criteria.'),
    ('criterion', 'noun', 'standard', 'Main criterion.'),
    ('critical', 'adj', 'very important', 'Critical decision.'),
    ('criticism', 'noun', 'disapproval', 'Constructive criticism.'),
    ('criticize', 'verb', 'to find fault', 'Criticize performance.'),
    ('crop', 'noun', 'harvest', 'Crop production.'),
    ('crucial', 'adj', 'very important', 'Crucial moment.'),
    ('crude', 'adj', 'raw', 'Crude oil.'),
    ('cruise', 'noun', 'sea voyage', 'Business cruise.'),
    ('cultivate', 'verb', 'to develop', 'Cultivate relationships.'),
    ('culture', 'noun', 'customs', 'Corporate culture.'),
    ('cumulative', 'adj', 'increasing', 'Cumulative effect.'),
    ('curb', 'verb', 'to restrain', 'Curb spending.'),
    ('cure', 'noun', 'remedy', 'No quick cure.'),
    ('curiosity', 'noun', 'desire to know', 'Intellectual curiosity.'),
    ('curious', 'adj', 'eager to know', 'Curious about details.'),
    ('currency', 'noun', 'money', 'Foreign currency.'),
    ('current', 'adj', 'present', 'Current status.'),
    ('currently', 'adv', 'at present', 'Currently available.'),
    ('curriculum', 'noun', 'course of study', 'Training curriculum.'),
    ('curtail', 'verb', 'to reduce', 'Curtail expenses.'),
    ('custodian', 'noun', 'guardian', 'Asset custodian.'),
    ('custody', 'noun', 'care', 'In safe custody.'),
    ('custom', 'noun', 'tradition', 'Business custom.'),
    ('customary', 'adj', 'usual', 'Customary practice.'),
    ('customer', 'noun', 'buyer', 'Regular customer.'),
    ('customize', 'verb', 'to modify', 'Customize settings.'),
    ('cut', 'noun', 'reduction', 'Budget cut.'),
    ('cutback', 'noun', 'reduction', 'Staff cutbacks.'),
    ('cycle', 'noun', 'recurring period', 'Business cycle.'),
    ('daily', 'adj', 'every day', 'Daily report.'),
    ('damage', 'noun', 'harm', 'Property damage.'),
    ('damp', 'adj', 'slightly wet', 'Damp conditions.'),
    ('danger', 'noun', 'risk', 'Danger zone.'),
    ('dangerous', 'adj', 'risky', 'Dangerous situation.'),
    ('dare', 'verb', 'to have courage', 'Dare to innovate.'),
    ('dashboard', 'noun', 'control panel', 'Analytics dashboard.'),
    ('data', 'noun', 'information', 'Collect data.'),
    ('database', 'noun', 'data collection', 'Customer database.'),
    ('date', 'noun', 'specific day', 'Due date.'),
    ('dawn', 'noun', 'beginning', 'Dawn of new era.'),
    ('day', 'noun', 'period of time', 'Work day.'),
    ('deadline', 'noun', 'time limit', 'Meet deadline.'),
    ('deadlock', 'noun', 'standstill', 'Negotiations deadlock.'),
    ('deal', 'noun', 'agreement', 'Close deal.'),
    ('dealer', 'noun', 'trader', 'Authorized dealer.'),
    ('dealing', 'noun', 'transaction', 'Fair dealing.'),
    ('dean', 'noun', 'head', 'Dean of business school.'),
    ('dear', 'adj', 'expensive', 'Dear prices.'),
    ('death', 'noun', 'end', 'Death of project.'),
    ('debate', 'noun', 'discussion', 'Policy debate.'),
    ('debit', 'noun', 'charge', 'Debit card.'),
    ('debris', 'noun', 'remains', 'Clear debris.'),
    ('debt', 'noun', 'money owed', 'Pay off debt.'),
    ('debtor', 'noun', 'one who owes', 'Debtor nation.'),
    ('debut', 'noun', 'first appearance', 'Product debut.'),
    ('decade', 'noun', 'ten years', 'Next decade.'),
    ('decay', 'noun', 'decline', 'Urban decay.'),
    ('deceive', 'verb', 'to mislead', 'Deceive customers.'),
    ('decent', 'adj', 'acceptable', 'Decent salary.'),
    ('decide', 'verb', 'to choose', 'Decide quickly.'),
    ('decision', 'noun', 'choice', 'Make decision.'),
    ('decisive', 'adj', 'conclusive', 'Decisive action.'),
    ('deck', 'noun', 'presentation slides', 'Slide deck.'),
    ('declaration', 'noun', 'announcement', 'Tax declaration.'),
    ('declare', 'verb', 'to announce', 'Declare bankruptcy.'),
    ('decline', 'verb', 'to decrease', 'Sales decline.'),
    ('decorate', 'verb', 'to adorn', 'Decorate office.'),
    ('decrease', 'verb', 'to reduce', 'Decrease costs.'),
    ('dedicate', 'verb', 'to devote', 'Dedicate resources.'),
    ('dedication', 'noun', 'commitment', 'Show dedication.'),
    ('deduct', 'verb', 'to subtract', 'Deduct expenses.'),
    ('deduction', 'noun', 'subtraction', 'Tax deduction.'),
    ('deed', 'noun', 'action', 'Good deeds.'),
    ('deem', 'verb', 'to consider', 'Deem necessary.'),
    ('deep', 'adj', 'profound', 'Deep discount.'),
    ('deepen', 'verb', 'to intensify', 'Deepen understanding.'),
    ('default', 'noun', 'failure to pay', 'Loan default.'),
    ('defeat', 'verb', 'to beat', 'Defeat competition.'),
    ('defect', 'noun', 'flaw', 'Product defect.'),
    ('defective', 'adj', 'faulty', 'Defective item.'),
    ('defend', 'verb', 'to protect', 'Defend market share.'),
    ('defense', 'noun', 'protection', 'Legal defense.'),
    ('defensive', 'adj', 'protective', 'Defensive strategy.'),
    ('defer', 'verb', 'to postpone', 'Defer payment.'),
    ('deferral', 'noun', 'postponement', 'Tax deferral.'),
    ('deficiency', 'noun', 'shortage', 'Budget deficiency.'),
    ('deficient', 'adj', 'lacking', 'Deficient in skills.'),
    ('deficit', 'noun', 'shortage', 'Trade deficit.'),
    ('define', 'verb', 'to explain', 'Define goals.'),
    ('definite', 'adj', 'certain', 'Definite answer.'),
    ('definitely', 'adv', 'certainly', 'Definitely interested.'),
    ('definition', 'noun', 'meaning', 'Clear definition.'),
    ('deflate', 'verb', 'to reduce', 'Deflate prices.'),
    ('deflation', 'noun', 'price decrease', 'Economic deflation.'),
    ('defy', 'verb', 'to resist', 'Defy expectations.'),
    ('degrade', 'verb', 'to lower', 'Degrade quality.'),
    ('degree', 'noun', 'extent', 'High degree.'),
    ('delay', 'noun', 'postponement', 'Shipping delay.'),
    ('delegate', 'verb', 'to assign', 'Delegate tasks.'),
    ('delegation', 'noun', 'group of representatives', 'Trade delegation.'),
    ('delete', 'verb', 'to remove', 'Delete files.'),
    ('deliberate', 'adj', 'intentional', 'Deliberate action.'),
    ('deliberately', 'adv', 'on purpose', 'Deliberately ignored.'),
    ('delicate', 'adj', 'sensitive', 'Delicate matter.'),
    ('delight', 'noun', 'pleasure', 'Customer delight.'),
    ('delighted', 'adj', 'very pleased', 'Delighted to help.'),
    ('deliver', 'verb', 'to bring', 'Deliver results.'),
    ('delivery', 'noun', 'bringing', 'Fast delivery.'),
    ('demand', 'noun', 'request', 'High demand.'),
    ('demanding', 'adj', 'requiring much', 'Demanding job.'),
    ('democracy', 'noun', 'government by people', 'Corporate democracy.'),
    ('democratic', 'adj', 'relating to democracy', 'Democratic process.'),
    ('demographic', 'adj', 'relating to population', 'Demographic data.'),
    ('demolish', 'verb', 'to destroy', 'Demolish building.'),
    ('demonstrate', 'verb', 'to show', 'Demonstrate product.'),
    ('demonstration', 'noun', 'showing', 'Product demonstration.'),
    ('denial', 'noun', 'refusal', 'Denial of claim.'),
    ('denote', 'verb', 'to indicate', 'Denote change.'),
    ('denounce', 'verb', 'to criticize publicly', 'Denounce practices.'),
    ('dense', 'adj', 'thick', 'Dense traffic.'),
    ('density', 'noun', 'thickness', 'Population density.'),
    ('deny', 'verb', 'to refuse', 'Deny request.'),
    ('depart', 'verb', 'to leave', 'Depart from schedule.'),
    ('department', 'noun', 'division', 'Sales department.'),
    ('departure', 'noun', 'leaving', 'New departure.'),
    ('depend', 'verb', 'to rely', 'Depend on support.'),
    ('dependable', 'adj', 'reliable', 'Dependable service.'),
    ('dependence', 'noun', 'reliance', 'Reduce dependence.'),
    ('dependent', 'adj', 'relying on', 'Dependent on sales.'),
    ('depict', 'verb', 'to show', 'Depict growth.'),
    ('deplete', 'verb', 'to use up', 'Deplete resources.'),
    ('depletion', 'noun', 'using up', 'Resource depletion.'),
    ('deploy', 'verb', 'to use', 'Deploy resources.'),
    ('deployment', 'noun', 'use', 'System deployment.'),
    ('deposit', 'noun', 'payment', 'Security deposit.'),
    ('depot', 'noun', 'storage place', 'Warehouse depot.'),
    ('depreciate', 'verb', 'to decrease in value', 'Assets depreciate.'),
    ('depreciation', 'noun', 'decrease in value', 'Asset depreciation.'),
    ('depress', 'verb', 'to lower', 'Depress prices.'),
    ('depression', 'noun', 'economic decline', 'Great depression.'),
    ('deprive', 'verb', 'to take away', 'Deprive of rights.'),
    ('depth', 'noun', 'deepness', 'Depth of knowledge.'),
    ('deputy', 'noun', 'assistant', 'Deputy director.'),
    ('derive', 'verb', 'to obtain', 'Derive benefit.'),
    ('descend', 'verb', 'to go down', 'Prices descend.'),
    ('descent', 'noun', 'going down', 'Economic descent.'),
    ('describe', 'verb', 'to explain', 'Describe process.'),
    ('description', 'noun', 'explanation', 'Job description.'),
    ('desert', 'verb', 'to abandon', 'Desert post.'),
    ('deserve', 'verb', 'to be worthy', 'Deserve promotion.'),
    ('design', 'noun', 'plan', 'Product design.'),
    ('designate', 'verb', 'to appoint', 'Designate leader.'),
    ('designation', 'noun', 'title', 'Job designation.'),
    ('designer', 'noun', 'creator', 'Graphic designer.'),
    ('desirable', 'adj', 'wanted', 'Desirable outcome.'),
    ('desire', 'noun', 'wish', 'Strong desire.'),
    ('desk', 'noun', 'work table', 'Help desk.'),
    ('desktop', 'noun', 'computer screen', 'Desktop computer.'),
    ('desperate', 'adj', 'very serious', 'Desperate situation.'),
    ('despite', 'prep', 'in spite of', 'Despite challenges.'),
    ('destination', 'noun', 'end point', 'Travel destination.'),
    ('destined', 'adj', 'certain', 'Destined for success.'),
    ('destroy', 'verb', 'to ruin', 'Destroy reputation.'),
    ('destruction', 'noun', 'ruin', 'Data destruction.'),
    ('destructive', 'adj', 'causing damage', 'Destructive behavior.'),
    ('detach', 'verb', 'to separate', 'Detach coupon.'),
    ('detail', 'noun', 'specific information', 'Attention to detail.'),
    ('detailed', 'adj', 'thorough', 'Detailed report.'),
    ('detain', 'verb', 'to hold', 'Detain for questioning.'),
    ('detect', 'verb', 'to discover', 'Detect fraud.'),
    ('detection', 'noun', 'discovery', 'Early detection.'),
    ('detention', 'noun', 'holding', 'Cargo detention.'),
    ('deter', 'verb', 'to discourage', 'Deter competition.'),
    ('deteriorate', 'verb', 'to worsen', 'Conditions deteriorate.'),
    ('deterioration', 'noun', 'worsening', 'Market deterioration.'),
    ('determination', 'noun', 'resolve', 'Show determination.'),
    ('determine', 'verb', 'to decide', 'Determine outcome.'),
    ('deterrent', 'noun', 'discouragement', 'Price deterrent.'),
    ('detract', 'verb', 'to take away', 'Detract from value.'),
    ('detrimental', 'adj', 'harmful', 'Detrimental effect.'),
    ('devastate', 'verb', 'to destroy', 'Devastate industry.'),
    ('devastating', 'adj', 'destructive', 'Devastating loss.'),
    ('develop', 'verb', 'to grow', 'Develop skills.'),
    ('developer', 'noun', 'creator', 'Software developer.'),
    ('development', 'noun', 'growth', 'Business development.'),
    ('deviate', 'verb', 'to depart', 'Deviate from plan.'),
    ('deviation', 'noun', 'departure', 'Standard deviation.'),
    ('device', 'noun', 'tool', 'Mobile device.'),
    ('devise', 'verb', 'to create', 'Devise strategy.'),
    ('devote', 'verb', 'to dedicate', 'Devote time.'),
    ('devoted', 'adj', 'dedicated', 'Devoted employee.'),
    ('devotion', 'noun', 'dedication', 'Show devotion.'),
    ('diagnose', 'verb', 'to identify', 'Diagnose problem.'),
    ('diagnosis', 'noun', 'identification', 'Market diagnosis.'),
    ('diagram', 'noun', 'drawing', 'Flow diagram.'),
    ('dial', 'verb', 'to call', 'Dial number.'),
    ('dialogue', 'noun', 'conversation', 'Open dialogue.'),
    ('differ', 'verb', 'to be different', 'Views differ.'),
    ('difference', 'noun', 'distinction', 'Make a difference.'),
    ('different', 'adj', 'not the same', 'Different approach.'),
    ('differentiate', 'verb', 'to distinguish', 'Differentiate products.'),
    ('differentiation', 'noun', 'distinction', 'Product differentiation.'),
    ('difficult', 'adj', 'hard', 'Difficult decision.'),
    ('difficulty', 'noun', 'problem', 'Financial difficulty.'),
    ('digest', 'verb', 'to absorb', 'Digest information.'),
    ('digital', 'adj', 'electronic', 'Digital marketing.'),
    ('dignity', 'noun', 'self-respect', 'Work with dignity.'),
    ('dilemma', 'noun', 'difficult choice', 'Ethical dilemma.'),
    ('diligence', 'noun', 'careful work', 'Due diligence.'),
    ('diligent', 'adj', 'hardworking', 'Diligent employee.'),
    ('dilute', 'verb', 'to weaken', 'Dilute shares.'),
    ('dilution', 'noun', 'weakening', 'Share dilution.'),
    ('dimension', 'noun', 'aspect', 'New dimension.'),
    ('diminish', 'verb', 'to reduce', 'Diminish returns.'),
    ('dine', 'verb', 'to eat', 'Dine with clients.'),
    ('dinner', 'noun', 'evening meal', 'Business dinner.'),
    ('diploma', 'noun', 'certificate', 'College diploma.'),
    ('diplomatic', 'adj', 'tactful', 'Diplomatic approach.'),
    ('direct', 'adj', 'straight', 'Direct contact.'),
    ('direction', 'noun', 'course', 'New direction.'),
    ('directive', 'noun', 'instruction', 'Issue directive.'),
    ('directly', 'adv', 'straight', 'Report directly.'),
    ('director', 'noun', 'manager', 'Board director.'),
    ('directory', 'noun', 'list', 'Business directory.'),
    ('disability', 'noun', 'impairment', 'Disability insurance.'),
    ('disable', 'verb', 'to make inoperative', 'Disable function.'),
    ('disadvantage', 'noun', 'drawback', 'Competitive disadvantage.'),
    ('disagree', 'verb', 'to differ', 'Respectfully disagree.'),
    ('disagreement', 'noun', 'dispute', 'Resolve disagreement.'),
    ('disappear', 'verb', 'to vanish', 'Jobs disappear.'),
    ('disappoint', 'verb', 'to let down', 'Disappoint investors.'),
    ('disappointment', 'noun', 'letdown', 'Major disappointment.'),
    ('disapproval', 'noun', 'rejection', 'Express disapproval.'),
    ('disapprove', 'verb', 'to reject', 'Disapprove request.'),
    ('disaster', 'noun', 'catastrophe', 'Natural disaster.'),
    ('disastrous', 'adj', 'catastrophic', 'Disastrous results.'),
    ('discard', 'verb', 'to throw away', 'Discard old files.'),
    ('discharge', 'verb', 'to release', 'Discharge duties.'),
    ('discipline', 'noun', 'control', 'Financial discipline.'),
    ('disciplined', 'adj', 'controlled', 'Disciplined approach.'),
    ('disclose', 'verb', 'to reveal', 'Disclose information.'),
    ('disclosure', 'noun', 'revealing', 'Full disclosure.'),
    ('discount', 'noun', 'price reduction', 'Volume discount.'),
    ('discourage', 'verb', 'to dishearten', 'Discourage waste.'),
    ('discover', 'verb', 'to find', 'Discover opportunity.'),
    ('discovery', 'noun', 'finding', 'New discovery.'),
    ('discreet', 'adj', 'careful', 'Discreet inquiry.'),
    ('discrepancy', 'noun', 'difference', 'Account discrepancy.'),
    ('discretion', 'noun', 'judgment', 'Use discretion.'),
    ('discretionary', 'adj', 'optional', 'Discretionary spending.'),
    ('discriminate', 'verb', 'to distinguish', 'Discriminate against.'),
    ('discrimination', 'noun', 'unfair treatment', 'No discrimination.'),
    ('discuss', 'verb', 'to talk about', 'Discuss options.'),
    ('discussion', 'noun', 'conversation', 'Open discussion.'),
    ('disease', 'noun', 'illness', 'Prevent disease.'),
    ('disguise', 'verb', 'to hide', 'Disguise intent.'),
    ('dismiss', 'verb', 'to reject', 'Dismiss claim.'),
    ('dismissal', 'noun', 'firing', 'Wrongful dismissal.'),
    ('disorder', 'noun', 'confusion', 'Market disorder.'),
    ('dispatch', 'verb', 'to send', 'Dispatch order.'),
    ('dispel', 'verb', 'to drive away', 'Dispel rumors.'),
    ('dispense', 'verb', 'to distribute', 'Dispense advice.'),
    ('disperse', 'verb', 'to scatter', 'Disperse funds.'),
    ('displace', 'verb', 'to replace', 'Displace workers.'),
    ('displacement', 'noun', 'replacement', 'Job displacement.'),
    ('display', 'verb', 'to show', 'Display products.'),
    ('disposal', 'noun', 'getting rid of', 'Waste disposal.'),
    ('dispose', 'verb', 'to get rid of', 'Dispose of assets.'),
    ('disposition', 'noun', 'temperament', 'Good disposition.'),
    ('dispute', 'noun', 'disagreement', 'Labor dispute.'),
    ('disqualify', 'verb', 'to make ineligible', 'Disqualify bidder.'),
    ('disregard', 'verb', 'to ignore', 'Disregard warning.'),
    ('disrupt', 'verb', 'to interrupt', 'Disrupt market.'),
    ('disruption', 'noun', 'interruption', 'Supply disruption.'),
    ('disruptive', 'adj', 'causing disruption', 'Disruptive technology.'),
    ('dissatisfaction', 'noun', 'unhappiness', 'Customer dissatisfaction.'),
    ('dissatisfied', 'adj', 'unhappy', 'Dissatisfied customer.'),
    ('disseminate', 'verb', 'to spread', 'Disseminate information.'),
    ('dissent', 'noun', 'disagreement', 'Voice dissent.'),
    ('dissolve', 'verb', 'to end', 'Dissolve partnership.'),
    ('distance', 'noun', 'space between', 'Travel distance.'),
    ('distant', 'adj', 'far', 'Distant future.'),
    ('distinct', 'adj', 'different', 'Distinct advantage.'),
    ('distinction', 'noun', 'difference', 'Clear distinction.'),
    ('distinctive', 'adj', 'unique', 'Distinctive brand.'),
    ('distinguish', 'verb', 'to differentiate', 'Distinguish quality.'),
    ('distinguished', 'adj', 'eminent', 'Distinguished career.'),
    ('distort', 'verb', 'to misrepresent', 'Distort facts.'),
    ('distortion', 'noun', 'misrepresentation', 'Market distortion.'),
    ('distract', 'verb', 'to divert', 'Distract attention.'),
    ('distraction', 'noun', 'diversion', 'Avoid distractions.'),
    ('distress', 'noun', 'trouble', 'Financial distress.'),
    ('distribute', 'verb', 'to give out', 'Distribute products.'),
    ('distribution', 'noun', 'giving out', 'Distribution channel.'),
    ('distributor', 'noun', 'supplier', 'Authorized distributor.'),
    ('district', 'noun', 'area', 'Business district.'),
    ('disturb', 'verb', 'to interrupt', 'Do not disturb.'),
    ('disturbance', 'noun', 'interruption', 'Market disturbance.'),
    ('diverge', 'verb', 'to separate', 'Paths diverge.'),
    ('divergence', 'noun', 'separation', 'Policy divergence.'),
    ('diverse', 'adj', 'varied', 'Diverse portfolio.'),
    ('diversification', 'noun', 'variety', 'Portfolio diversification.'),
    ('diversify', 'verb', 'to vary', 'Diversify investments.'),
    ('diversity', 'noun', 'variety', 'Workplace diversity.'),
    ('divert', 'verb', 'to redirect', 'Divert funds.'),
    ('divide', 'verb', 'to separate', 'Divide profits.'),
    ('dividend', 'noun', 'share of profit', 'Pay dividend.'),
    ('division', 'noun', 'section', 'Sales division.'),
    ('dock', 'noun', 'loading area', 'Loading dock.'),
    ('doctor', 'noun', 'physician', 'Company doctor.'),
    ('doctrine', 'noun', 'principle', 'Business doctrine.'),
    ('document', 'noun', 'paper', 'Legal document.'),
    ('documentation', 'noun', 'papers', 'Proper documentation.'),
    ('dollar', 'noun', 'currency', 'Dollar value.'),
    ('domain', 'noun', 'area', 'Public domain.'),
    ('domestic', 'adj', 'home country', 'Domestic market.'),
    ('dominate', 'verb', 'to control', 'Dominate market.'),
    ('domination', 'noun', 'control', 'Market domination.'),
    ('dominant', 'adj', 'most influential', 'Dominant player.'),
    ('donate', 'verb', 'to give', 'Donate to charity.'),
    ('donation', 'noun', 'gift', 'Charitable donation.'),
    ('donor', 'noun', 'giver', 'Major donor.'),
    ('doom', 'noun', 'destruction', 'Doom and gloom.'),
    ('door', 'noun', 'entrance', 'Open door policy.'),
    ('dormant', 'adj', 'inactive', 'Dormant account.'),
    ('dose', 'noun', 'amount', 'Small dose.'),
    ('dot', 'noun', 'point', 'Dot com.'),
    ('double', 'verb', 'to multiply by two', 'Double sales.'),
    ('doubt', 'noun', 'uncertainty', 'Beyond doubt.'),
    ('doubtful', 'adj', 'uncertain', 'Doubtful outcome.'),
    ('down', 'adv', 'lower', 'Prices down.'),
    ('downfall', 'noun', 'ruin', 'Company downfall.'),
    ('downgrade', 'verb', 'to lower', 'Downgrade rating.'),
    ('download', 'verb', 'to transfer', 'Download file.'),
    ('downside', 'noun', 'disadvantage', 'Potential downside.'),
    ('downsize', 'verb', 'to reduce', 'Downsize workforce.'),
    ('downsizing', 'noun', 'reduction', 'Corporate downsizing.'),
    ('downstream', 'adj', 'later in process', 'Downstream effects.'),
    ('downturn', 'noun', 'decline', 'Economic downturn.'),
    ('downward', 'adj', 'moving down', 'Downward trend.'),
    ('dozen', 'noun', 'twelve', 'Dozen items.'),
    ('draft', 'noun', 'preliminary version', 'First draft.'),
    ('drag', 'verb', 'to pull', 'Drag on results.'),
    ('drain', 'verb', 'to empty', 'Drain resources.'),
    ('dramatic', 'adj', 'striking', 'Dramatic increase.'),
    ('dramatically', 'adv', 'strikingly', 'Dramatically improved.'),
    ('draw', 'verb', 'to attract', 'Draw attention.'),
    ('drawback', 'noun', 'disadvantage', 'Major drawback.'),
    ('drawing', 'noun', 'illustration', 'Technical drawing.'),
    ('dread', 'verb', 'to fear', 'Dread deadline.'),
    ('dream', 'noun', 'aspiration', 'Business dream.'),
    ('dress', 'noun', 'clothing', 'Dress code.'),
    ('drift', 'verb', 'to move slowly', 'Prices drift.'),
    ('drill', 'noun', 'practice', 'Fire drill.'),
    ('drink', 'noun', 'beverage', 'Soft drink.'),
    ('drive', 'verb', 'to push', 'Drive growth.'),
    ('driver', 'noun', 'cause', 'Key driver.'),
    ('drop', 'verb', 'to fall', 'Prices drop.'),
    ('drought', 'noun', 'dry period', 'Cash drought.'),
    ('drug', 'noun', 'medicine', 'Drug industry.'),
    ('dual', 'adj', 'double', 'Dual role.'),
    ('due', 'adj', 'owed', 'Payment due.'),
    ('dull', 'adj', 'boring', 'Dull market.'),
    ('dump', 'verb', 'to discard', 'Dump stock.'),
    ('dumping', 'noun', 'selling cheaply', 'Price dumping.'),
    ('duplicate', 'verb', 'to copy', 'Duplicate files.'),
    ('durable', 'adj', 'long-lasting', 'Durable goods.'),
    ('duration', 'noun', 'length of time', 'Contract duration.'),
    ('during', 'prep', 'throughout', 'During meeting.'),
    ('dust', 'noun', 'dirt', 'Gather dust.'),
    ('duty', 'noun', 'responsibility', 'Customs duty.'),
    ('dwell', 'verb', 'to live', 'Dwell on problems.'),
    ('dwelling', 'noun', 'residence', 'Private dwelling.'),
    ('dynamic', 'adj', 'active', 'Dynamic market.'),
    ('dynamics', 'noun', 'forces', 'Market dynamics.'),
    ('eager', 'adj', 'keen', 'Eager to learn.'),
    ('early', 'adj', 'before expected', 'Early retirement.'),
    ('earn', 'verb', 'to receive', 'Earn profit.'),
    ('earnest', 'adj', 'serious', 'Earnest effort.'),
    ('earning', 'noun', 'income', 'Earning potential.'),
    ('earnings', 'noun', 'profits', 'Quarterly earnings.'),
    ('earth', 'noun', 'world', 'Down to earth.'),
    ('ease', 'noun', 'comfort', 'With ease.'),
    ('easily', 'adv', 'without difficulty', 'Easily accessible.'),
    ('east', 'noun', 'direction', 'Far East.'),
    ('eastern', 'adj', 'from east', 'Eastern markets.'),
    ('easy', 'adj', 'not difficult', 'Easy access.'),
    ('echo', 'verb', 'to repeat', 'Echo sentiment.'),
    ('ecological', 'adj', 'environmental', 'Ecological impact.'),
    ('ecology', 'noun', 'environment', 'Business ecology.'),
    ('economic', 'adj', 'financial', 'Economic growth.'),
    ('economical', 'adj', 'cost-effective', 'Economical solution.'),
    ('economics', 'noun', 'financial science', 'Business economics.'),
    ('economist', 'noun', 'financial expert', 'Chief economist.'),
    ('economize', 'verb', 'to save', 'Economize on costs.'),
    ('economy', 'noun', 'financial system', 'Global economy.'),
    ('ecosystem', 'noun', 'system', 'Business ecosystem.'),
    ('edge', 'noun', 'advantage', 'Competitive edge.'),
    ('edit', 'verb', 'to revise', 'Edit document.'),
    ('edition', 'noun', 'version', 'Limited edition.'),
    ('editor', 'noun', 'reviser', 'Text editor.'),
    ('editorial', 'adj', 'relating to editing', 'Editorial policy.'),
    ('educate', 'verb', 'to teach', 'Educate customers.'),
    ('education', 'noun', 'learning', 'Business education.'),
    ('educational', 'adj', 'relating to education', 'Educational program.'),
    ('educator', 'noun', 'teacher', 'Business educator.'),
    ('effect', 'noun', 'result', 'Positive effect.'),
    ('effective', 'adj', 'successful', 'Effective strategy.'),
    ('effectively', 'adv', 'successfully', 'Work effectively.'),
    ('effectiveness', 'noun', 'success', 'Cost effectiveness.'),
    ('efficiency', 'noun', 'productivity', 'Improve efficiency.'),
    ('efficient', 'adj', 'productive', 'Efficient process.'),
    ('efficiently', 'adv', 'productively', 'Work efficiently.'),
    ('effort', 'noun', 'attempt', 'Joint effort.'),
    ('elaborate', 'adj', 'detailed', 'Elaborate plan.'),
    ('elastic', 'adj', 'flexible', 'Price elastic.'),
    ('elasticity', 'noun', 'flexibility', 'Price elasticity.'),
    ('elder', 'adj', 'older', 'Elder statesman.'),
    ('elderly', 'adj', 'old', 'Elderly customers.'),
    ('elect', 'verb', 'to choose', 'Elect board.'),
    ('election', 'noun', 'voting', 'Board election.'),
    ('electric', 'adj', 'using electricity', 'Electric vehicle.'),
    ('electrical', 'adj', 'relating to electricity', 'Electrical equipment.'),
    ('electricity', 'noun', 'electric power', 'Electricity cost.'),
    ('electronic', 'adj', 'digital', 'Electronic payment.'),
    ('electronics', 'noun', 'electronic devices', 'Consumer electronics.'),
    ('elegance', 'noun', 'grace', 'Design elegance.'),
    ('elegant', 'adj', 'graceful', 'Elegant solution.'),
    ('element', 'noun', 'component', 'Key element.'),
    ('elementary', 'adj', 'basic', 'Elementary level.'),
    ('elevate', 'verb', 'to raise', 'Elevate status.'),
    ('elevation', 'noun', 'raising', 'Job elevation.'),
    ('elevator', 'noun', 'lift', 'Elevator pitch.'),
    ('eligibility', 'noun', 'qualification', 'Check eligibility.'),
    ('eligible', 'adj', 'qualified', 'Eligible candidate.'),
    ('eliminate', 'verb', 'to remove', 'Eliminate waste.'),
    ('elimination', 'noun', 'removal', 'Cost elimination.'),
    ('elite', 'noun', 'top group', 'Business elite.'),
    ('eloquent', 'adj', 'well-spoken', 'Eloquent speaker.'),
    ('elsewhere', 'adv', 'in another place', 'Look elsewhere.'),
    ('email', 'noun', 'electronic mail', 'Send email.'),
    ('embark', 'verb', 'to begin', 'Embark on project.'),
    ('embarrass', 'verb', 'to shame', 'Embarrass company.'),
    ('embarrassment', 'noun', 'shame', 'Avoid embarrassment.'),
    ('embassy', 'noun', 'diplomatic office', 'Trade embassy.'),
    ('embed', 'verb', 'to fix firmly', 'Embed values.'),
    ('embody', 'verb', 'to represent', 'Embody quality.'),
    ('embrace', 'verb', 'to accept', 'Embrace change.'),
    ('emerge', 'verb', 'to appear', 'Emerge as leader.'),
    ('emergence', 'noun', 'appearance', 'Market emergence.'),
    ('emergency', 'noun', 'crisis', 'Emergency fund.'),
    ('emergent', 'adj', 'emerging', 'Emergent market.'),
    ('emerging', 'adj', 'developing', 'Emerging markets.'),
    ('emission', 'noun', 'discharge', 'Carbon emission.'),
    ('emit', 'verb', 'to release', 'Emit signals.'),
    ('emotion', 'noun', 'feeling', 'Strong emotion.'),
    ('emotional', 'adj', 'relating to feelings', 'Emotional appeal.'),
    ('emphasis', 'noun', 'importance', 'Place emphasis.'),
    ('emphasize', 'verb', 'to stress', 'Emphasize quality.'),
    ('empire', 'noun', 'large organization', 'Business empire.'),
    ('empirical', 'adj', 'based on observation', 'Empirical data.'),
    ('employ', 'verb', 'to hire', 'Employ workers.'),
    ('employee', 'noun', 'worker', 'Full-time employee.'),
    ('employer', 'noun', 'company', 'Top employer.'),
    ('employment', 'noun', 'work', 'Full employment.'),
    ('empower', 'verb', 'to give power', 'Empower employees.'),
    ('empowerment', 'noun', 'giving power', 'Employee empowerment.'),
    ('empty', 'adj', 'containing nothing', 'Empty office.'),
    ('enable', 'verb', 'to make possible', 'Enable growth.'),
    ('enact', 'verb', 'to make law', 'Enact policy.'),
    ('encounter', 'verb', 'to meet', 'Encounter problems.'),
    ('encourage', 'verb', 'to support', 'Encourage innovation.'),
    ('encouragement', 'noun', 'support', 'Provide encouragement.'),
    ('end', 'noun', 'finish', 'Year end.'),
    ('endanger', 'verb', 'to put at risk', 'Endanger profits.'),
    ('endeavor', 'noun', 'effort', 'Business endeavor.'),
    ('ending', 'noun', 'conclusion', 'Happy ending.'),
    ('endless', 'adj', 'without end', 'Endless possibilities.'),
    ('endorse', 'verb', 'to support', 'Endorse product.'),
    ('endorsement', 'noun', 'support', 'Celebrity endorsement.'),
    ('endow', 'verb', 'to provide', 'Endow with skills.'),
    ('endowment', 'noun', 'gift', 'Endowment fund.'),
    ('endure', 'verb', 'to last', 'Endure hardship.'),
    ('enduring', 'adj', 'lasting', 'Enduring value.'),
    ('enemy', 'noun', 'opponent', 'Business enemy.'),
    ('energetic', 'adj', 'active', 'Energetic team.'),
    ('energy', 'noun', 'power', 'Renewable energy.'),
    ('enforce', 'verb', 'to apply', 'Enforce rules.'),
    ('enforcement', 'noun', 'application', 'Law enforcement.'),
    ('engage', 'verb', 'to involve', 'Engage customers.'),
    ('engaged', 'adj', 'involved', 'Engaged workforce.'),
    ('engagement', 'noun', 'involvement', 'Customer engagement.'),
    ('engine', 'noun', 'motor', 'Growth engine.'),
    ('engineer', 'noun', 'technical expert', 'Software engineer.'),
    ('engineering', 'noun', 'technical work', 'Financial engineering.'),
    ('enhance', 'verb', 'to improve', 'Enhance performance.'),
    ('enhancement', 'noun', 'improvement', 'Product enhancement.'),
    ('enjoy', 'verb', 'to experience pleasure', 'Enjoy success.'),
    ('enjoyment', 'noun', 'pleasure', 'Customer enjoyment.'),
    ('enlarge', 'verb', 'to make bigger', 'Enlarge scope.'),
    ('enlighten', 'verb', 'to inform', 'Enlighten audience.'),
    ('enormous', 'adj', 'very large', 'Enormous potential.'),
    ('enough', 'adj', 'sufficient', 'Enough resources.'),
    ('enquire', 'verb', 'to ask', 'Enquire about.'),
    ('enquiry', 'noun', 'question', 'Customer enquiry.'),
    ('enrich', 'verb', 'to improve', 'Enrich experience.'),
    ('enroll', 'verb', 'to register', 'Enroll in program.'),
    ('enrollment', 'noun', 'registration', 'Program enrollment.'),
    ('ensure', 'verb', 'to make certain', 'Ensure quality.'),
    ('enter', 'verb', 'to go into', 'Enter market.'),
    ('enterprise', 'noun', 'business', 'Small enterprise.'),
    ('entertain', 'verb', 'to amuse', 'Entertain clients.'),
    ('entertainment', 'noun', 'amusement', 'Entertainment industry.'),
    ('enthusiasm', 'noun', 'eagerness', 'Show enthusiasm.'),
    ('enthusiastic', 'adj', 'eager', 'Enthusiastic response.'),
    ('entire', 'adj', 'whole', 'Entire company.'),
    ('entirely', 'adv', 'completely', 'Entirely new.'),
    ('entitle', 'verb', 'to give right', 'Entitle to benefits.'),
    ('entitlement', 'noun', 'right', 'Employee entitlement.'),
    ('entity', 'noun', 'organization', 'Legal entity.'),
    ('entrance', 'noun', 'entry', 'Main entrance.'),
    ('entrepreneur', 'noun', 'business starter', 'Young entrepreneur.'),
    ('entrepreneurial', 'adj', 'business-minded', 'Entrepreneurial spirit.'),
    ('entrepreneurship', 'noun', 'business creation', 'Promote entrepreneurship.'),
    ('entry', 'noun', 'entrance', 'Market entry.'),
    ('envelope', 'noun', 'paper container', 'Push the envelope.'),
    ('environment', 'noun', 'surroundings', 'Work environment.'),
    ('environmental', 'adj', 'relating to environment', 'Environmental impact.'),
    ('envisage', 'verb', 'to imagine', 'Envisage future.'),
    ('envision', 'verb', 'to imagine', 'Envision success.'),
    ('equal', 'adj', 'same', 'Equal opportunity.'),
    ('equality', 'noun', 'sameness', 'Gender equality.'),
    ('equally', 'adv', 'in same way', 'Equally important.'),
    ('equation', 'noun', 'formula', 'Business equation.'),
    ('equip', 'verb', 'to provide', 'Equip team.'),
    ('equipment', 'noun', 'tools', 'Office equipment.'),
    ('equity', 'noun', 'ownership', 'Home equity.'),
    ('equivalent', 'adj', 'equal', 'Equivalent value.'),
    ('era', 'noun', 'period', 'New era.'),
    ('eradicate', 'verb', 'to eliminate', 'Eradicate waste.'),
    ('erode', 'verb', 'to wear away', 'Erode profits.'),
    ('erosion', 'noun', 'wearing away', 'Margin erosion.'),
    ('err', 'verb', 'to make mistake', 'Err on caution.'),
    ('errand', 'noun', 'short trip', 'Run errands.'),
    ('error', 'noun', 'mistake', 'Human error.'),
    ('escalate', 'verb', 'to increase', 'Escalate issue.'),
    ('escalation', 'noun', 'increase', 'Cost escalation.'),
    ('escape', 'verb', 'to get away', 'Escape liability.'),
    ('escort', 'verb', 'to accompany', 'Escort visitors.'),
    ('especially', 'adv', 'particularly', 'Especially important.'),
    ('essence', 'noun', 'core', 'In essence.'),
    ('essential', 'adj', 'necessary', 'Essential skills.'),
    ('essentially', 'adv', 'basically', 'Essentially complete.'),
    ('establish', 'verb', 'to set up', 'Establish company.'),
    ('established', 'adj', 'set up', 'Well established.'),
    ('establishment', 'noun', 'organization', 'Business establishment.'),
    ('estate', 'noun', 'property', 'Real estate.'),
    ('esteem', 'noun', 'respect', 'High esteem.'),
    ('estimate', 'noun', 'guess', 'Cost estimate.'),
    ('estimation', 'noun', 'judgment', 'In my estimation.'),
    ('eternal', 'adj', 'forever', 'Eternal value.'),
    ('ethic', 'noun', 'moral principle', 'Work ethic.'),
    ('ethical', 'adj', 'moral', 'Ethical business.'),
    ('ethics', 'noun', 'moral principles', 'Business ethics.'),
    ('ethnic', 'adj', 'cultural', 'Ethnic diversity.'),
    ('evaluate', 'verb', 'to assess', 'Evaluate performance.'),
    ('evaluation', 'noun', 'assessment', 'Job evaluation.'),
    ('eve', 'noun', 'day before', 'On the eve.'),
    ('even', 'adj', 'equal', 'Even distribution.'),
    ('event', 'noun', 'occasion', 'Corporate event.'),
    ('eventual', 'adj', 'final', 'Eventual outcome.'),
    ('eventually', 'adv', 'finally', 'Eventually succeed.'),
    ('ever', 'adv', 'at any time', 'Ever increasing.'),
    ('every', 'adj', 'each', 'Every customer.'),
    ('everybody', 'pron', 'everyone', 'Everybody knows.'),
    ('everyday', 'adj', 'daily', 'Everyday operations.'),
    ('everyone', 'pron', 'all people', 'Everyone agrees.'),
    ('everything', 'pron', 'all things', 'Everything included.'),
    ('everywhere', 'adv', 'in all places', 'Everywhere available.'),
    ('evidence', 'noun', 'proof', 'Clear evidence.'),
    ('evident', 'adj', 'obvious', 'Evident benefit.'),
    ('evidently', 'adv', 'obviously', 'Evidently successful.'),
    ('evil', 'adj', 'bad', 'Necessary evil.'),
    ('evolution', 'noun', 'development', 'Market evolution.'),
    ('evolve', 'verb', 'to develop', 'Evolve strategy.'),
    ('exact', 'adj', 'precise', 'Exact amount.'),
    ('exactly', 'adv', 'precisely', 'Exactly right.'),
    ('exaggerate', 'verb', 'to overstate', 'Exaggerate claims.'),
    ('examination', 'noun', 'inspection', 'Close examination.'),
    ('examine', 'verb', 'to inspect', 'Examine closely.'),
    ('examiner', 'noun', 'inspector', 'Bank examiner.'),
    ('example', 'noun', 'instance', 'Good example.'),
    ('exceed', 'verb', 'to go beyond', 'Exceed expectations.'),
    ('excel', 'verb', 'to be superior', 'Excel in service.'),
    ('excellence', 'noun', 'superiority', 'Strive for excellence.'),
    ('excellent', 'adj', 'outstanding', 'Excellent results.'),
    ('except', 'prep', 'excluding', 'Except weekends.'),
    ('exception', 'noun', 'exclusion', 'No exception.'),
    ('exceptional', 'adj', 'outstanding', 'Exceptional quality.'),
    ('exceptionally', 'adv', 'unusually', 'Exceptionally good.'),
    ('excess', 'noun', 'surplus', 'Excess inventory.'),
    ('excessive', 'adj', 'too much', 'Excessive cost.'),
    ('exchange', 'noun', 'trade', 'Stock exchange.'),
    ('excite', 'verb', 'to stimulate', 'Excite interest.'),
    ('excitement', 'noun', 'enthusiasm', 'Create excitement.'),
    ('exciting', 'adj', 'thrilling', 'Exciting opportunity.'),
    ('exclude', 'verb', 'to leave out', 'Exclude tax.'),
    ('excluding', 'prep', 'not including', 'Excluding shipping.'),
    ('exclusion', 'noun', 'leaving out', 'Policy exclusion.'),
    ('exclusive', 'adj', 'sole', 'Exclusive rights.'),
    ('exclusively', 'adv', 'only', 'Exclusively online.'),
    ('excuse', 'noun', 'reason', 'No excuse.'),
    ('execute', 'verb', 'to carry out', 'Execute plan.'),
    ('execution', 'noun', 'carrying out', 'Flawless execution.'),
    ('executive', 'noun', 'manager', 'Senior executive.'),
    ('exemplary', 'adj', 'excellent', 'Exemplary service.'),
    ('exemplify', 'verb', 'to illustrate', 'Exemplify quality.'),
    ('exempt', 'adj', 'free from', 'Tax exempt.'),
    ('exemption', 'noun', 'freedom from', 'Tax exemption.'),
    ('exercise', 'verb', 'to use', 'Exercise caution.'),
    ('exert', 'verb', 'to apply', 'Exert influence.'),
    ('exhaust', 'verb', 'to use up', 'Exhaust resources.'),
    ('exhausted', 'adj', 'tired', 'Exhausted supply.'),
    ('exhausting', 'adj', 'tiring', 'Exhausting work.'),
    ('exhaustion', 'noun', 'extreme tiredness', 'Near exhaustion.'),
    ('exhaustive', 'adj', 'thorough', 'Exhaustive search.'),
    ('exhibit', 'verb', 'to display', 'Exhibit products.'),
    ('exhibition', 'noun', 'display', 'Trade exhibition.'),
    ('exist', 'verb', 'to be', 'Opportunities exist.'),
    ('existence', 'noun', 'being', 'In existence.'),
    ('existing', 'adj', 'current', 'Existing customers.'),
    ('exit', 'noun', 'way out', 'Exit strategy.'),
    ('exotic', 'adj', 'unusual', 'Exotic markets.'),
    ('expand', 'verb', 'to grow', 'Expand business.'),
    ('expansion', 'noun', 'growth', 'Market expansion.'),
    ('expect', 'verb', 'to anticipate', 'Expect growth.'),
    ('expectation', 'noun', 'anticipation', 'Meet expectations.'),
    ('expected', 'adj', 'anticipated', 'Expected results.'),
    ('expedite', 'verb', 'to speed up', 'Expedite delivery.'),
    ('expedition', 'noun', 'journey', 'Business expedition.'),
    ('expel', 'verb', 'to force out', 'Expel member.'),
    ('expenditure', 'noun', 'spending', 'Capital expenditure.'),
    ('expense', 'noun', 'cost', 'Business expense.'),
    ('expensive', 'adj', 'costly', 'Expensive option.'),
    ('experience', 'noun', 'knowledge', 'Work experience.'),
    ('experienced', 'adj', 'skilled', 'Experienced manager.'),
    ('experiment', 'noun', 'test', 'Market experiment.'),
    ('experimental', 'adj', 'trial', 'Experimental phase.'),
    ('expert', 'noun', 'specialist', 'Industry expert.'),
    ('expertise', 'noun', 'skill', 'Technical expertise.'),
    ('expiration', 'noun', 'ending', 'Contract expiration.'),
    ('expire', 'verb', 'to end', 'Contract expires.'),
    ('expiry', 'noun', 'ending', 'Expiry date.'),
    ('explain', 'verb', 'to make clear', 'Explain process.'),
    ('explanation', 'noun', 'reason', 'Clear explanation.'),
    ('explicit', 'adj', 'clear', 'Explicit instructions.'),
    ('explicitly', 'adv', 'clearly', 'Explicitly stated.'),
    ('explode', 'verb', 'to burst', 'Demand exploded.'),
    ('exploit', 'verb', 'to use', 'Exploit opportunity.'),
    ('exploitation', 'noun', 'use', 'Resource exploitation.'),
    ('exploration', 'noun', 'search', 'Market exploration.'),
    ('explore', 'verb', 'to investigate', 'Explore options.'),
    ('explosion', 'noun', 'rapid increase', 'Data explosion.'),
    ('explosive', 'adj', 'rapid', 'Explosive growth.'),
    ('export', 'verb', 'to sell abroad', 'Export goods.'),
    ('exporter', 'noun', 'seller abroad', 'Major exporter.'),
    ('expose', 'verb', 'to reveal', 'Expose risk.'),
    ('exposure', 'noun', 'contact', 'Market exposure.'),
    ('express', 'verb', 'to state', 'Express opinion.'),
    ('expression', 'noun', 'statement', 'Common expression.'),
    ('extend', 'verb', 'to stretch', 'Extend deadline.'),
    ('extension', 'noun', 'addition', 'Contract extension.'),
    ('extensive', 'adj', 'wide', 'Extensive network.'),
    ('extensively', 'adv', 'widely', 'Used extensively.'),
    ('extent', 'noun', 'degree', 'To some extent.'),
    ('exterior', 'adj', 'outside', 'Exterior design.'),
    ('external', 'adj', 'outside', 'External audit.'),
    ('extra', 'adj', 'additional', 'Extra charge.'),
    ('extract', 'verb', 'to remove', 'Extract data.'),
    ('extraction', 'noun', 'removal', 'Data extraction.'),
    ('extraordinary', 'adj', 'exceptional', 'Extraordinary results.'),
    ('extreme', 'adj', 'very great', 'Extreme caution.'),
    ('extremely', 'adv', 'very', 'Extremely important.'),
]

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    existing = data.get('words', data)

print(f'기존 단어: {len(existing)}개')
word_set = {w['word'].lower() for w in existing}
new_words = [(w,p,m,e) for w,p,m,e in WORDS if w.lower() not in word_set]
print(f'추가할 새 단어: {len(new_words)}개')

if not new_words:
    print('추가할 단어 없음')
    exit()

langs = ['ko','ja','zh','es','pt','de','fr','vi','ar','id']
trans_by_lang = {}
print('번역 중...')
for lang in langs:
    print(f'  {lang}...', end=' ', flush=True)
    trans_by_lang[lang] = translate_batch([w[2] for w in new_words], lang)
    print('완료')
    time.sleep(0.2)

count = len(existing)
total = count + len(new_words)
for i, (word, pos, meaning, example) in enumerate(new_words):
    word_id = count + i + 1
    if word_id <= total // 4:
        level = '0-400'
    elif word_id <= total // 2:
        level = '400-600'
    elif word_id <= total * 3 // 4:
        level = '600-800'
    else:
        level = '800-990'
    trans = {lang: trans_by_lang[lang][i] if i < len(trans_by_lang[lang]) else meaning for lang in langs}
    existing.append({'id': word_id, 'word': word, 'meaning': meaning, 'example': example, 'pos': pos, 'level': level, 'translations': trans})

with open('assets/data/words.json', 'w', encoding='utf-8') as f:
    json.dump({'words': existing}, f, ensure_ascii=False, indent=2)

level_counts = {}
for w in existing:
    lv = w.get('level', '0-400')
    level_counts[lv] = level_counts.get(lv, 0) + 1

print(f'\n총 단어 수: {len(existing)}개')
for lv in ['0-400', '400-600', '600-800', '800-990']:
    print(f'  {lv}: {level_counts.get(lv, 0)}개')
