import json
import requests
import time

API_KEY = 'AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk'

def translate_batch(texts, target_lang):
    if not texts:
        return []
    url = f'https://translation.googleapis.com/language/translate/v2?key={API_KEY}'
    results = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        payload = {'q': batch, 'target': target_lang, 'source': 'en'}
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                translations = [t['translatedText'] for t in data['data']['translations']]
                results.extend(translations)
            else:
                results.extend(batch)
        except:
            results.extend(batch)
    return results

# More TOEIC words - F, G, H words
WORDS = [
    ('fabric', 'noun', 'cloth', 'Social fabric.'),
    ('fabricate', 'verb', 'to make up', 'Fabricate story.'),
    ('fabrication', 'noun', 'creation', 'Complete fabrication.'),
    ('fabulous', 'adj', 'wonderful', 'Fabulous deal.'),
    ('facade', 'noun', 'front', 'Company facade.'),
    ('face', 'verb', 'to confront', 'Face challenges.'),
    ('facilitate', 'verb', 'to make easier', 'Facilitate process.'),
    ('facilitation', 'noun', 'making easier', 'Trade facilitation.'),
    ('facilitator', 'noun', 'helper', 'Meeting facilitator.'),
    ('facility', 'noun', 'building', 'Production facility.'),
    ('fact', 'noun', 'truth', 'In fact.'),
    ('faction', 'noun', 'group', 'Company faction.'),
    ('factor', 'noun', 'element', 'Key factor.'),
    ('factory', 'noun', 'manufacturing plant', 'Factory output.'),
    ('factual', 'adj', 'based on facts', 'Factual information.'),
    ('faculty', 'noun', 'ability', 'Mental faculty.'),
    ('fade', 'verb', 'to disappear', 'Enthusiasm fades.'),
    ('fail', 'verb', 'to not succeed', 'Business fails.'),
    ('failure', 'noun', 'lack of success', 'Market failure.'),
    ('fair', 'adj', 'just', 'Fair deal.'),
    ('fairly', 'adv', 'justly', 'Fairly priced.'),
    ('fairness', 'noun', 'justice', 'Ensure fairness.'),
    ('faith', 'noun', 'trust', 'Good faith.'),
    ('faithful', 'adj', 'loyal', 'Faithful customer.'),
    ('fake', 'adj', 'not genuine', 'Fake product.'),
    ('fall', 'verb', 'to decrease', 'Prices fall.'),
    ('fallacy', 'noun', 'false idea', 'Common fallacy.'),
    ('fallout', 'noun', 'consequences', 'Economic fallout.'),
    ('false', 'adj', 'untrue', 'False claim.'),
    ('fame', 'noun', 'renown', 'Gain fame.'),
    ('familiar', 'adj', 'well-known', 'Familiar brand.'),
    ('familiarity', 'noun', 'knowledge', 'Brand familiarity.'),
    ('familiarize', 'verb', 'to acquaint', 'Familiarize yourself.'),
    ('family', 'noun', 'relatives', 'Family business.'),
    ('famine', 'noun', 'food shortage', 'Capital famine.'),
    ('famous', 'adj', 'well-known', 'Famous brand.'),
    ('fancy', 'adj', 'elaborate', 'Fancy packaging.'),
    ('fantastic', 'adj', 'excellent', 'Fantastic results.'),
    ('fantasy', 'noun', 'imagination', 'Market fantasy.'),
    ('far', 'adv', 'distant', 'So far.'),
    ('fare', 'noun', 'price', 'Bus fare.'),
    ('farewell', 'noun', 'goodbye', 'Farewell party.'),
    ('farm', 'noun', 'agricultural land', 'Server farm.'),
    ('farmer', 'noun', 'agriculturist', 'Local farmer.'),
    ('farming', 'noun', 'agriculture', 'Organic farming.'),
    ('fascinate', 'verb', 'to attract', 'Fascinate customers.'),
    ('fascinating', 'adj', 'interesting', 'Fascinating idea.'),
    ('fashion', 'noun', 'style', 'Fashion industry.'),
    ('fashionable', 'adj', 'stylish', 'Fashionable product.'),
    ('fast', 'adj', 'quick', 'Fast delivery.'),
    ('fasten', 'verb', 'to attach', 'Fasten seatbelt.'),
    ('fat', 'adj', 'thick', 'Fat profit.'),
    ('fatal', 'adj', 'deadly', 'Fatal flaw.'),
    ('fate', 'noun', 'destiny', 'Company fate.'),
    ('father', 'noun', 'male parent', 'Founding father.'),
    ('fatigue', 'noun', 'tiredness', 'Decision fatigue.'),
    ('fault', 'noun', 'defect', 'Product fault.'),
    ('faulty', 'adj', 'defective', 'Faulty equipment.'),
    ('favor', 'noun', 'preference', 'In favor of.'),
    ('favorable', 'adj', 'positive', 'Favorable terms.'),
    ('favorite', 'adj', 'preferred', 'Customer favorite.'),
    ('fax', 'noun', 'facsimile', 'Send fax.'),
    ('fear', 'noun', 'anxiety', 'Fear of failure.'),
    ('feasibility', 'noun', 'possibility', 'Feasibility study.'),
    ('feasible', 'adj', 'possible', 'Feasible plan.'),
    ('feast', 'noun', 'celebration', 'Sales feast.'),
    ('feat', 'noun', 'achievement', 'Remarkable feat.'),
    ('feature', 'noun', 'characteristic', 'Key feature.'),
    ('federal', 'adj', 'national', 'Federal law.'),
    ('federation', 'noun', 'union', 'Trade federation.'),
    ('fee', 'noun', 'charge', 'Service fee.'),
    ('feed', 'verb', 'to supply', 'Feed data.'),
    ('feedback', 'noun', 'response', 'Customer feedback.'),
    ('feel', 'verb', 'to sense', 'Feel confident.'),
    ('feeling', 'noun', 'emotion', 'General feeling.'),
    ('fellow', 'noun', 'colleague', 'Fellow employee.'),
    ('fellowship', 'noun', 'companionship', 'Professional fellowship.'),
    ('female', 'adj', 'woman', 'Female executive.'),
    ('fence', 'noun', 'barrier', 'On the fence.'),
    ('ferry', 'noun', 'boat', 'Ferry service.'),
    ('fertile', 'adj', 'productive', 'Fertile ground.'),
    ('festival', 'noun', 'celebration', 'Sales festival.'),
    ('fetch', 'verb', 'to bring', 'Fetch high price.'),
    ('fever', 'noun', 'excitement', 'Merger fever.'),
    ('few', 'adj', 'not many', 'Few options.'),
    ('fiber', 'noun', 'thread', 'Optical fiber.'),
    ('fiction', 'noun', 'made-up story', 'Legal fiction.'),
    ('fictitious', 'adj', 'made up', 'Fictitious company.'),
    ('fidelity', 'noun', 'loyalty', 'Brand fidelity.'),
    ('field', 'noun', 'area', 'Field of work.'),
    ('fierce', 'adj', 'intense', 'Fierce competition.'),
    ('figure', 'noun', 'number', 'Sales figures.'),
    ('file', 'noun', 'document', 'File report.'),
    ('fill', 'verb', 'to make full', 'Fill order.'),
    ('filter', 'verb', 'to screen', 'Filter data.'),
    ('final', 'adj', 'last', 'Final decision.'),
    ('finalize', 'verb', 'to complete', 'Finalize deal.'),
    ('finally', 'adv', 'at last', 'Finally approved.'),
    ('finance', 'noun', 'money management', 'Corporate finance.'),
    ('financial', 'adj', 'monetary', 'Financial report.'),
    ('financially', 'adv', 'monetarily', 'Financially stable.'),
    ('financier', 'noun', 'money manager', 'Wall Street financier.'),
    ('financing', 'noun', 'funding', 'Project financing.'),
    ('find', 'verb', 'to discover', 'Find solution.'),
    ('finding', 'noun', 'discovery', 'Key finding.'),
    ('fine', 'adj', 'good', 'Fine quality.'),
    ('finger', 'noun', 'digit', 'Point finger.'),
    ('finish', 'verb', 'to complete', 'Finish project.'),
    ('finite', 'adj', 'limited', 'Finite resources.'),
    ('fire', 'verb', 'to dismiss', 'Fire employee.'),
    ('firewall', 'noun', 'security barrier', 'Network firewall.'),
    ('firm', 'noun', 'company', 'Law firm.'),
    ('firmly', 'adv', 'strongly', 'Firmly committed.'),
    ('first', 'adj', 'initial', 'First quarter.'),
    ('firsthand', 'adj', 'direct', 'Firsthand experience.'),
    ('fiscal', 'adj', 'financial', 'Fiscal year.'),
    ('fish', 'verb', 'to seek', 'Fish for information.'),
    ('fit', 'verb', 'to match', 'Fit requirements.'),
    ('fitness', 'noun', 'suitability', 'Fitness for purpose.'),
    ('fitting', 'adj', 'suitable', 'Fitting tribute.'),
    ('fix', 'verb', 'to repair', 'Fix problem.'),
    ('fixed', 'adj', 'set', 'Fixed cost.'),
    ('fixture', 'noun', 'permanent item', 'Office fixture.'),
    ('flag', 'verb', 'to mark', 'Flag issue.'),
    ('flagship', 'noun', 'leading item', 'Flagship store.'),
    ('flair', 'noun', 'talent', 'Marketing flair.'),
    ('flame', 'noun', 'fire', 'Fan the flames.'),
    ('flank', 'verb', 'to be at side', 'Flank competition.'),
    ('flash', 'noun', 'sudden burst', 'Flash sale.'),
    ('flat', 'adj', 'level', 'Flat rate.'),
    ('flavor', 'noun', 'taste', 'Flavor of the month.'),
    ('flaw', 'noun', 'defect', 'Design flaw.'),
    ('flawed', 'adj', 'defective', 'Flawed plan.'),
    ('flawless', 'adj', 'perfect', 'Flawless execution.'),
    ('flee', 'verb', 'to escape', 'Flee market.'),
    ('fleet', 'noun', 'group of vehicles', 'Company fleet.'),
    ('flesh', 'noun', 'substance', 'Flesh out details.'),
    ('flexibility', 'noun', 'adaptability', 'Schedule flexibility.'),
    ('flexible', 'adj', 'adaptable', 'Flexible hours.'),
    ('flight', 'noun', 'air journey', 'Business flight.'),
    ('flip', 'verb', 'to turn over', 'Flip strategy.'),
    ('float', 'verb', 'to drift', 'Float idea.'),
    ('flock', 'verb', 'to gather', 'Customers flock.'),
    ('flood', 'noun', 'overflow', 'Flood of orders.'),
    ('floor', 'noun', 'level', 'Trading floor.'),
    ('flop', 'noun', 'failure', 'Product flop.'),
    ('flourish', 'verb', 'to thrive', 'Business flourishes.'),
    ('flow', 'noun', 'movement', 'Cash flow.'),
    ('fluctuate', 'verb', 'to vary', 'Prices fluctuate.'),
    ('fluctuation', 'noun', 'variation', 'Market fluctuation.'),
    ('fluent', 'adj', 'able to speak well', 'Fluent in English.'),
    ('fluid', 'adj', 'changeable', 'Fluid situation.'),
    ('flurry', 'noun', 'burst', 'Flurry of activity.'),
    ('flush', 'adj', 'abundant', 'Flush with cash.'),
    ('fly', 'verb', 'to travel by air', 'Fly business class.'),
    ('focus', 'noun', 'center of attention', 'Main focus.'),
    ('folder', 'noun', 'file holder', 'Document folder.'),
    ('folk', 'noun', 'people', 'Business folk.'),
    ('follow', 'verb', 'to come after', 'Follow up.'),
    ('follower', 'noun', 'supporter', 'Market follower.'),
    ('following', 'adj', 'next', 'Following year.'),
    ('fond', 'adj', 'having affection', 'Fond of idea.'),
    ('food', 'noun', 'nourishment', 'Food industry.'),
    ('fool', 'noun', 'foolish person', 'April Fool.'),
    ('foolish', 'adj', 'unwise', 'Foolish decision.'),
    ('foot', 'verb', 'to pay', 'Foot the bill.'),
    ('footage', 'noun', 'film', 'Security footage.'),
    ('foothold', 'noun', 'secure position', 'Gain foothold.'),
    ('footprint', 'noun', 'impact', 'Carbon footprint.'),
    ('footstep', 'noun', 'step', 'Follow footsteps.'),
    ('forbid', 'verb', 'to prohibit', 'Forbid practice.'),
    ('force', 'noun', 'power', 'Sales force.'),
    ('forecast', 'noun', 'prediction', 'Sales forecast.'),
    ('foreground', 'noun', 'front', 'In foreground.'),
    ('foreign', 'adj', 'from abroad', 'Foreign market.'),
    ('foremost', 'adj', 'most important', 'Foremost priority.'),
    ('foresee', 'verb', 'to predict', 'Foresee problems.'),
    ('foreseeable', 'adj', 'predictable', 'Foreseeable future.'),
    ('foresight', 'noun', 'anticipation', 'Strategic foresight.'),
    ('forest', 'noun', 'wooded area', 'Forest industry.'),
    ('forever', 'adv', 'always', 'Last forever.'),
    ('forfeit', 'verb', 'to lose', 'Forfeit deposit.'),
    ('forge', 'verb', 'to create', 'Forge partnership.'),
    ('forget', 'verb', 'to fail to remember', 'Never forget.'),
    ('forgive', 'verb', 'to pardon', 'Forgive debt.'),
    ('fork', 'noun', 'division', 'Fork in road.'),
    ('form', 'noun', 'document', 'Application form.'),
    ('formal', 'adj', 'official', 'Formal agreement.'),
    ('formality', 'noun', 'official procedure', 'Legal formality.'),
    ('formally', 'adv', 'officially', 'Formally announced.'),
    ('format', 'noun', 'arrangement', 'File format.'),
    ('formation', 'noun', 'creation', 'Company formation.'),
    ('former', 'adj', 'previous', 'Former employee.'),
    ('formerly', 'adv', 'previously', 'Formerly known as.'),
    ('formidable', 'adj', 'powerful', 'Formidable competitor.'),
    ('formula', 'noun', 'method', 'Success formula.'),
    ('formulate', 'verb', 'to create', 'Formulate strategy.'),
    ('formulation', 'noun', 'creation', 'Policy formulation.'),
    ('forth', 'adv', 'forward', 'Set forth.'),
    ('forthcoming', 'adj', 'approaching', 'Forthcoming event.'),
    ('fortunate', 'adj', 'lucky', 'Fortunate timing.'),
    ('fortunately', 'adv', 'luckily', 'Fortunately approved.'),
    ('fortune', 'noun', 'wealth', 'Make fortune.'),
    ('forum', 'noun', 'meeting place', 'Business forum.'),
    ('forward', 'adv', 'ahead', 'Move forward.'),
    ('foster', 'verb', 'to encourage', 'Foster growth.'),
    ('foul', 'adj', 'unfair', 'Foul play.'),
    ('found', 'verb', 'to establish', 'Found company.'),
    ('foundation', 'noun', 'base', 'Solid foundation.'),
    ('founder', 'noun', 'creator', 'Company founder.'),
    ('fountain', 'noun', 'source', 'Fountain of ideas.'),
    ('fraction', 'noun', 'small part', 'Small fraction.'),
    ('fragile', 'adj', 'delicate', 'Fragile economy.'),
    ('fragment', 'noun', 'piece', 'Market fragment.'),
    ('fragmentation', 'noun', 'breaking up', 'Market fragmentation.'),
    ('frame', 'noun', 'structure', 'Time frame.'),
    ('framework', 'noun', 'structure', 'Legal framework.'),
    ('franchise', 'noun', 'license', 'Franchise agreement.'),
    ('franchisee', 'noun', 'license holder', 'Local franchisee.'),
    ('franchisor', 'noun', 'license grantor', 'Franchisor rights.'),
    ('frank', 'adj', 'honest', 'Frank discussion.'),
    ('frankly', 'adv', 'honestly', 'Frankly speaking.'),
    ('fraud', 'noun', 'deception', 'Insurance fraud.'),
    ('fraudulent', 'adj', 'deceptive', 'Fraudulent activity.'),
    ('free', 'adj', 'without cost', 'Free trial.'),
    ('freedom', 'noun', 'liberty', 'Financial freedom.'),
    ('freely', 'adv', 'without restriction', 'Trade freely.'),
    ('freeze', 'verb', 'to stop', 'Hiring freeze.'),
    ('freight', 'noun', 'cargo', 'Freight cost.'),
    ('frequency', 'noun', 'rate of occurrence', 'Purchase frequency.'),
    ('frequent', 'adj', 'often', 'Frequent flyer.'),
    ('frequently', 'adv', 'often', 'Frequently asked.'),
    ('fresh', 'adj', 'new', 'Fresh perspective.'),
    ('friction', 'noun', 'conflict', 'Reduce friction.'),
    ('friend', 'noun', 'ally', 'Business friend.'),
    ('friendly', 'adj', 'kind', 'User friendly.'),
    ('friendship', 'noun', 'bond', 'Business friendship.'),
    ('frighten', 'verb', 'to scare', 'Frighten investors.'),
    ('fringe', 'noun', 'edge', 'Fringe benefits.'),
    ('front', 'noun', 'forward part', 'Front office.'),
    ('frontier', 'noun', 'border', 'New frontier.'),
    ('frost', 'noun', 'cold', 'Market frost.'),
    ('frozen', 'adj', 'fixed', 'Frozen assets.'),
    ('frugal', 'adj', 'economical', 'Frugal spending.'),
    ('fruit', 'noun', 'result', 'Bear fruit.'),
    ('fruitful', 'adj', 'productive', 'Fruitful discussion.'),
    ('frustrate', 'verb', 'to disappoint', 'Frustrate customers.'),
    ('frustrating', 'adj', 'disappointing', 'Frustrating delay.'),
    ('frustration', 'noun', 'disappointment', 'Customer frustration.'),
    ('fuel', 'noun', 'energy source', 'Fuel costs.'),
    ('fulfill', 'verb', 'to complete', 'Fulfill order.'),
    ('fulfillment', 'noun', 'completion', 'Order fulfillment.'),
    ('full', 'adj', 'complete', 'Full capacity.'),
    ('fully', 'adv', 'completely', 'Fully booked.'),
    ('fumble', 'verb', 'to mishandle', 'Fumble opportunity.'),
    ('function', 'noun', 'purpose', 'Main function.'),
    ('functional', 'adj', 'working', 'Functional design.'),
    ('functionality', 'noun', 'capability', 'Core functionality.'),
    ('fund', 'noun', 'money', 'Investment fund.'),
    ('fundamental', 'adj', 'basic', 'Fundamental change.'),
    ('fundamentally', 'adv', 'basically', 'Fundamentally different.'),
    ('fundamentals', 'noun', 'basics', 'Market fundamentals.'),
    ('funding', 'noun', 'financing', 'Secure funding.'),
    ('fundraiser', 'noun', 'money collector', 'Corporate fundraiser.'),
    ('fundraising', 'noun', 'collecting money', 'Fundraising event.'),
    ('funeral', 'noun', 'burial ceremony', 'Funeral expenses.'),
    ('funny', 'adj', 'amusing', 'Funny business.'),
    ('furnish', 'verb', 'to provide', 'Furnish information.'),
    ('furniture', 'noun', 'movable items', 'Office furniture.'),
    ('further', 'adv', 'more', 'Further discussion.'),
    ('furthermore', 'adv', 'in addition', 'Furthermore important.'),
    ('fury', 'noun', 'rage', 'Customer fury.'),
    ('fuse', 'verb', 'to combine', 'Fuse operations.'),
    ('fusion', 'noun', 'combination', 'Company fusion.'),
    ('futile', 'adj', 'useless', 'Futile effort.'),
    ('future', 'noun', 'time ahead', 'Bright future.'),
    ('fuzzy', 'adj', 'unclear', 'Fuzzy logic.'),
    ('gadget', 'noun', 'device', 'Tech gadget.'),
    ('gain', 'verb', 'to obtain', 'Gain market share.'),
    ('gallery', 'noun', 'exhibition space', 'Photo gallery.'),
    ('gallon', 'noun', 'unit of measure', 'Price per gallon.'),
    ('gamble', 'noun', 'risk', 'Business gamble.'),
    ('game', 'noun', 'competition', 'Game changer.'),
    ('gang', 'noun', 'group', 'Work gang.'),
    ('gap', 'noun', 'space', 'Market gap.'),
    ('garage', 'noun', 'parking space', 'Parking garage.'),
    ('garbage', 'noun', 'waste', 'Garbage collection.'),
    ('garden', 'noun', 'planted area', 'Roof garden.'),
    ('garment', 'noun', 'clothing', 'Garment industry.'),
    ('gas', 'noun', 'fuel', 'Gas prices.'),
    ('gasoline', 'noun', 'petrol', 'Gasoline cost.'),
    ('gate', 'noun', 'entrance', 'Gate keeper.'),
    ('gateway', 'noun', 'entrance', 'Payment gateway.'),
    ('gather', 'verb', 'to collect', 'Gather data.'),
    ('gathering', 'noun', 'meeting', 'Annual gathering.'),
    ('gauge', 'verb', 'to measure', 'Gauge interest.'),
    ('gear', 'noun', 'equipment', 'Safety gear.'),
    ('gem', 'noun', 'valuable thing', 'Hidden gem.'),
    ('gender', 'noun', 'sex', 'Gender diversity.'),
    ('gene', 'noun', 'hereditary unit', 'Gene technology.'),
    ('general', 'adj', 'overall', 'General manager.'),
    ('generalize', 'verb', 'to make broad', 'Generalize findings.'),
    ('generally', 'adv', 'usually', 'Generally accepted.'),
    ('generate', 'verb', 'to produce', 'Generate revenue.'),
    ('generation', 'noun', 'age group', 'Next generation.'),
    ('generator', 'noun', 'producer', 'Power generator.'),
    ('generic', 'adj', 'general', 'Generic product.'),
    ('generous', 'adj', 'giving', 'Generous offer.'),
    ('generosity', 'noun', 'willingness to give', 'Show generosity.'),
    ('genius', 'noun', 'brilliant person', 'Marketing genius.'),
    ('genre', 'noun', 'type', 'Product genre.'),
    ('gentle', 'adj', 'mild', 'Gentle reminder.'),
    ('gentleman', 'noun', 'polite man', 'Gentleman agreement.'),
    ('gently', 'adv', 'mildly', 'Gently remind.'),
    ('genuine', 'adj', 'real', 'Genuine product.'),
    ('genuinely', 'adv', 'truly', 'Genuinely interested.'),
    ('geographic', 'adj', 'relating to geography', 'Geographic market.'),
    ('geographical', 'adj', 'relating to geography', 'Geographical area.'),
    ('geography', 'noun', 'study of places', 'Market geography.'),
    ('gesture', 'noun', 'movement', 'Good gesture.'),
    ('ghost', 'noun', 'spirit', 'Ghost writer.'),
    ('giant', 'noun', 'large company', 'Industry giant.'),
    ('gift', 'noun', 'present', 'Corporate gift.'),
    ('gifted', 'adj', 'talented', 'Gifted employee.'),
    ('gigantic', 'adj', 'huge', 'Gigantic project.'),
    ('gist', 'noun', 'main point', 'Get the gist.'),
    ('give', 'verb', 'to provide', 'Give feedback.'),
    ('given', 'adj', 'particular', 'At any given time.'),
    ('glad', 'adj', 'happy', 'Glad to help.'),
    ('glamour', 'noun', 'attractiveness', 'Corporate glamour.'),
    ('glance', 'noun', 'quick look', 'At first glance.'),
    ('glare', 'noun', 'harsh light', 'Media glare.'),
    ('glass', 'noun', 'transparent material', 'Glass ceiling.'),
    ('gleam', 'noun', 'shine', 'Gleam of hope.'),
    ('glide', 'verb', 'to move smoothly', 'Glide path.'),
    ('glimmer', 'noun', 'faint sign', 'Glimmer of hope.'),
    ('glimpse', 'noun', 'brief look', 'Glimpse of future.'),
    ('glitch', 'noun', 'problem', 'Technical glitch.'),
    ('global', 'adj', 'worldwide', 'Global market.'),
    ('globalization', 'noun', 'worldwide integration', 'Economic globalization.'),
    ('globally', 'adv', 'worldwide', 'Operate globally.'),
    ('globe', 'noun', 'world', 'Around the globe.'),
    ('gloom', 'noun', 'darkness', 'Economic gloom.'),
    ('gloomy', 'adj', 'dark', 'Gloomy forecast.'),
    ('glory', 'noun', 'honor', 'Past glory.'),
    ('glossy', 'adj', 'shiny', 'Glossy brochure.'),
    ('glove', 'noun', 'hand covering', 'Fit like a glove.'),
    ('glow', 'noun', 'brightness', 'Healthy glow.'),
    ('glue', 'noun', 'adhesive', 'Social glue.'),
    ('go', 'verb', 'to move', 'Go ahead.'),
    ('goal', 'noun', 'objective', 'Sales goal.'),
    ('gold', 'noun', 'precious metal', 'Gold standard.'),
    ('golden', 'adj', 'valuable', 'Golden opportunity.'),
    ('golf', 'noun', 'sport', 'Business golf.'),
    ('good', 'adj', 'satisfactory', 'Good value.'),
    ('goodness', 'noun', 'quality', 'Goodness sake.'),
    ('goods', 'noun', 'products', 'Consumer goods.'),
    ('goodwill', 'noun', 'friendly attitude', 'Build goodwill.'),
    ('govern', 'verb', 'to control', 'Govern conduct.'),
    ('governance', 'noun', 'management', 'Corporate governance.'),
    ('governing', 'adj', 'controlling', 'Governing body.'),
    ('government', 'noun', 'ruling body', 'Government contract.'),
    ('governmental', 'adj', 'relating to government', 'Governmental regulation.'),
    ('governor', 'noun', 'leader', 'State governor.'),
    ('grab', 'verb', 'to seize', 'Grab opportunity.'),
    ('grace', 'noun', 'elegance', 'Grace period.'),
    ('graceful', 'adj', 'elegant', 'Graceful exit.'),
    ('gracious', 'adj', 'kind', 'Gracious host.'),
    ('grade', 'noun', 'level', 'High grade.'),
    ('gradual', 'adj', 'slow', 'Gradual improvement.'),
    ('gradually', 'adv', 'slowly', 'Gradually increase.'),
    ('graduate', 'verb', 'to complete studies', 'Graduate program.'),
    ('graduation', 'noun', 'completion', 'Graduation ceremony.'),
    ('grain', 'noun', 'seed', 'Against the grain.'),
    ('grand', 'adj', 'large', 'Grand opening.'),
    ('grandeur', 'noun', 'magnificence', 'Corporate grandeur.'),
    ('grant', 'verb', 'to give', 'Grant permission.'),
    ('graphic', 'adj', 'visual', 'Graphic design.'),
    ('graphics', 'noun', 'visual images', 'Computer graphics.'),
    ('grasp', 'verb', 'to understand', 'Grasp concept.'),
    ('grass', 'noun', 'plant', 'Grassroots support.'),
    ('grateful', 'adj', 'thankful', 'Grateful for support.'),
    ('gratitude', 'noun', 'thankfulness', 'Express gratitude.'),
    ('grave', 'adj', 'serious', 'Grave concern.'),
    ('gravity', 'noun', 'seriousness', 'Understand gravity.'),
    ('gray', 'adj', 'unclear', 'Gray area.'),
    ('grease', 'verb', 'to facilitate', 'Grease wheels.'),
    ('great', 'adj', 'excellent', 'Great success.'),
    ('greatly', 'adv', 'very much', 'Greatly appreciated.'),
    ('greatness', 'noun', 'excellence', 'Achieve greatness.'),
    ('greed', 'noun', 'excessive desire', 'Corporate greed.'),
    ('greedy', 'adj', 'wanting more', 'Greedy investors.'),
    ('green', 'adj', 'environmentally friendly', 'Green initiative.'),
    ('greet', 'verb', 'to welcome', 'Greet customers.'),
    ('greeting', 'noun', 'welcome', 'Warm greeting.'),
    ('grey', 'adj', 'unclear', 'Grey market.'),
    ('grid', 'noun', 'network', 'Power grid.'),
    ('grief', 'noun', 'sorrow', 'Cause grief.'),
    ('grievance', 'noun', 'complaint', 'File grievance.'),
    ('grieve', 'verb', 'to mourn', 'Grieve loss.'),
    ('grill', 'verb', 'to question', 'Grill witnesses.'),
    ('grim', 'adj', 'serious', 'Grim outlook.'),
    ('grind', 'verb', 'to work hard', 'Daily grind.'),
    ('grip', 'noun', 'hold', 'Get a grip.'),
    ('grit', 'noun', 'determination', 'Show grit.'),
    ('grocery', 'noun', 'food store', 'Grocery chain.'),
    ('groom', 'verb', 'to prepare', 'Groom successor.'),
    ('gross', 'adj', 'total', 'Gross profit.'),
    ('ground', 'noun', 'basis', 'Common ground.'),
    ('groundbreaking', 'adj', 'innovative', 'Groundbreaking research.'),
    ('groundwork', 'noun', 'foundation', 'Lay groundwork.'),
    ('group', 'noun', 'collection', 'Focus group.'),
    ('grow', 'verb', 'to increase', 'Grow business.'),
    ('growing', 'adj', 'increasing', 'Growing demand.'),
    ('growth', 'noun', 'increase', 'Economic growth.'),
    ('guarantee', 'noun', 'promise', 'Money-back guarantee.'),
    ('guard', 'verb', 'to protect', 'Guard information.'),
    ('guardian', 'noun', 'protector', 'Legal guardian.'),
    ('guess', 'verb', 'to estimate', 'Best guess.'),
    ('guest', 'noun', 'visitor', 'Guest speaker.'),
    ('guidance', 'noun', 'direction', 'Provide guidance.'),
    ('guide', 'noun', 'instruction', 'Style guide.'),
    ('guideline', 'noun', 'rule', 'Follow guidelines.'),
    ('guild', 'noun', 'association', 'Trade guild.'),
    ('guilt', 'noun', 'responsibility', 'Admit guilt.'),
    ('guilty', 'adj', 'responsible', 'Found guilty.'),
    ('gulf', 'noun', 'gap', 'Wide gulf.'),
    ('gut', 'noun', 'intuition', 'Gut feeling.'),
    ('guy', 'noun', 'person', 'Good guy.'),
    ('gym', 'noun', 'exercise facility', 'Company gym.'),
    ('habit', 'noun', 'regular practice', 'Buying habit.'),
    ('habitat', 'noun', 'environment', 'Business habitat.'),
    ('hack', 'verb', 'to break into', 'Hack system.'),
    ('hail', 'verb', 'to praise', 'Hail success.'),
    ('hair', 'noun', 'strand', 'Hair trigger.'),
    ('half', 'noun', 'one of two parts', 'First half.'),
    ('halfway', 'adv', 'in the middle', 'Halfway point.'),
    ('hall', 'noun', 'large room', 'Conference hall.'),
    ('hallmark', 'noun', 'distinctive feature', 'Quality hallmark.'),
    ('halt', 'verb', 'to stop', 'Halt production.'),
    ('halve', 'verb', 'to cut in half', 'Halve costs.'),
    ('hammer', 'verb', 'to emphasize', 'Hammer out details.'),
    ('hand', 'noun', 'control', 'Upper hand.'),
    ('handbook', 'noun', 'manual', 'Employee handbook.'),
    ('handful', 'noun', 'small number', 'Handful of options.'),
    ('handicap', 'noun', 'disadvantage', 'Market handicap.'),
    ('handle', 'verb', 'to deal with', 'Handle complaint.'),
    ('handling', 'noun', 'management', 'Material handling.'),
    ('handout', 'noun', 'free material', 'Meeting handout.'),
    ('handover', 'noun', 'transfer', 'Project handover.'),
    ('handshake', 'noun', 'greeting', 'Business handshake.'),
    ('handsome', 'adj', 'large', 'Handsome profit.'),
    ('handy', 'adj', 'useful', 'Handy tool.'),
    ('hang', 'verb', 'to suspend', 'Hang in there.'),
    ('happen', 'verb', 'to occur', 'Things happen.'),
    ('happening', 'noun', 'event', 'Current happenings.'),
    ('happiness', 'noun', 'joy', 'Employee happiness.'),
    ('happy', 'adj', 'pleased', 'Happy customer.'),
    ('harass', 'verb', 'to bother', 'Harass employees.'),
    ('harassment', 'noun', 'bothering', 'Workplace harassment.'),
    ('harbor', 'verb', 'to hold', 'Harbor doubts.'),
    ('hard', 'adj', 'difficult', 'Hard work.'),
    ('harden', 'verb', 'to become firm', 'Harden position.'),
    ('hardly', 'adv', 'barely', 'Hardly any.'),
    ('hardship', 'noun', 'difficulty', 'Economic hardship.'),
    ('hardware', 'noun', 'equipment', 'Computer hardware.'),
    ('harm', 'noun', 'damage', 'Cause harm.'),
    ('harmful', 'adj', 'damaging', 'Harmful effect.'),
    ('harmless', 'adj', 'not harmful', 'Harmless error.'),
    ('harmonize', 'verb', 'to coordinate', 'Harmonize standards.'),
    ('harmony', 'noun', 'agreement', 'Work in harmony.'),
    ('harness', 'verb', 'to utilize', 'Harness potential.'),
    ('harsh', 'adj', 'severe', 'Harsh criticism.'),
    ('harvest', 'noun', 'gathering', 'Data harvest.'),
    ('haste', 'noun', 'speed', 'In haste.'),
    ('hasten', 'verb', 'to speed up', 'Hasten process.'),
    ('hasty', 'adj', 'too quick', 'Hasty decision.'),
    ('hate', 'verb', 'to dislike', 'Hate delays.'),
    ('haul', 'noun', 'transport', 'Long haul.'),
    ('haunt', 'verb', 'to trouble', 'Haunt company.'),
    ('haven', 'noun', 'safe place', 'Tax haven.'),
    ('havoc', 'noun', 'chaos', 'Wreak havoc.'),
    ('hazard', 'noun', 'danger', 'Safety hazard.'),
    ('hazardous', 'adj', 'dangerous', 'Hazardous materials.'),
    ('head', 'noun', 'leader', 'Department head.'),
    ('headache', 'noun', 'problem', 'Major headache.'),
    ('header', 'noun', 'title', 'Document header.'),
    ('heading', 'noun', 'title', 'Section heading.'),
    ('headline', 'noun', 'title', 'Make headlines.'),
    ('headlong', 'adv', 'rashly', 'Rush headlong.'),
    ('headquarter', 'verb', 'to base', 'Headquartered in.'),
    ('headquarters', 'noun', 'main office', 'Corporate headquarters.'),
    ('headway', 'noun', 'progress', 'Make headway.'),
    ('heal', 'verb', 'to cure', 'Heal divisions.'),
    ('health', 'noun', 'wellbeing', 'Financial health.'),
    ('healthcare', 'noun', 'medical services', 'Healthcare industry.'),
    ('healthy', 'adj', 'in good condition', 'Healthy profit.'),
    ('heap', 'noun', 'pile', 'Heap of work.'),
    ('hear', 'verb', 'to listen', 'Hear complaints.'),
    ('hearing', 'noun', 'listening session', 'Public hearing.'),
    ('heart', 'noun', 'center', 'Heart of matter.'),
    ('heartfelt', 'adj', 'sincere', 'Heartfelt thanks.'),
    ('heat', 'noun', 'pressure', 'Feel the heat.'),
    ('heated', 'adj', 'angry', 'Heated debate.'),
    ('heating', 'noun', 'warming', 'Heating costs.'),
    ('heaven', 'noun', 'paradise', 'Heaven sent.'),
    ('heavily', 'adv', 'greatly', 'Invest heavily.'),
    ('heavy', 'adj', 'substantial', 'Heavy losses.'),
    ('hectic', 'adj', 'very busy', 'Hectic schedule.'),
    ('hedge', 'verb', 'to protect', 'Hedge risk.'),
    ('heed', 'verb', 'to pay attention', 'Heed warning.'),
    ('heel', 'noun', 'back of foot', 'Achilles heel.'),
    ('hefty', 'adj', 'large', 'Hefty price.'),
    ('height', 'noun', 'peak', 'Height of success.'),
    ('heighten', 'verb', 'to increase', 'Heighten awareness.'),
    ('heir', 'noun', 'successor', 'Heir apparent.'),
    ('helicopter', 'noun', 'aircraft', 'Helicopter view.'),
    ('hell', 'noun', 'difficult situation', 'Through hell.'),
    ('hello', 'interj', 'greeting', 'Say hello.'),
    ('help', 'verb', 'to assist', 'Help customers.'),
    ('helper', 'noun', 'assistant', 'Office helper.'),
    ('helpful', 'adj', 'useful', 'Helpful advice.'),
    ('helpless', 'adj', 'unable to help', 'Feel helpless.'),
    ('hemisphere', 'noun', 'half of globe', 'Western hemisphere.'),
    ('hence', 'adv', 'therefore', 'Hence the decision.'),
    ('henceforth', 'adv', 'from now on', 'Henceforth required.'),
    ('her', 'pron', 'female', 'Her decision.'),
    ('herald', 'verb', 'to announce', 'Herald change.'),
    ('herb', 'noun', 'plant', 'Herbal product.'),
    ('herd', 'noun', 'group', 'Herd mentality.'),
    ('here', 'adv', 'in this place', 'Here and now.'),
    ('heritage', 'noun', 'inheritance', 'Corporate heritage.'),
    ('hero', 'noun', 'admired person', 'Business hero.'),
    ('heroic', 'adj', 'brave', 'Heroic effort.'),
    ('hesitant', 'adj', 'uncertain', 'Hesitant buyer.'),
    ('hesitate', 'verb', 'to pause', 'Hesitate to invest.'),
    ('hesitation', 'noun', 'pausing', 'Without hesitation.'),
    ('hidden', 'adj', 'concealed', 'Hidden costs.'),
    ('hide', 'verb', 'to conceal', 'Hide losses.'),
    ('hierarchy', 'noun', 'ranking system', 'Corporate hierarchy.'),
    ('high', 'adj', 'elevated', 'High priority.'),
    ('highlight', 'verb', 'to emphasize', 'Highlight benefits.'),
    ('highly', 'adv', 'very', 'Highly recommended.'),
    ('highway', 'noun', 'main road', 'Information highway.'),
    ('hike', 'noun', 'increase', 'Price hike.'),
    ('hill', 'noun', 'small mountain', 'Uphill battle.'),
    ('hinder', 'verb', 'to obstruct', 'Hinder progress.'),
    ('hindrance', 'noun', 'obstacle', 'Remove hindrance.'),
    ('hindsight', 'noun', 'looking back', 'In hindsight.'),
    ('hinge', 'verb', 'to depend', 'Hinge on decision.'),
    ('hint', 'noun', 'suggestion', 'Drop hint.'),
    ('hip', 'adj', 'fashionable', 'Hip brand.'),
    ('hire', 'verb', 'to employ', 'Hire staff.'),
    ('hiring', 'noun', 'employment', 'Hiring freeze.'),
    ('historic', 'adj', 'important in history', 'Historic achievement.'),
    ('historical', 'adj', 'relating to history', 'Historical data.'),
    ('historically', 'adv', 'in the past', 'Historically low.'),
    ('history', 'noun', 'past events', 'Company history.'),
    ('hit', 'verb', 'to reach', 'Hit target.'),
    ('hitch', 'noun', 'problem', 'Without a hitch.'),
    ('hitherto', 'adv', 'until now', 'Hitherto unknown.'),
    ('hoard', 'verb', 'to accumulate', 'Hoard cash.'),
    ('hobby', 'noun', 'leisure activity', 'Personal hobby.'),
    ('hold', 'verb', 'to have', 'Hold meeting.'),
    ('holder', 'noun', 'owner', 'Account holder.'),
    ('holding', 'noun', 'possession', 'Holding company.'),
    ('hole', 'noun', 'gap', 'Fill the hole.'),
    ('holiday', 'noun', 'vacation', 'Public holiday.'),
    ('hollow', 'adj', 'empty', 'Hollow promise.'),
    ('home', 'noun', 'residence', 'Work from home.'),
    ('homeland', 'noun', 'native country', 'Homeland security.'),
    ('homeless', 'adj', 'without home', 'Homeless shelter.'),
    ('homemade', 'adj', 'made at home', 'Homemade product.'),
    ('homepage', 'noun', 'main page', 'Company homepage.'),
    ('homework', 'noun', 'preparation', 'Do homework.'),
    ('honest', 'adj', 'truthful', 'Honest feedback.'),
    ('honestly', 'adv', 'truthfully', 'Honestly speaking.'),
    ('honesty', 'noun', 'truthfulness', 'Value honesty.'),
    ('honor', 'verb', 'to respect', 'Honor commitment.'),
    ('honorable', 'adj', 'respectable', 'Honorable mention.'),
    ('honorary', 'adj', 'given as honor', 'Honorary member.'),
    ('hook', 'noun', 'attraction', 'Marketing hook.'),
    ('hope', 'noun', 'expectation', 'High hopes.'),
    ('hopeful', 'adj', 'optimistic', 'Hopeful outlook.'),
    ('hopefully', 'adv', 'with hope', 'Hopefully succeed.'),
    ('hopeless', 'adj', 'without hope', 'Hopeless situation.'),
    ('horizon', 'noun', 'limit', 'On the horizon.'),
    ('horizontal', 'adj', 'level', 'Horizontal integration.'),
    ('horn', 'noun', 'warning device', 'Blow own horn.'),
    ('horrible', 'adj', 'very bad', 'Horrible mistake.'),
    ('horror', 'noun', 'fear', 'Horror story.'),
    ('horse', 'noun', 'animal', 'Dark horse.'),
    ('hospital', 'noun', 'medical facility', 'Hospital administration.'),
    ('hospitality', 'noun', 'friendly reception', 'Hospitality industry.'),
    ('host', 'noun', 'organizer', 'Host country.'),
    ('hostile', 'adj', 'unfriendly', 'Hostile takeover.'),
    ('hostility', 'noun', 'unfriendliness', 'Show hostility.'),
    ('hot', 'adj', 'popular', 'Hot topic.'),
    ('hotel', 'noun', 'lodging', 'Hotel industry.'),
    ('hotline', 'noun', 'direct line', 'Customer hotline.'),
    ('hour', 'noun', 'time period', 'Working hours.'),
    ('hourly', 'adj', 'every hour', 'Hourly rate.'),
    ('house', 'noun', 'building', 'In-house.'),
    ('household', 'noun', 'home', 'Household income.'),
    ('housekeeping', 'noun', 'maintenance', 'Office housekeeping.'),
    ('housing', 'noun', 'accommodation', 'Housing market.'),
    ('hover', 'verb', 'to remain', 'Prices hover.'),
    ('however', 'adv', 'nevertheless', 'However important.'),
    ('hub', 'noun', 'center', 'Business hub.'),
    ('hue', 'noun', 'color', 'Different hues.'),
    ('huge', 'adj', 'very large', 'Huge success.'),
    ('hugely', 'adv', 'very much', 'Hugely popular.'),
    ('hull', 'noun', 'body', 'Ship hull.'),
    ('human', 'adj', 'relating to people', 'Human resources.'),
    ('humane', 'adj', 'compassionate', 'Humane treatment.'),
    ('humanitarian', 'adj', 'caring for people', 'Humanitarian aid.'),
    ('humanity', 'noun', 'human beings', 'Serve humanity.'),
    ('humble', 'adj', 'modest', 'Humble beginnings.'),
    ('humid', 'adj', 'moist', 'Humid climate.'),
    ('humidity', 'noun', 'moisture', 'Control humidity.'),
    ('humiliate', 'verb', 'to embarrass', 'Humiliate competitor.'),
    ('humor', 'noun', 'comedy', 'Sense of humor.'),
    ('hundred', 'noun', 'number', 'Hundreds of options.'),
    ('hunger', 'noun', 'desire', 'Hunger for success.'),
    ('hungry', 'adj', 'wanting food', 'Hungry for growth.'),
    ('hunt', 'verb', 'to search', 'Hunt for talent.'),
    ('hunter', 'noun', 'searcher', 'Headhunter.'),
    ('hurdle', 'noun', 'obstacle', 'Clear hurdle.'),
    ('hurry', 'verb', 'to rush', 'Hurry up.'),
    ('hurt', 'verb', 'to harm', 'Hurt profits.'),
    ('husband', 'noun', 'male spouse', 'Husband resources.'),
    ('hybrid', 'adj', 'mixed', 'Hybrid model.'),
    ('hygiene', 'noun', 'cleanliness', 'Office hygiene.'),
    ('hype', 'noun', 'publicity', 'Marketing hype.'),
    ('hyperlink', 'noun', 'web link', 'Click hyperlink.'),
    ('hypothesis', 'noun', 'theory', 'Test hypothesis.'),
    ('hypothetical', 'adj', 'theoretical', 'Hypothetical scenario.'),
]

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    existing = data.get('words', data)

print(f'기존 단어: {len(existing)}개')
word_set = {w['word'].lower() for w in existing}
new_words = [(w,p,m,e) for w,p,m,e in WORDS if w.lower() not in word_set]
print(f'추가할 새 단어: {len(new_words)}개')

if not new_words:
    print('추가할 단어 없음')
    exit()

langs = ['ko','ja','zh','es','pt','de','fr','vi','ar','id']
trans_by_lang = {}
print('번역 중...')
for lang in langs:
    print(f'  {lang}...', end=' ', flush=True)
    trans_by_lang[lang] = translate_batch([w[2] for w in new_words], lang)
    print('완료')
    time.sleep(0.2)

count = len(existing)
total = count + len(new_words)
for i, (word, pos, meaning, example) in enumerate(new_words):
    word_id = count + i + 1
    if word_id <= total // 4:
        level = '0-400'
    elif word_id <= total // 2:
        level = '400-600'
    elif word_id <= total * 3 // 4:
        level = '600-800'
    else:
        level = '800-990'
    trans = {lang: trans_by_lang[lang][i] if i < len(trans_by_lang[lang]) else meaning for lang in langs}
    existing.append({'id': word_id, 'word': word, 'meaning': meaning, 'example': example, 'pos': pos, 'level': level, 'translations': trans})

with open('assets/data/words.json', 'w', encoding='utf-8') as f:
    json.dump({'words': existing}, f, ensure_ascii=False, indent=2)

level_counts = {}
for w in existing:
    lv = w.get('level', '0-400')
    level_counts[lv] = level_counts.get(lv, 0) + 1

print(f'\n총 단어 수: {len(existing)}개')
for lv in ['0-400', '400-600', '600-800', '800-990']:
    print(f'  {lv}: {level_counts.get(lv, 0)}개')
