import json
import requests
import time

API_KEY = 'AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk'

def translate_batch(texts, target_lang):
    if not texts:
        return []
    url = f'https://translation.googleapis.com/language/translate/v2?key={API_KEY}'
    results = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        payload = {'q': batch, 'target': target_lang, 'source': 'en'}
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                translations = [t['translatedText'] for t in data['data']['translations']]
                results.extend(translations)
            else:
                results.extend(batch)
        except:
            results.extend(batch)
    return results

# More TOEIC words - Business English, Finance, Office Life
WORDS = [
    ('abandon', 'verb', 'to give up', 'Abandon the project.'),
    ('abbreviate', 'verb', 'to shorten', 'Abbreviate the name.'),
    ('abolish', 'verb', 'to end officially', 'Abolish the policy.'),
    ('abound', 'verb', 'to be plentiful', 'Opportunities abound.'),
    ('absence', 'noun', 'being away', 'During her absence.'),
    ('absent', 'adj', 'not present', 'Absent from meeting.'),
    ('absorb', 'verb', 'to take in', 'Absorb costs.'),
    ('abundance', 'noun', 'large quantity', 'Abundance of resources.'),
    ('abundant', 'adj', 'plentiful', 'Abundant supply.'),
    ('abuse', 'noun', 'misuse', 'Prevent abuse.'),
    ('accelerate', 'verb', 'to speed up', 'Accelerate growth.'),
    ('acceptable', 'adj', 'good enough', 'Acceptable quality.'),
    ('acceptance', 'noun', 'agreement', 'Gain acceptance.'),
    ('accessibility', 'noun', 'ease of access', 'Website accessibility.'),
    ('accessory', 'noun', 'extra item', 'Computer accessories.'),
    ('accidental', 'adj', 'by chance', 'Accidental damage.'),
    ('accommodate', 'verb', 'to provide for', 'Accommodate guests.'),
    ('accommodation', 'noun', 'lodging', 'Hotel accommodation.'),
    ('accompany', 'verb', 'to go with', 'Accompany client.'),
    ('accomplishment', 'noun', 'achievement', 'Career accomplishment.'),
    ('accountable', 'adj', 'responsible', 'Held accountable.'),
    ('accumulate', 'verb', 'to gather', 'Accumulate wealth.'),
    ('accuracy', 'noun', 'correctness', 'Ensure accuracy.'),
    ('accusation', 'noun', 'charge', 'False accusation.'),
    ('accuse', 'verb', 'to blame', 'Accuse of fraud.'),
    ('accustomed', 'adj', 'used to', 'Accustomed to change.'),
    ('achievable', 'adj', 'possible', 'Achievable targets.'),
    ('acknowledge', 'verb', 'to recognize', 'Acknowledge receipt.'),
    ('acknowledgment', 'noun', 'recognition', 'Letter of acknowledgment.'),
    ('acquaint', 'verb', 'to familiarize', 'Acquaint with process.'),
    ('acquaintance', 'noun', 'person known', 'Business acquaintance.'),
    ('acquire', 'verb', 'to obtain', 'Acquire company.'),
    ('acquisition', 'noun', 'purchase', 'Recent acquisition.'),
    ('activate', 'verb', 'to start', 'Activate account.'),
    ('actively', 'adv', 'energetically', 'Actively participate.'),
    ('actual', 'adj', 'real', 'Actual costs.'),
    ('adapt', 'verb', 'to adjust', 'Adapt to change.'),
    ('adaptation', 'noun', 'adjustment', 'Market adaptation.'),
    ('addiction', 'noun', 'dependency', 'Phone addiction.'),
    ('additional', 'adj', 'extra', 'Additional cost.'),
    ('adequate', 'adj', 'sufficient', 'Adequate resources.'),
    ('adhere', 'verb', 'to stick to', 'Adhere to rules.'),
    ('adjacent', 'adj', 'next to', 'Adjacent building.'),
    ('adjourn', 'verb', 'to pause', 'Adjourn meeting.'),
    ('adjustment', 'noun', 'small change', 'Minor adjustment.'),
    ('administer', 'verb', 'to manage', 'Administer program.'),
    ('administration', 'noun', 'management', 'Business administration.'),
    ('administrative', 'adj', 'related to management', 'Administrative duties.'),
    ('administrator', 'noun', 'manager', 'System administrator.'),
    ('admission', 'noun', 'entrance', 'Free admission.'),
    ('adopt', 'verb', 'to take on', 'Adopt new policy.'),
    ('adoption', 'noun', 'acceptance', 'Technology adoption.'),
    ('advancement', 'noun', 'progress', 'Career advancement.'),
    ('advantage', 'noun', 'benefit', 'Competitive advantage.'),
    ('adverse', 'adj', 'negative', 'Adverse effect.'),
    ('advertise', 'verb', 'to promote', 'Advertise product.'),
    ('advertisement', 'noun', 'ad', 'Place advertisement.'),
    ('advise', 'verb', 'to recommend', 'Advise caution.'),
    ('adviser', 'noun', 'consultant', 'Financial adviser.'),
    ('advisory', 'adj', 'giving advice', 'Advisory board.'),
    ('advocate', 'verb', 'to support', 'Advocate change.'),
    ('affair', 'noun', 'matter', 'Business affairs.'),
    ('affect', 'verb', 'to influence', 'Affect outcome.'),
    ('affiliate', 'noun', 'associated company', 'Affiliate partner.'),
    ('affiliation', 'noun', 'connection', 'Corporate affiliation.'),
    ('affirm', 'verb', 'to confirm', 'Affirm commitment.'),
    ('affordable', 'adj', 'reasonably priced', 'Affordable options.'),
    ('aftermath', 'noun', 'consequences', 'Aftermath of crisis.'),
    ('agenda', 'noun', 'list of items', 'Meeting agenda.'),
    ('agent', 'noun', 'representative', 'Sales agent.'),
    ('aggregate', 'adj', 'total', 'Aggregate demand.'),
    ('aggressive', 'adj', 'forceful', 'Aggressive strategy.'),
    ('agile', 'adj', 'able to move quickly', 'Agile methodology.'),
    ('agreement', 'noun', 'contract', 'Sign agreement.'),
    ('aim', 'verb', 'to intend', 'Aim to succeed.'),
    ('aisle', 'noun', 'passage', 'Store aisle.'),
    ('alert', 'noun', 'warning', 'System alert.'),
    ('align', 'verb', 'to adjust', 'Align strategy.'),
    ('alignment', 'noun', 'arrangement', 'Strategic alignment.'),
    ('allegation', 'noun', 'claim', 'Serious allegation.'),
    ('allege', 'verb', 'to claim', 'Allege wrongdoing.'),
    ('allocate', 'verb', 'to assign', 'Allocate budget.'),
    ('allocation', 'noun', 'distribution', 'Resource allocation.'),
    ('allowance', 'noun', 'amount allowed', 'Travel allowance.'),
    ('ally', 'noun', 'partner', 'Strategic ally.'),
    ('alter', 'verb', 'to change', 'Alter plans.'),
    ('alteration', 'noun', 'change', 'Make alterations.'),
    ('alternate', 'adj', 'every other', 'Alternate solution.'),
    ('alternative', 'noun', 'other option', 'Consider alternatives.'),
    ('amateur', 'adj', 'not professional', 'Amateur approach.'),
    ('ambiguity', 'noun', 'uncertainty', 'Remove ambiguity.'),
    ('ambiguous', 'adj', 'unclear', 'Ambiguous terms.'),
    ('ambition', 'noun', 'desire for success', 'Professional ambition.'),
    ('ambitious', 'adj', 'aspiring', 'Ambitious plans.'),
    ('amend', 'verb', 'to revise', 'Amend contract.'),
    ('amendment', 'noun', 'change', 'Contract amendment.'),
    ('amenity', 'noun', 'convenience', 'Office amenities.'),
    ('amid', 'prep', 'in the middle of', 'Amid competition.'),
    ('ample', 'adj', 'plenty of', 'Ample time.'),
    ('analogy', 'noun', 'comparison', 'Draw analogy.'),
    ('analysis', 'noun', 'examination', 'Data analysis.'),
    ('analyst', 'noun', 'examiner', 'Business analyst.'),
    ('analyze', 'verb', 'to examine', 'Analyze data.'),
    ('anniversary', 'noun', 'yearly celebration', 'Company anniversary.'),
    ('announce', 'verb', 'to make known', 'Announce results.'),
    ('announcement', 'noun', 'public notice', 'Official announcement.'),
    ('annoyance', 'noun', 'irritation', 'Cause annoyance.'),
    ('annual', 'adj', 'yearly', 'Annual report.'),
    ('anonymous', 'adj', 'unnamed', 'Anonymous survey.'),
    ('anticipate', 'verb', 'to expect', 'Anticipate problems.'),
    ('anticipation', 'noun', 'expectation', 'In anticipation.'),
    ('anxious', 'adj', 'worried', 'Anxious about results.'),
    ('apart', 'adv', 'separate', 'Set apart.'),
    ('apology', 'noun', 'expression of regret', 'Issue apology.'),
    ('apparent', 'adj', 'obvious', 'Apparent reason.'),
    ('appeal', 'noun', 'attraction', 'Market appeal.'),
    ('appendix', 'noun', 'supplement', 'Report appendix.'),
    ('appliance', 'noun', 'device', 'Home appliances.'),
    ('applicable', 'adj', 'relevant', 'If applicable.'),
    ('applicant', 'noun', 'person applying', 'Job applicant.'),
    ('appoint', 'verb', 'to assign', 'Appoint manager.'),
    ('appointment', 'noun', 'scheduled meeting', 'Doctor appointment.'),
    ('appraisal', 'noun', 'evaluation', 'Performance appraisal.'),
    ('appreciate', 'verb', 'to value', 'Appreciate support.'),
    ('appreciation', 'noun', 'gratitude', 'Show appreciation.'),
    ('apprentice', 'noun', 'trainee', 'Hire apprentice.'),
    ('approach', 'noun', 'method', 'New approach.'),
    ('appropriate', 'adj', 'suitable', 'Appropriate action.'),
    ('approval', 'noun', 'permission', 'Get approval.'),
    ('approximate', 'adj', 'close to', 'Approximate cost.'),
    ('approximately', 'adv', 'about', 'Approximately 100.'),
    ('arbitrary', 'adj', 'random', 'Arbitrary decision.'),
    ('architect', 'noun', 'building designer', 'System architect.'),
    ('architecture', 'noun', 'structure', 'Software architecture.'),
    ('archive', 'noun', 'collection of records', 'Data archive.'),
    ('arguably', 'adv', 'possibly', 'Arguably the best.'),
    ('arise', 'verb', 'to occur', 'Problems arise.'),
    ('arrange', 'verb', 'to organize', 'Arrange meeting.'),
    ('arrangement', 'noun', 'plan', 'Make arrangements.'),
    ('array', 'noun', 'collection', 'Wide array.'),
    ('arrears', 'noun', 'overdue debt', 'In arrears.'),
    ('arrival', 'noun', 'coming', 'Upon arrival.'),
    ('article', 'noun', 'item', 'News article.'),
    ('articulate', 'verb', 'to express clearly', 'Articulate vision.'),
    ('artificial', 'adj', 'man-made', 'Artificial intelligence.'),
    ('ascertain', 'verb', 'to find out', 'Ascertain facts.'),
    ('aspect', 'noun', 'feature', 'Every aspect.'),
    ('aspiration', 'noun', 'ambition', 'Career aspirations.'),
    ('aspire', 'verb', 'to strive', 'Aspire to lead.'),
    ('assemble', 'verb', 'to put together', 'Assemble team.'),
    ('assembly', 'noun', 'gathering', 'Assembly line.'),
    ('assert', 'verb', 'to state firmly', 'Assert rights.'),
    ('assertion', 'noun', 'statement', 'Bold assertion.'),
    ('assess', 'verb', 'to evaluate', 'Assess risk.'),
    ('assessment', 'noun', 'evaluation', 'Risk assessment.'),
    ('asset', 'noun', 'valuable item', 'Company assets.'),
    ('assign', 'verb', 'to give task', 'Assign work.'),
    ('assignment', 'noun', 'task', 'New assignment.'),
    ('assist', 'verb', 'to help', 'Assist customer.'),
    ('assistance', 'noun', 'help', 'Technical assistance.'),
    ('assistant', 'noun', 'helper', 'Personal assistant.'),
    ('associate', 'noun', 'colleague', 'Business associate.'),
    ('association', 'noun', 'organization', 'Trade association.'),
    ('assume', 'verb', 'to take on', 'Assume responsibility.'),
    ('assumption', 'noun', 'supposition', 'Wrong assumption.'),
    ('assurance', 'noun', 'guarantee', 'Quality assurance.'),
    ('assure', 'verb', 'to guarantee', 'Assure quality.'),
    ('atmosphere', 'noun', 'environment', 'Work atmosphere.'),
    ('attach', 'verb', 'to connect', 'Attach file.'),
    ('attachment', 'noun', 'addition', 'Email attachment.'),
    ('attain', 'verb', 'to achieve', 'Attain goals.'),
    ('attainment', 'noun', 'achievement', 'Goal attainment.'),
    ('attempt', 'noun', 'try', 'First attempt.'),
    ('attendance', 'noun', 'presence', 'High attendance.'),
    ('attendant', 'noun', 'assistant', 'Flight attendant.'),
    ('attendee', 'noun', 'participant', 'Meeting attendee.'),
    ('attentive', 'adj', 'paying attention', 'Attentive listener.'),
    ('attorney', 'noun', 'lawyer', 'Corporate attorney.'),
    ('attract', 'verb', 'to draw', 'Attract investors.'),
    ('attraction', 'noun', 'appeal', 'Tourist attraction.'),
    ('attractive', 'adj', 'appealing', 'Attractive offer.'),
    ('attribute', 'verb', 'to assign', 'Attribute success.'),
    ('audit', 'noun', 'official examination', 'Financial audit.'),
    ('auditor', 'noun', 'examiner', 'External auditor.'),
    ('authentic', 'adj', 'genuine', 'Authentic product.'),
    ('authority', 'noun', 'power', 'Decision authority.'),
    ('authorization', 'noun', 'permission', 'Need authorization.'),
    ('authorize', 'verb', 'to permit', 'Authorize payment.'),
    ('automated', 'adj', 'operating automatically', 'Automated system.'),
    ('automation', 'noun', 'automatic operation', 'Office automation.'),
    ('autonomy', 'noun', 'independence', 'Work autonomy.'),
    ('availability', 'noun', 'being available', 'Check availability.'),
    ('available', 'adj', 'accessible', 'Currently available.'),
    ('avenue', 'noun', 'way', 'New avenue.'),
    ('average', 'adj', 'typical', 'Average cost.'),
    ('aversion', 'noun', 'strong dislike', 'Risk aversion.'),
    ('avoid', 'verb', 'to keep away', 'Avoid delay.'),
    ('avoidance', 'noun', 'keeping away', 'Tax avoidance.'),
    ('await', 'verb', 'to wait for', 'Await response.'),
    ('award', 'noun', 'prize', 'Win award.'),
    ('awareness', 'noun', 'knowledge', 'Brand awareness.'),
    ('backbone', 'noun', 'main support', 'Business backbone.'),
    ('backdrop', 'noun', 'background', 'Economic backdrop.'),
    ('background', 'noun', 'history', 'Professional background.'),
    ('backlog', 'noun', 'accumulated work', 'Order backlog.'),
    ('backup', 'noun', 'reserve', 'Data backup.'),
    ('bail', 'verb', 'to rescue', 'Bail out company.'),
    ('balance', 'noun', 'equilibrium', 'Work-life balance.'),
    ('ballot', 'noun', 'vote', 'Secret ballot.'),
    ('ban', 'verb', 'to prohibit', 'Ban advertising.'),
    ('bankrupt', 'adj', 'financially ruined', 'Go bankrupt.'),
    ('bankruptcy', 'noun', 'financial failure', 'File bankruptcy.'),
    ('banner', 'noun', 'flag or ad', 'Banner ad.'),
    ('bar', 'verb', 'to prevent', 'Bar entry.'),
    ('bargain', 'noun', 'good deal', 'Great bargain.'),
    ('barrier', 'noun', 'obstacle', 'Entry barrier.'),
    ('base', 'noun', 'foundation', 'Customer base.'),
    ('baseline', 'noun', 'starting point', 'Baseline data.'),
    ('batch', 'noun', 'group', 'Batch processing.'),
    ('battery', 'noun', 'power source', 'Battery life.'),
    ('bear', 'verb', 'to carry', 'Bear responsibility.'),
    ('bearer', 'noun', 'carrier', 'Bearer of news.'),
    ('beat', 'verb', 'to defeat', 'Beat competition.'),
    ('beforehand', 'adv', 'in advance', 'Plan beforehand.'),
    ('behalf', 'noun', 'representation', 'On behalf of.'),
    ('behave', 'verb', 'to act', 'Behave professionally.'),
    ('behavior', 'noun', 'conduct', 'Consumer behavior.'),
    ('belongings', 'noun', 'possessions', 'Personal belongings.'),
    ('benchmark', 'noun', 'standard', 'Industry benchmark.'),
    ('beneficial', 'adj', 'helpful', 'Mutually beneficial.'),
    ('beneficiary', 'noun', 'recipient', 'Policy beneficiary.'),
    ('betterment', 'noun', 'improvement', 'Self-betterment.'),
    ('beverage', 'noun', 'drink', 'Beverage industry.'),
    ('bias', 'noun', 'prejudice', 'Avoid bias.'),
    ('bid', 'noun', 'offer', 'Submit bid.'),
    ('bilateral', 'adj', 'two-sided', 'Bilateral agreement.'),
    ('binding', 'adj', 'obligatory', 'Legally binding.'),
    ('blueprint', 'noun', 'plan', 'Business blueprint.'),
    ('board', 'noun', 'committee', 'Board of directors.'),
    ('bond', 'noun', 'financial instrument', 'Government bond.'),
    ('bonus', 'noun', 'extra payment', 'Year-end bonus.'),
    ('booking', 'noun', 'reservation', 'Make booking.'),
    ('booklet', 'noun', 'small book', 'Information booklet.'),
    ('boom', 'noun', 'rapid growth', 'Economic boom.'),
    ('boost', 'verb', 'to increase', 'Boost sales.'),
    ('booth', 'noun', 'stall', 'Trade booth.'),
    ('border', 'noun', 'boundary', 'Cross border.'),
    ('borrower', 'noun', 'one who borrows', 'Loan borrower.'),
    ('bottleneck', 'noun', 'obstacle', 'Production bottleneck.'),
    ('bottom', 'noun', 'lowest point', 'Bottom line.'),
    ('bounce', 'verb', 'to spring back', 'Check bounced.'),
    ('bound', 'adj', 'obligated', 'Legally bound.'),
    ('boundary', 'noun', 'limit', 'Set boundaries.'),
    ('branch', 'noun', 'division', 'Local branch.'),
    ('brand', 'noun', 'trademark', 'Brand name.'),
    ('branding', 'noun', 'brand creation', 'Corporate branding.'),
    ('breach', 'noun', 'violation', 'Data breach.'),
    ('breakdown', 'noun', 'analysis', 'Cost breakdown.'),
    ('breakthrough', 'noun', 'major advance', 'Major breakthrough.'),
    ('brief', 'adj', 'short', 'Brief meeting.'),
    ('briefing', 'noun', 'short meeting', 'Daily briefing.'),
    ('brisk', 'adj', 'active', 'Brisk business.'),
    ('broad', 'adj', 'wide', 'Broad range.'),
    ('broadcast', 'verb', 'to transmit', 'Broadcast message.'),
    ('broaden', 'verb', 'to widen', 'Broaden horizons.'),
    ('brochure', 'noun', 'pamphlet', 'Product brochure.'),
    ('broker', 'noun', 'agent', 'Insurance broker.'),
    ('browse', 'verb', 'to look through', 'Browse catalog.'),
    ('browser', 'noun', 'web viewer', 'Web browser.'),
    ('buck', 'noun', 'dollar', 'Save a buck.'),
    ('buffer', 'noun', 'cushion', 'Financial buffer.'),
    ('bulk', 'noun', 'large quantity', 'Buy in bulk.'),
    ('bulletin', 'noun', 'notice', 'News bulletin.'),
    ('bundle', 'noun', 'package', 'Software bundle.'),
    ('burden', 'noun', 'load', 'Tax burden.'),
    ('bureaucracy', 'noun', 'administration', 'Government bureaucracy.'),
    ('burdensome', 'adj', 'troublesome', 'Burdensome regulations.'),
    ('buyer', 'noun', 'purchaser', 'Potential buyer.'),
    ('bylaw', 'noun', 'rule', 'Company bylaws.'),
    ('bypass', 'verb', 'to go around', 'Bypass procedure.'),
    ('cabinet', 'noun', 'storage', 'File cabinet.'),
    ('calculate', 'verb', 'to compute', 'Calculate cost.'),
    ('calculation', 'noun', 'computation', 'Quick calculation.'),
    ('calendar', 'noun', 'schedule', 'Company calendar.'),
    ('calibrate', 'verb', 'to adjust precisely', 'Calibrate instrument.'),
    ('campaign', 'noun', 'organized effort', 'Marketing campaign.'),
    ('cancel', 'verb', 'to call off', 'Cancel order.'),
    ('cancellation', 'noun', 'calling off', 'Flight cancellation.'),
    ('candidate', 'noun', 'applicant', 'Job candidate.'),
    ('capability', 'noun', 'ability', 'Technical capability.'),
    ('capable', 'adj', 'able', 'Highly capable.'),
    ('capacity', 'noun', 'ability', 'Full capacity.'),
    ('capital', 'noun', 'money', 'Venture capital.'),
    ('capitalize', 'verb', 'to take advantage', 'Capitalize on opportunity.'),
    ('capture', 'verb', 'to get', 'Capture market.'),
    ('carbon', 'noun', 'element', 'Carbon footprint.'),
    ('career', 'noun', 'profession', 'Career path.'),
    ('cargo', 'noun', 'goods', 'Ship cargo.'),
    ('carrier', 'noun', 'transporter', 'Mail carrier.'),
    ('cascade', 'verb', 'to flow down', 'Cascade information.'),
    ('cashier', 'noun', 'checkout person', 'Bank cashier.'),
    ('cast', 'verb', 'to throw', 'Cast vote.'),
    ('catalog', 'noun', 'list', 'Product catalog.'),
    ('category', 'noun', 'class', 'Product category.'),
    ('cater', 'verb', 'to provide', 'Cater to needs.'),
    ('catering', 'noun', 'food service', 'Office catering.'),
    ('caution', 'noun', 'care', 'Exercise caution.'),
    ('cease', 'verb', 'to stop', 'Cease operations.'),
    ('ceiling', 'noun', 'upper limit', 'Price ceiling.'),
    ('celebrate', 'verb', 'to honor', 'Celebrate success.'),
    ('centralize', 'verb', 'to bring to center', 'Centralize operations.'),
    ('ceremony', 'noun', 'formal event', 'Award ceremony.'),
    ('certain', 'adj', 'sure', 'Certain outcome.'),
    ('certainty', 'noun', 'sureness', 'With certainty.'),
    ('certificate', 'noun', 'document', 'Gift certificate.'),
    ('certification', 'noun', 'official approval', 'ISO certification.'),
    ('certify', 'verb', 'to confirm officially', 'Certify document.'),
    ('chain', 'noun', 'series', 'Supply chain.'),
    ('chair', 'verb', 'to lead', 'Chair meeting.'),
    ('chairman', 'noun', 'leader', 'Board chairman.'),
    ('challenge', 'noun', 'difficulty', 'Major challenge.'),
    ('chamber', 'noun', 'room', 'Chamber of commerce.'),
    ('champion', 'verb', 'to support', 'Champion cause.'),
    ('channel', 'noun', 'means', 'Sales channel.'),
    ('chapter', 'noun', 'section', 'New chapter.'),
    ('characteristic', 'noun', 'feature', 'Key characteristic.'),
    ('charge', 'noun', 'fee', 'Service charge.'),
    ('charitable', 'adj', 'generous', 'Charitable donation.'),
    ('charity', 'noun', 'organization', 'Support charity.'),
    ('chart', 'noun', 'diagram', 'Sales chart.'),
    ('charter', 'noun', 'document', 'Company charter.'),
    ('chase', 'verb', 'to pursue', 'Chase payment.'),
    ('cheap', 'adj', 'inexpensive', 'Cheap products.'),
    ('checkout', 'noun', 'payment point', 'At checkout.'),
    ('checkpoint', 'noun', 'control point', 'Security checkpoint.'),
    ('chief', 'adj', 'main', 'Chief executive.'),
    ('chiefly', 'adv', 'mainly', 'Chiefly responsible.'),
    ('choice', 'noun', 'selection', 'Wide choice.'),
    ('chronic', 'adj', 'long-lasting', 'Chronic problem.'),
    ('chronological', 'adj', 'in time order', 'Chronological order.'),
    ('chunk', 'noun', 'piece', 'Large chunk.'),
    ('circuit', 'noun', 'path', 'Circuit board.'),
    ('circulate', 'verb', 'to spread', 'Circulate memo.'),
    ('circulation', 'noun', 'distribution', 'Wide circulation.'),
    ('circumstance', 'noun', 'condition', 'Under circumstances.'),
    ('cite', 'verb', 'to mention', 'Cite sources.'),
    ('citizen', 'noun', 'resident', 'Corporate citizen.'),
    ('civic', 'adj', 'relating to city', 'Civic duty.'),
    ('civil', 'adj', 'relating to citizens', 'Civil law.'),
    ('civilian', 'noun', 'non-military person', 'Civilian staff.'),
    ('civilization', 'noun', 'society', 'Modern civilization.'),
    ('claim', 'verb', 'to assert', 'Claim refund.'),
    ('claimant', 'noun', 'one who claims', 'Insurance claimant.'),
    ('clarification', 'noun', 'explanation', 'Need clarification.'),
    ('clarify', 'verb', 'to make clear', 'Clarify position.'),
    ('clarity', 'noun', 'clearness', 'Provide clarity.'),
    ('classification', 'noun', 'grouping', 'Job classification.'),
    ('classify', 'verb', 'to categorize', 'Classify documents.'),
    ('clause', 'noun', 'provision', 'Contract clause.'),
    ('clear', 'verb', 'to approve', 'Clear payment.'),
    ('clearance', 'noun', 'permission', 'Security clearance.'),
    ('clerk', 'noun', 'office worker', 'Accounts clerk.'),
    ('client', 'noun', 'customer', 'Major client.'),
    ('clientele', 'noun', 'customers', 'Regular clientele.'),
    ('climate', 'noun', 'conditions', 'Business climate.'),
    ('climb', 'verb', 'to rise', 'Sales climb.'),
    ('clinch', 'verb', 'to secure', 'Clinch deal.'),
    ('close', 'verb', 'to complete', 'Close deal.'),
    ('closure', 'noun', 'ending', 'Factory closure.'),
    ('cluster', 'noun', 'group', 'Business cluster.'),
    ('coalition', 'noun', 'alliance', 'Form coalition.'),
    ('code', 'noun', 'system of rules', 'Dress code.'),
    ('coherent', 'adj', 'logical', 'Coherent strategy.'),
    ('coincide', 'verb', 'to happen together', 'Coincide with event.'),
    ('collaborate', 'verb', 'to work together', 'Collaborate on project.'),
    ('collaboration', 'noun', 'working together', 'Close collaboration.'),
    ('collaborative', 'adj', 'cooperative', 'Collaborative effort.'),
    ('collapse', 'verb', 'to fall', 'Market collapse.'),
    ('collateral', 'noun', 'security', 'Loan collateral.'),
    ('colleague', 'noun', 'coworker', 'Dear colleague.'),
    ('collect', 'verb', 'to gather', 'Collect data.'),
    ('collection', 'noun', 'gathering', 'Debt collection.'),
    ('collective', 'adj', 'shared', 'Collective bargaining.'),
    ('collision', 'noun', 'crash', 'Avoid collision.'),
    ('column', 'noun', 'vertical section', 'Spreadsheet column.'),
    ('combination', 'noun', 'mixture', 'Perfect combination.'),
    ('combine', 'verb', 'to join', 'Combine resources.'),
    ('comeback', 'noun', 'return', 'Business comeback.'),
    ('comfort', 'noun', 'ease', 'Customer comfort.'),
    ('comfortable', 'adj', 'at ease', 'Comfortable environment.'),
    ('command', 'verb', 'to order', 'Command respect.'),
    ('commence', 'verb', 'to begin', 'Commence operation.'),
    ('commencement', 'noun', 'beginning', 'Commencement date.'),
    ('commend', 'verb', 'to praise', 'Commend employee.'),
    ('comment', 'noun', 'remark', 'Customer comments.'),
    ('commentary', 'noun', 'explanation', 'Market commentary.'),
    ('commerce', 'noun', 'trade', 'E-commerce.'),
    ('commercial', 'adj', 'business-related', 'Commercial property.'),
    ('commission', 'noun', 'payment', 'Sales commission.'),
    ('commit', 'verb', 'to pledge', 'Commit resources.'),
    ('commitment', 'noun', 'promise', 'Total commitment.'),
    ('committee', 'noun', 'group', 'Planning committee.'),
    ('commodity', 'noun', 'basic good', 'Commodity prices.'),
    ('common', 'adj', 'shared', 'Common goal.'),
    ('commonplace', 'adj', 'ordinary', 'Commonplace occurrence.'),
    ('communicate', 'verb', 'to convey', 'Communicate clearly.'),
    ('communication', 'noun', 'exchange', 'Internal communication.'),
    ('community', 'noun', 'group', 'Business community.'),
    ('commute', 'verb', 'to travel to work', 'Daily commute.'),
    ('commuter', 'noun', 'traveler', 'Regular commuter.'),
    ('compact', 'adj', 'small', 'Compact design.'),
    ('companion', 'noun', 'partner', 'Travel companion.'),
    ('company', 'noun', 'business', 'Start company.'),
    ('comparable', 'adj', 'similar', 'Comparable price.'),
    ('comparative', 'adj', 'relative', 'Comparative analysis.'),
    ('compare', 'verb', 'to examine', 'Compare prices.'),
    ('comparison', 'noun', 'examining', 'In comparison.'),
    ('compartment', 'noun', 'section', 'Storage compartment.'),
    ('compatible', 'adj', 'able to work together', 'Compatible systems.'),
    ('compel', 'verb', 'to force', 'Compel action.'),
    ('compelling', 'adj', 'convincing', 'Compelling argument.'),
    ('compensate', 'verb', 'to pay', 'Compensate fairly.'),
    ('compensation', 'noun', 'payment', 'Fair compensation.'),
    ('compete', 'verb', 'to contend', 'Compete effectively.'),
    ('competence', 'noun', 'ability', 'Core competence.'),
    ('competent', 'adj', 'capable', 'Competent staff.'),
    ('competition', 'noun', 'rivalry', 'Fierce competition.'),
    ('competitive', 'adj', 'eager to compete', 'Competitive market.'),
    ('competitor', 'noun', 'rival', 'Major competitor.'),
    ('compilation', 'noun', 'collection', 'Data compilation.'),
    ('compile', 'verb', 'to gather', 'Compile report.'),
    ('complaint', 'noun', 'criticism', 'Customer complaint.'),
    ('complement', 'verb', 'to complete', 'Complement team.'),
    ('complementary', 'adj', 'completing', 'Complementary products.'),
    ('complete', 'adj', 'whole', 'Complete package.'),
    ('completion', 'noun', 'finishing', 'Project completion.'),
    ('complex', 'adj', 'complicated', 'Complex issue.'),
    ('complexity', 'noun', 'complication', 'Reduce complexity.'),
    ('compliance', 'noun', 'conformity', 'Regulatory compliance.'),
    ('compliant', 'adj', 'conforming', 'Fully compliant.'),
    ('complicate', 'verb', 'to make difficult', 'Complicate matters.'),
    ('complicated', 'adj', 'difficult', 'Complicated process.'),
    ('complication', 'noun', 'difficulty', 'Unexpected complications.'),
    ('compliment', 'noun', 'praise', 'Receive compliment.'),
    ('complimentary', 'adj', 'free', 'Complimentary service.'),
    ('comply', 'verb', 'to follow rules', 'Comply with regulations.'),
    ('component', 'noun', 'part', 'Key component.'),
    ('compose', 'verb', 'to create', 'Compose email.'),
    ('composition', 'noun', 'makeup', 'Team composition.'),
    ('compound', 'adj', 'combined', 'Compound interest.'),
    ('comprehensive', 'adj', 'complete', 'Comprehensive plan.'),
    ('comprise', 'verb', 'to include', 'Team comprises.'),
    ('compromise', 'noun', 'agreement', 'Reach compromise.'),
    ('compulsory', 'adj', 'required', 'Compulsory training.'),
    ('computation', 'noun', 'calculation', 'Quick computation.'),
    ('compute', 'verb', 'to calculate', 'Compute total.'),
    ('conceive', 'verb', 'to imagine', 'Conceive idea.'),
    ('concentrate', 'verb', 'to focus', 'Concentrate efforts.'),
    ('concentration', 'noun', 'focus', 'Market concentration.'),
    ('concept', 'noun', 'idea', 'New concept.'),
    ('concern', 'noun', 'worry', 'Address concerns.'),
    ('concession', 'noun', 'compromise', 'Make concessions.'),
    ('conclude', 'verb', 'to end', 'Conclude deal.'),
    ('conclusion', 'noun', 'ending', 'In conclusion.'),
    ('concrete', 'adj', 'definite', 'Concrete plans.'),
    ('concurrent', 'adj', 'simultaneous', 'Concurrent projects.'),
    ('condemn', 'verb', 'to criticize', 'Condemn actions.'),
    ('condition', 'noun', 'state', 'Market conditions.'),
    ('conditional', 'adj', 'with conditions', 'Conditional approval.'),
    ('conduct', 'verb', 'to carry out', 'Conduct survey.'),
    ('confer', 'verb', 'to discuss', 'Confer with team.'),
    ('conference', 'noun', 'meeting', 'Annual conference.'),
    ('confess', 'verb', 'to admit', 'Confess error.'),
    ('confidence', 'noun', 'trust', 'Build confidence.'),
    ('confident', 'adj', 'sure', 'Confident outlook.'),
    ('confidential', 'adj', 'secret', 'Confidential information.'),
    ('confidentiality', 'noun', 'secrecy', 'Maintain confidentiality.'),
    ('configuration', 'noun', 'arrangement', 'System configuration.'),
    ('configure', 'verb', 'to set up', 'Configure settings.'),
    ('confine', 'verb', 'to limit', 'Confine to area.'),
    ('confirm', 'verb', 'to verify', 'Confirm booking.'),
    ('confirmation', 'noun', 'verification', 'Order confirmation.'),
    ('conflict', 'noun', 'disagreement', 'Resolve conflict.'),
    ('conform', 'verb', 'to comply', 'Conform to standards.'),
    ('conformity', 'noun', 'compliance', 'In conformity.'),
    ('confront', 'verb', 'to face', 'Confront challenge.'),
    ('confrontation', 'noun', 'conflict', 'Avoid confrontation.'),
    ('confuse', 'verb', 'to bewilder', 'Confuse customers.'),
    ('confusion', 'noun', 'uncertainty', 'Avoid confusion.'),
    ('congratulate', 'verb', 'to praise', 'Congratulate team.'),
    ('congratulation', 'noun', 'praise', 'Offer congratulations.'),
    ('congress', 'noun', 'assembly', 'Annual congress.'),
    ('conjunction', 'noun', 'combination', 'In conjunction.'),
    ('connect', 'verb', 'to link', 'Connect systems.'),
    ('connection', 'noun', 'link', 'Business connection.'),
    ('conquer', 'verb', 'to overcome', 'Conquer market.'),
    ('conscience', 'noun', 'moral sense', 'Clear conscience.'),
    ('conscious', 'adj', 'aware', 'Cost conscious.'),
    ('consecutive', 'adj', 'following', 'Consecutive days.'),
    ('consensus', 'noun', 'agreement', 'Reach consensus.'),
    ('consent', 'noun', 'permission', 'Get consent.'),
    ('consequence', 'noun', 'result', 'Serious consequences.'),
    ('consequently', 'adv', 'as a result', 'Consequently successful.'),
    ('conservation', 'noun', 'preservation', 'Energy conservation.'),
    ('conservative', 'adj', 'cautious', 'Conservative estimate.'),
    ('conserve', 'verb', 'to save', 'Conserve resources.'),
    ('consider', 'verb', 'to think about', 'Consider options.'),
    ('considerable', 'adj', 'significant', 'Considerable savings.'),
    ('consideration', 'noun', 'thought', 'Under consideration.'),
    ('consist', 'verb', 'to be made of', 'Consist of parts.'),
    ('consistency', 'noun', 'uniformity', 'Brand consistency.'),
    ('consistent', 'adj', 'uniform', 'Consistent quality.'),
    ('consolidate', 'verb', 'to combine', 'Consolidate operations.'),
    ('consolidation', 'noun', 'combining', 'Market consolidation.'),
    ('consortium', 'noun', 'group', 'Business consortium.'),
    ('constant', 'adj', 'continuous', 'Constant change.'),
    ('constantly', 'adv', 'always', 'Constantly improving.'),
    ('constituency', 'noun', 'group of supporters', 'Customer constituency.'),
    ('constituent', 'noun', 'component', 'Key constituent.'),
    ('constitute', 'verb', 'to make up', 'Constitute majority.'),
    ('constitution', 'noun', 'structure', 'Company constitution.'),
    ('constraint', 'noun', 'limitation', 'Budget constraints.'),
    ('construct', 'verb', 'to build', 'Construct building.'),
    ('construction', 'noun', 'building', 'Under construction.'),
    ('constructive', 'adj', 'helpful', 'Constructive feedback.'),
    ('consult', 'verb', 'to ask advice', 'Consult expert.'),
    ('consultant', 'noun', 'adviser', 'Management consultant.'),
    ('consultation', 'noun', 'discussion', 'Free consultation.'),
    ('consume', 'verb', 'to use', 'Consume resources.'),
    ('consumer', 'noun', 'buyer', 'Consumer goods.'),
    ('consumption', 'noun', 'use', 'Energy consumption.'),
    ('contact', 'verb', 'to communicate', 'Contact customer.'),
    ('contain', 'verb', 'to hold', 'Contain costs.'),
    ('container', 'noun', 'holder', 'Shipping container.'),
    ('contaminate', 'verb', 'to pollute', 'Contaminate supply.'),
    ('contamination', 'noun', 'pollution', 'Prevent contamination.'),
    ('contemplate', 'verb', 'to consider', 'Contemplate change.'),
    ('contemporary', 'adj', 'modern', 'Contemporary design.'),
    ('contend', 'verb', 'to argue', 'Contend with issues.'),
    ('content', 'noun', 'material', 'Website content.'),
    ('contention', 'noun', 'dispute', 'Point of contention.'),
    ('contest', 'verb', 'to challenge', 'Contest decision.'),
    ('context', 'noun', 'circumstances', 'Business context.'),
    ('contingency', 'noun', 'possibility', 'Contingency plan.'),
    ('contingent', 'adj', 'dependent', 'Contingent on approval.'),
    ('continual', 'adj', 'repeated', 'Continual improvement.'),
    ('continuation', 'noun', 'continuing', 'Continuation of service.'),
    ('continue', 'verb', 'to go on', 'Continue work.'),
    ('continuity', 'noun', 'unbroken flow', 'Business continuity.'),
    ('continuous', 'adj', 'unbroken', 'Continuous improvement.'),
    ('contract', 'noun', 'agreement', 'Sign contract.'),
    ('contractor', 'noun', 'hired worker', 'Independent contractor.'),
    ('contradict', 'verb', 'to deny', 'Contradict statement.'),
    ('contradiction', 'noun', 'inconsistency', 'Clear contradiction.'),
    ('contrary', 'adj', 'opposite', 'On the contrary.'),
    ('contrast', 'noun', 'difference', 'In contrast.'),
    ('contribute', 'verb', 'to give', 'Contribute ideas.'),
    ('contribution', 'noun', 'giving', 'Major contribution.'),
    ('contributor', 'noun', 'giver', 'Key contributor.'),
    ('control', 'noun', 'power', 'Quality control.'),
    ('controversial', 'adj', 'disputed', 'Controversial decision.'),
    ('controversy', 'noun', 'dispute', 'Cause controversy.'),
    ('convene', 'verb', 'to assemble', 'Convene meeting.'),
    ('convenience', 'noun', 'ease', 'Customer convenience.'),
    ('convenient', 'adj', 'handy', 'Convenient location.'),
    ('convention', 'noun', 'meeting', 'Annual convention.'),
    ('conventional', 'adj', 'traditional', 'Conventional approach.'),
    ('conversation', 'noun', 'talk', 'Business conversation.'),
    ('conversion', 'noun', 'change', 'Currency conversion.'),
    ('convert', 'verb', 'to change', 'Convert currency.'),
    ('convey', 'verb', 'to communicate', 'Convey message.'),
    ('convince', 'verb', 'to persuade', 'Convince customer.'),
    ('cooperate', 'verb', 'to work together', 'Cooperate fully.'),
    ('cooperation', 'noun', 'working together', 'International cooperation.'),
    ('cooperative', 'adj', 'helpful', 'Cooperative effort.'),
    ('coordinate', 'verb', 'to organize', 'Coordinate efforts.'),
    ('coordination', 'noun', 'organization', 'Better coordination.'),
    ('coordinator', 'noun', 'organizer', 'Project coordinator.'),
    ('cope', 'verb', 'to deal with', 'Cope with pressure.'),
    ('copy', 'noun', 'reproduction', 'Extra copy.'),
    ('core', 'noun', 'center', 'Core business.'),
    ('corner', 'verb', 'to gain control', 'Corner market.'),
    ('corporate', 'adj', 'business', 'Corporate culture.'),
    ('corporation', 'noun', 'company', 'Large corporation.'),
    ('correct', 'verb', 'to fix', 'Correct error.'),
    ('correction', 'noun', 'fixing', 'Market correction.'),
    ('correlation', 'noun', 'relationship', 'Strong correlation.'),
    ('correspond', 'verb', 'to communicate', 'Correspond by email.'),
    ('correspondence', 'noun', 'letters', 'Business correspondence.'),
    ('correspondent', 'noun', 'reporter', 'News correspondent.'),
    ('corresponding', 'adj', 'matching', 'Corresponding increase.'),
    ('corridor', 'noun', 'hallway', 'Office corridor.'),
    ('corrupt', 'adj', 'dishonest', 'Corrupt practices.'),
    ('corruption', 'noun', 'dishonesty', 'Fight corruption.'),
    ('costly', 'adj', 'expensive', 'Costly mistake.'),
    ('council', 'noun', 'committee', 'City council.'),
    ('counsel', 'noun', 'advice', 'Legal counsel.'),
    ('counselor', 'noun', 'adviser', 'Career counselor.'),
    ('count', 'verb', 'to include', 'Count on support.'),
    ('counter', 'noun', 'service area', 'Service counter.'),
    ('counteract', 'verb', 'to act against', 'Counteract effects.'),
    ('counterfeit', 'adj', 'fake', 'Counterfeit goods.'),
    ('counterpart', 'noun', 'equivalent', 'Foreign counterpart.'),
    ('countless', 'adj', 'very many', 'Countless opportunities.'),
    ('countryside', 'noun', 'rural area', 'Countryside office.'),
    ('county', 'noun', 'district', 'County office.'),
    ('coup', 'noun', 'achievement', 'Marketing coup.'),
    ('couple', 'noun', 'pair', 'A couple of days.'),
    ('coupon', 'noun', 'voucher', 'Discount coupon.'),
    ('courier', 'noun', 'messenger', 'Express courier.'),
    ('course', 'noun', 'path', 'Course of action.'),
    ('court', 'noun', 'law court', 'Court case.'),
    ('courtesy', 'noun', 'politeness', 'Common courtesy.'),
    ('coverage', 'noun', 'protection', 'Insurance coverage.'),
]

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    existing = data.get('words', data)

print(f'기존 단어: {len(existing)}개')
word_set = {w['word'].lower() for w in existing}
new_words = [(w,p,m,e) for w,p,m,e in WORDS if w.lower() not in word_set]
print(f'추가할 새 단어: {len(new_words)}개')

if not new_words:
    print('추가할 단어 없음')
    exit()

langs = ['ko','ja','zh','es','pt','de','fr','vi','ar','id']
trans_by_lang = {}
print('번역 중...')
for lang in langs:
    print(f'  {lang}...', end=' ', flush=True)
    trans_by_lang[lang] = translate_batch([w[2] for w in new_words], lang)
    print('완료')
    time.sleep(0.2)

count = len(existing)
total = count + len(new_words)
for i, (word, pos, meaning, example) in enumerate(new_words):
    word_id = count + i + 1
    if word_id <= total // 4:
        level = '0-400'
    elif word_id <= total // 2:
        level = '400-600'
    elif word_id <= total * 3 // 4:
        level = '600-800'
    else:
        level = '800-990'
    trans = {lang: trans_by_lang[lang][i] if i < len(trans_by_lang[lang]) else meaning for lang in langs}
    existing.append({'id': word_id, 'word': word, 'meaning': meaning, 'example': example, 'pos': pos, 'level': level, 'translations': trans})

with open('assets/data/words.json', 'w', encoding='utf-8') as f:
    json.dump({'words': existing}, f, ensure_ascii=False, indent=2)

level_counts = {}
for w in existing:
    lv = w.get('level', '0-400')
    level_counts[lv] = level_counts.get(lv, 0) + 1

print(f'\n총 단어 수: {len(existing)}개')
for lv in ['0-400', '400-600', '600-800', '800-990']:
    print(f'  {lv}: {level_counts.get(lv, 0)}개')
