workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - toefl_keystore
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.jhjo.toefl_vocab_app"
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate localizations
        script: |
          flutter gen-l10n
      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hoonijo@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: TOEFL Vocab App
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jhjo.toeflVocabApp
      vars:
        APP_ID: 0000000000
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate localizations
        script: |
          flutter gen-l10n
      - name: Clean and rebuild
        script: |
          flutter clean
          flutter pub get
          flutter gen-l10n
      - name: Install pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hoonijo@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
